= Prüfschritt 11.7 Benutzerdefinierte Einstellungen
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Die Seite soll benutzerdefinierte Browsereinstellungen berücksichtigen.
Im Einzelnen können dies folgende Punkte sein:

* Maßeinheiten
* Farben (z. B. Darkmode)
* Kontraste
* Schriftarten
* Schriftgrößen
* Darstellung des Fokuscursors

Die Seite kann darüber hinaus eigene Werte für diese Einstellungen anbieten, wenn diese Einstellungen nicht genutzt werden, sollen die Browsereinstellungen übernommen werden.

== Warum wird das geprüft?

Wenn Menschen eigene Einstellungen im System oder im Browser vornehmen, zum Beispiel weil sie größere Schrift oder eigene angepasste Farbeinstellungen brauchen, sollen diese vom Webangebot wo immer möglich respektiert und übernommen werden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

=== 2. Prüfung

. Die Seite im Firefox Browser laden
. Einstellungen öffnen (Element Menü öffnen > Einstellungen)
. Im Bereich "Sprache und Erscheinungsbild" Die Größe auf einen deutlich höheren Wert als den Standard-Wert setzen (z.B. 24)
. Den Button "Farben..." wählen, veränderte Text und Hintergrundfarbe einstellen, die Checkbox "Systemfarben verwenden" deaktivieren und bei der Auswahlliste "Oben ausgewählte Farben anstatt der Farben der Seite verwenden" den Wert "Immer" auswählen, dann mit "OK" bestätigen.
. Prüfen, ob sich die Einstellungen auf die Darstellung der Seite auswirken.

=== 3. Hinweise

* Wenn einer der genannten Einstellungen in den verschiedenen Browsern nicht zu finden ist und somit vom Nutzer nicht angepasst werden kann, wird diese Einstellung bei der Prüfung nicht berücksichtigt.
* Änderungen der Standard-Schriftart werden zur Zeit weder im Firefox- noch im Chrome-Browser übernommen, sobald über CSS für die zu prüfende Seite eine Schriftart festgelegt worden ist, etwa über `font-family` auf dem `body`-Element. Die Wirksamkeit der Änderung der Standard-Schriftart wird deshalb zurzeit nicht geprüft.
* Die Schriftart und -Größe muss sich nur in Fließtexten an die Einstellungen anpassen. Es wird nicht verlangt, dass Bedienelemente der Webseite dynamische Veränderungen dieser Einstellungen unterstützen, da hiermit das Layout der Webseite verändert würde.

Für die Praxis fehlen noch Hinweise. Sie können auf GitHub
https://github.com/BIK-BITV/BIK-Web-Test/issues[ein Issue zu diesem Prüfschritt erstellen], um bei der Entwicklung der Prüfung mitzuwirken

=== 4. Bewertung

==== Erfüllt: 

Die Seite wird nach dem Vornehmen von eigenen Farbeinstellungen (z.B. heller Text auf dunklem Hintergrund) richtig dargestellt, Fließtexte erscheinen nach Vergrößerung der Standard-Schriftgröße in den Browsereinstellungen vergrößert.

==== Nicht voll erfüllt:
 
* Texte haben bei Nutzung eigener Farbeinstellungen nicht genug Kontrast oder verschwinden
* Fließtext wird nicht vergrößert dargestellt.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1, Annex A

Tabelle A1 verweist auf Abschnitt 11.7 "User preferences".

== Quellen

[.BLOCK_LANG_EN]
=== 11.7 User preferences

[.BLOCK_LANG_EN]
--
Where Web-App is not designed to be isolated from its platform, and provides
a user interface, that user interface shall follow the values of the user
preferences for platform settings for:
units of measurement, colour, contrast, font type, font 
size, and focus cursor except where they are overridden by the user.

NOTE 1:
Web-App that is isolated from its underlying platform has no access to user
settings in the platform and thus cannot adhere to them.

NOTE 2:
For web content, the underlying platform is the user agent.

NOTE 3:
This does not preclude the Web-App from having additional values for a
setting as long as there is one mode where the application will follow the
system settings even if more restricted.
--

(Aus EN 301 549 V3.1.1 Abschnitt 11.7 "User preferences")
