= Prüfschritt 11.7 Benutzerdefinierte Einstellungen
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Die Seite soll benutzerdefinierte Browsereinstellungen berücksichtigen.
Im Einzelnen können dies folgende Punkte sein:

* Maßeinheiten
* Farben
* Kontraste
* Schriftarten
* Schriftgrößen
* Darstellung des Fokuscursors

Die Seite kann darüber hinaus eigene Werte für diese Einstellungen anbieten, wenn diese Einstellungen nicht genutzt werden, sollen die Browsereinstellungen übernommen werden. In manchen Fällen muss die Seite neu geladen werden, damit sich die Änderungen auswirken.

== Warum wird das geprüft?

Wenn Menschen eigene Einstellungen im Browser vornehmen, zum Beispiel weil sie größere Schrift oder eigene angepasste Farbeinstellungen brauchen, sollen diese vom Webangebot wo immer möglich respektiert und übernommen werden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

=== 2. Prüfung

. Die Seite im Firefox Browser laden
. Einstellungen öffnen (Element Menü öffnen > Einstellungen)
. Im Bereich "Sprache und Erscheinungsbild" die Schriftgröße auf einen deutlich höheren Wert als den Standard-Wert setzen (z.B. 24). In den Einstellungen "Erweitert..." sollte für Mindestschriftgröße "Keine" ausgewählt sein.
. Über den Button "Erweitert..." für die Schriftarten "Serif", "Sans Serif" und "Feste Breite" deutlich abweichende Schrifttypen (Fonts) einstellen und bei der Checkbox "Seiten das Verwenden von eigenen statt der oben gewählten Schriftarten erlauben" den Haken entfernen.
. Den Button "Farben..." wählen, veränderte Text und Hintergrundfarbe einstellen, die Checkbox "Systemfarben verwenden" deaktivieren und bei der Auswahlliste "Oben ausgewählte Farben anstatt der Farben der Seite verwenden" den Wert "Immer" auswählen, dann mit "OK" bestätigen.
. Prüfen, ob sich Einstellungen der Schrifttype, Schriftgröße und Vorder- bzw. Hintergrund-Farben auf die Darstellung der Seite auswirken und übernommen werden.

=== 3. Hinweise
==== 3.1. Einzusetzender Browser für die Prüfung
Zur Prüfung sollte wenn möglich der Firefox-Browser genutzt werden, der diese Einstellungsmöglichkeiten bietet. In anderen Browsern sind ggf. nicht alle diese Einstellungen zu finden, oder sie sind unwirksam.

Wenn zur Prüfung andere Browser genutzt werden und sich die Darstellung trotz geänderter Voreinstellungen nicht ändert, kann dies am Browser oder auch an Vorgaben der Web-Anwendung liegen.

==== 3.2 Hinweis zur Prüfung mit Firefox
Der Firefox-Browser übernimmt für `button`-Elemente die vom Nutzer gewählte Hintergrundfarbe nicht bzw. setzt eine eigene Farbe. Dies darf nicht als Fehler bewertet werden. 

Für die Praxis fehlen noch Hinweise. Sie können auf GitHub
https://github.com/BIK-BITV/BIK-Web-Test/issues[ein Issue zu diesem Prüfschritt erstellen], um bei der Entwicklung der Prüfung mitzuwirken

=== 4. Bewertung

==== Erfüllt

* Die Seite wird im Firefox-Browser nach dem Vornehmen von abweichenden Einstellungen (z.B. heller Text auf dunklem Hintergrund) entsprechend anders dargestellt, Schriften erscheinen vergrößert und in der jeweils eingestelten Schrifttype.

==== Nicht voll erfüllt
 
* Aufgrund von benutzerdefinierten Farbeinstellungen treten beispielsweise Probleme auf wie:
** informationstragende Grafiken oder grafische Bedienelmente sind nicht mehr sichtbar
** Texte auf Grafiken kontrastieren nicht mehr ausreichend (es fehlt ein definierter Hintergrund)
** Schriften von Logos sind nicht mehr lesbar, weil sie einen transparenten Hintergrund haben
** Fließtext wird nicht vergrößert dargestellt oder ist nicht mehr lesbar

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

11.7 User preferences

== Quellen

[.BLOCK_LANG_EN]
=== 11.7 User preferences

[.BLOCK_LANG_EN]
--
Where Web-App is not designed to be isolated from its platform, and provides
a user interface, that user interface shall follow the values of the user
preferences for platform settings for:
units of measurement, colour, contrast, font type, font 
size, and focus cursor except where they are overridden by the user.

NOTE 1:
Web-App that is isolated from its underlying platform has no access to user
settings in the platform and thus cannot adhere to them.

NOTE 2:
For web content, the underlying platform is the user agent.

NOTE 3:
This does not preclude the Web-App from having additional values for a
setting as long as there is one mode where the application will follow the
system settings even if more restricted.
--

(Aus EN 301 549 V3.1.1 Abschnitt 11.7 "User preferences")
