= Prüfschritt 11.8.2 Barrierefreie Erstellung von Inhalten
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Grundlage des Prüfschritts ist die Tabelle A.1 im Annex A der EN 301 549
V3.1.1.
In dieser Tabelle wird auf Abschnitt
11.8.2 "Accessible content creation" verwiesen.

== Was wird geprüft?

Wenn es sich bei der zu testenden Web-App um ein Autorenwerkzeug handelt, soll
die Anwendung die Erstellung von barrierefreien Dokumenten erlauben und den
Nutzer dabei unterstützen.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist bei der Prüfung von Autorenwerzeugen wie Content Management Systemen anwendbar,  Ergebnis eines Autorenwerkzeugs ist, etwa eines Content Management Systems. Ebenfalls anwendbar ist der Prüfschritt auf Kommentarfunktionen, die die Strukturierung von Kommentare erlauben, etwa die Vergabe einer Kommentareüberschrift oder Funktionen zur Binnenauszeichnung des Kommentars, wie etwa Listen oder Texthervorhebungen.

Die Prüfung bezieht sich auf die Ausgabe des jeweiligen Autorenwerkzeugs.

Der Dokumenttyp, den das Autorenwerkzeug erstellt, muss für die Barrierefreiheit optimierbar sein, ansonsten ist dieser Prüfschritt nicht anwendbar. Dies ist für Web Content Managment Systeme und Kommentarfunktionen grundsätzlich gegeben. 

Die Ausgabe des Autorenwerkzeugs muss innerhalb einer Webumgebung dargestellt werden. Es können lediglich Autorenwerkzeuge geprüft werden, die eine HTML-Ausgabe generieren, die auch für die Überprüfung verfügbar ist, etwa in einer Vorschau. 
Zudem können in das Frontend integrierte Werkzeuge wie z. B. Kommentareditoren getestet werden, deren Output entweder unmittelbar oder nach Freigabe überprüft werden kann.
Umfangreiche Autorenwerkzeuge, wie z. B. Textverarbeitungen können im BITV-Test derzeit nicht geprüft werden, da in diesem Verfahren die Barrierefreiheit der durch das Tool generierten Dateien nicht überprüft werden kann.

=== Prüfung

Für die Praxis fehlt noch eine praktikable Methode, Für  Hinweise dazu können Sie auf GitHub {web-issue-url}[ein Issue zu diesem Prüfschritt erstellen].

Auf der Seite wird mittels des Autorenwerkzeugs (z. B. Kommentarfunktion) eine Ausgabe generiert (und ggf. freigegeben).
Die Ansicht der Seite, in der die Ausgabe angezeigt wird, muss dann bei der Prüfung berücksichtigt werden.
Alle für die Ansicht anwendbaren Prüfschritte sind anzuwenden. Einige Beispiele:

*  Im Autorenwerkzeug festgelegte Überschriften sollen in der Ausgabe mit Überschriften-Markup ausgezeichnet sein (also nicht über Fettung oder CSS Styles)
*  Im Autorenwerkzeug angelegte Listen sollen in der Ausgabe mit Listen-Markup ausgezeichnet sein (also nicht Pseudo-Listen über vorangestellte Spiegelstriche)
*  Im Autorenwerkzeug festgelegte Absätze sollten in der Ausgabe mit Absatz-Markup ausgezeichnet sein (nicht div)
*  Im Autorenwerkzeug festgelegte Text-Hervorhebungen sollen in der Ausgabe mit semantischen Elementen wie strong oder em ausgezeichnet sein.
*  Falls das Autorenwerkzeug die Einfügung von Bildern erlaubt, gibt es die Möglichkeit, einen Alternativtext für das Bide zu definieren. Der Alternativtext wird als alt-Attribut übernommen.

==== Hinweise

Das Autorenwerkzeug darf für die Erstellung von barrierefreien Dokumenten von
anderen Werkzeugen abhängen, um spezifische Kriterien zu erfüllen.
Das könnte z. B. ein zusätzliches Werkzeug für die Erstellung von Untertiteln
sein.

== Quellen

[.BLOCK_LANG_EN]
=== 11.8.2 Accessible content creation

[.BLOCK_LANG_EN]
--
Authoring tools shall enable and guide the production of content that conforms
to clauses 9 (Web content) or 10 (Non-Web content) as applicable.

NOTE:
Authoring tools may rely on additional tools where conformance with specific
requirements is not achievable by a single tool.
For example, a video editing tool may enable the creation of video files for
distribution via broadcast television and the web, but authoring of caption
files for multiple formats may be provided by a different tool.
--

(Aus EN 301 549 V3.1.1 Abschnitt 11.8.2 "Accessible content creation")
