= Prüfschritt 11.8.4 Reparaturassistenz
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Grundlage des Prüfschritts ist die Tabelle A.1 im Annex A der EN 301 549
V3.1.1.
In dieser Tabelle wird auf Abschnitt
11.8.4 "Repair assistance" verwiesen.

== Was wird geprüft?

Wenn die Seite Teil eines Autorenwerkzeugs ist und Funktionen zur Erkennung von
Barrierefreiheits-Fehlern bei der Erstellung von Dokumenten bietet, soll sie
Vorschläge zur Behebung dieser Fehler machen.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Seite Teil eines Autorenwerkzeugs ist
oder eine Autorfunktion enthält (etwa eine Kommentarfunktion), und
Barrierefreiheits-Fehler in den erstellten Dokumenten bzw. Inhalten aufzeigen
kann (z. B. "Bitte vergeben Sie eine Überschrift" oder
"Wenn Sie ein informationstragendes Bild einfügen, vergeben Sie bitte einen
passenden Alternativtext").

=== Prüfung

. Auf der Seite Inhalte erstellen und dabei vorhandene
  Auszeichnungsmöglichkeiten *nicht* nutzen, z. B.:
   * Vorhandene Felder für Überschriften leer lassen,
     Überschriftenauszeichung von Text-Editoren nicht nutzen
   * Bilder einfügen, ohne einen Alternativtext festzulegen
   * In ein E-Mail-Adressen-Feld eine fehlerhafte E-Mail-Adresse eingeben

. Inhalt sichern oder abschicken und prüfen, ob eine Überprüfung auf
  Fehler stattfindet
. Falls eine Fehlerprüfung stattfindet (z. B. wenn das Sichern oder Abschicken
  nicht möglich ist bzw. fehlerhafte oder fehlende Eingaben grafisch
  hervorgehoben werden),
  prüfen, ob Hinweise für die Korrektur der Fehler gegeben werden

=== Hinweise
Der Begriff "Dokumente" wird in dieser Anforderung weit gefasst und umfasst Web-
und Nicht-Web-Dokumente.
Siehe dazu auch Kapitel 9 (Web-Inhalte) und Kapitel 10 (Nicht-Web-Inhalte) der
EN 301 549.

Für die Prüfpraxis sind weitere Hinweise notwendig, auf GitHub können Sie
https://github.com/BIK-BITV/BIK-Web-Test/issues[dazu ein Issue eröffnen].

== Quellen

[.BLOCK_LANG_EN]
=== 11.8.4 Repair assistance

[.BLOCK_LANG_EN]
--
If the accessibility checking functionality of an authoring tool can detect
that content does not meet a requirement of clauses 9 (Web) or 10 (Non-web
documents) as applicable, then the authoring tool shall provide repair
suggestion(s). 

NOTE:
This does not preclude automated and semi-automated repair which is possible
(and encouraged) for many types of content accessibility problems. 
--

(Aus EN 301 549 V3.1.1 Abschnitt 11.8.4 "Repair assistance")
