= Prüfschritt 11.8.3 Erhaltung von Barrierefreiheitsinformationen bei Transformation
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Grundlage des Prüfschritts ist die Tabelle A.2 im Annex A der EN 301 549
V3.1.1.
In dieser Tabelle wird auf Abschnitt
11.8.3 "Preservation of accessibility information in transformations" verwiesen.

== Was wird geprüft?

Wenn die Software ein Autorenwerkzeug ist und Umstrukturierungen oder
Funktionen zur Neucodierung bietet, dann werden die Informationen zur
Zugänglichkeit in der Ausgabe, wenn gleichwertige Mechanismen zur Speicherung
der Zugänglichkeitsinformationen im Zieldokumententyp der Ausgabe existieren,
übernommen.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Software ein Autorenwerkzeug ist und
Umstrukturierungen (Restrukturierungstransformationen) oder Funktionen zur
Neucodierung bietet.

==== Restrukturierungstransformationen

Restrukturierungstransformationen sind Transformationen, bei denen 
die strukturellen Merkmale sich ändern (z.B. Linearisierung von Tabellen,
Aufteilen eines Dokuments in Seiten oder wenn einzelne PDF-Dokumente in eine
Datei zusammengeführt werden).
Der Dokumententyp bzw. die Technologie bleibt gleich.

==== Rekodierungstransformationen 

Rekodierungstransformationen sind Transformationen, bei denen die Technologie
bzw. der Dokumententyp geändert wird.
Dies könnte z. B. die Umwandlung eines HTML-Dokuments zum PDF sein.

=== Prüfung

Für die Praxis fehlt noch eine praktikable Methode, Für  Hinweise dazu können
Sie auf GitHub
{app-issue-url}[ein Issue zu diesem Prüfschritt erstellen].

Für die Prüfung muss ein Beispieldokument im Eingangsformat vorgehalten
werden.
Z. B. bei der Rekodierungstransformation von HTML nach PDF, eine HTML-Datei.

Anschließend wird die Eingangsdatei in der App geöffnet und in das
Zielformat bzw. in eine andere Struktur umgewandelt.

Zum Schluss muss die Zieldatei überprüft werden, je nach Dokumententyp sind
dies sehr individuelle Schritte.
Hier können nur Beispiele genannt werden, z. B. die Transformation eines HTML-
zum PDF-Dokument:

* Sind alle Überschriften aus der Quelle übernommen worden?
* Sind die Alternativtexte der Grafiken in der PDF-Datei enthalten
* Wurde die Tabellenauszeichnung korrekt übersetzt?
* ...

Die Schritte müssen für jedes Ein- und Ausgangsformat, das die Software für
die Transformation unterstützt, wiederholt werden.

Auch wenn die Software lediglich die Struktur des Eingangsdokuments verändert,
muss sichergestellt werden, dass die Ausgangsdatei noch alle, für die
Barrierefreiheit relevanten, Informationen enthält.

== Quellen

[.BLOCK_LANG_EN]
=== 11.8.3 Preservation of accessibility information in transformations

[.BLOCK_LANG_EN]
--
If the authoring tool provides restructuring transformations or re-coding
transformations, then accessibility information shall be preserved in the
output if equivalent mechanisms exist in the content technology of the output. 

NOTE 1:
Restructuring transformations are transformations in which the content
technology stays the same, but the structural features of the content are
changed (e.g. linearizing tables, splitting a document into pages). 

NOTE 2:
Re-coding transformations are transformations in which the technology used to
encode the content is changed.
--

(Aus EN 301 549 V3.1.1 Abschnitt 11.8.3 "Preservation of accessibility
information in transformations")
