= Prüfschritt 11.8.4 Reparaturassistenz
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Ist die Seite Teil eines Autorenwerkzeugs und bietet Funktionen zur Erkennung von
Barrierefreiheits-Fehlern bei der Erstellung von Dokumenten, dann sollen
Vorschläge zur Behebung dieser Fehler verfügbar sein.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, 
wenn die Seite Teil eines Autorenwerkzeugs ist 
oder eine Autorfunktion enthält (etwa eine Kommentarfunktion). 
Barrierefreiheits-Fehler in den erstellten Dokumenten bzw. Inhalten 
können aufgezeigt werden (z. B. "Bitte vergeben Sie eine Überschrift" 
oder "Wenn Sie ein informationstragendes Bild einfügen, 
vergeben Sie bitte einen passenden Alternativtext").

=== 2. Prüfung

. Auf der Seite Inhalte erstellen und dabei vorhandene
  Auszeichnungsmöglichkeiten *nicht* nutzen, z. B.:
   * Vorhandene Felder für Überschriften leer lassen,
     Überschriftenauszeichung von Text-Editoren nicht nutzen
   * Bilder einfügen, ohne einen Alternativtext festzulegen
   * In ein E-Mail-Adressen-Feld eine fehlerhafte E-Mail-Adresse eingeben

. Inhalt sichern oder abschicken und prüfen, ob eine Überprüfung auf
  Fehler stattfindet.
. Falls eine Fehlerprüfung stattfindet (z. B. wenn das Sichern oder Abschicken
  nicht möglich ist bzw. fehlerhafte oder fehlende Eingaben grafisch
  hervorgehoben werden),
  prüfen, ob Hinweise für die Korrektur der Fehler gegeben werden.

=== 3. Hinweise
Der Begriff "Dokumente" wird in dieser Anforderung weit gefasst und umfasst Web-
und Nicht-Web-Dokumente.
Siehe dazu auch Kapitel 9 (Web-Inhalte) und Kapitel 10 (Nicht-Web-Inhalte) der
EN 301 549.

Für die Prüfpraxis sind weitere Hinweise notwendig, auf GitHub können Sie
https://github.com/BIK-BITV/BIK-Web-Test/issues[dazu ein Issue eröffnen].

== Quellen
* Zurzeit keine Quellen. 

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.2.1

[.BLOCK_LANG_EN]
==== 11.8.4 Repair assistance
____
[.BLOCK_LANG_EN]
--
If the accessibility checking functionality of an authoring tool can detect
that content does not meet a requirement of clauses 9 (Web) or 10 (Non-web
documents) as applicable, then the authoring tool shall provide repair
suggestion(s). 

NOTE:
This does not preclude automated and semi-automated repair which is possible
(and encouraged) for many types of content accessibility problems. 
--
____
