= Prüfschritt 11.8.4 Reparaturassistenz
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Grundlage des Prüfschritts ist die Tabelle A.2 im Annex A der EN 301 549
V3.1.1.
In dieser Tabelle wird auf Abschnitt
11.8.4 "Repair assistance" verwiesen.

== Was wird geprüft?

Wenn die Software ein Autorenwerkzeug ist und Funktionen zur Erkennung von
Barrierefreiheitsproblemen in Dokumenten, die das Werkzeug unterstützt,
anbietet, soll die Software Vorschläge zur Reparatur dieser Probleme machen.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Software ein Autorenwerkzeug ist und
Probleme in Bezug auf Barrierefreiheit in den Dokumenten, welche die Software
erstellen kann, detektieren kann.

=== Prüfung

Für die Prüfpraxis sind weitere Hinweise notwendig, auf GitHub können Sie
{app-issue-url}[dazu ein Issue eröffnen].

Wenn die Software Probleme im Bereich Barrierefreiheit in den Dokumenten
erkennt und auflistet, sollen für die einzelnen Probleme Hinweise für die
Reparatur gegeben werden.

Der Begriff "Dokumente" wird dabei weit gefasst und umfasst Web- und
Nicht-Web-Dokumente.
Siehe dazu auch Kapitel 9 (Web-Inhalte) und Kapitel 10 (Nicht-Web-Inhalte) der
EN 301 549.

== Quellen

[.BLOCK_LANG_EN]
=== 11.8.4 Repair assistance

[.BLOCK_LANG_EN]
--
If the accessibility checking functionality of an authoring tool can detect
that content does not meet a requirement of clauses 9 (Web) or 10 (Non-web
documents) as applicable, then the authoring tool shall provide repair
suggestion(s). 

NOTE:
This does not preclude automated and semi-automated repair which is possible
(and encouraged) for many types of content accessibility problems. 
--

(Aus EN 301 549 V3.1.1 Abschnitt 11.8.4 "Repair assistance")
