= Prüfschritt 12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn ein Webangebot Dokumentation bereitstellt (und dazu gehört auch die Erklärung zur Barrierefreiheit), dann soll diese Dokumentation vorhandene zusätzliche Barrierefreiheits-Eigenschaften und -Funktionen auflisten und deren Nutzung erklären, sofern diese als Teil des Web-Angebots selbst implementiert wurden. Dazu gehören zum Beispiel Vorlesefunktionen, Funktionen zum Einstellen individueller Farbschemata, oder verfügbare Tastaturkurzbefehle. Auch Informationen zur (möglicherweise eingeschränkten) Kompatibilität mit assistiven Technologien zählen dazu.

== Warum wird das geprüft?

Wenn Angebote bestimmte Barrierefreiheitsfunktionen enthalten, sollten diese gut dokumentiert sein, denn viele Nutzende werden ohne ausdrückliche Hinweise diese Funktionen nicht erkennen oder nutzen können.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Dieser Prüfschritt ist anwendbar, wenn für das Angebot eine Dokumentation vorhanden und auf HTML-Basis integriert ist. Eine Dokumentation, die ausschließlich außerhalb der Webseite bereitgestellt wird, und / oder in anderen Formaten vorliegt, kann nicht im Rahmen dieses Prüfverfahrens mitgetestet werden. Die entsprechende Dokumentation muss dann in einem separaten Auftrag geprüft werden. Die Erklärung zur Barrierefreiheit ist als Dokumentation des Angebots einzustufen.

=== 2. Prüfung

Alle für die Barrierefreiheit relevanten Informationen zur Webseite sollen in der Dokumentation aufgelistet und erklärt werden. Die Dokumentation kann dabei auf der Webseite zur Verfügung gestellt werden oder separat verfügbar sein. Zu finden ist die Dokumentation z. B. auf Hilfeseiten bzw. in Support-Bereichen, Wikis oder der Erklärung zur Barrierefreiheit.

Die Dokumentation muss dabei z. B. folgende Informationen enthalten, sofern relevant:

* Einzelheiten zu Features für die Barrierefreiheit, sofern sie auf der Webseite integriert sind, zum Beispiel:
** Vorlesefunktion
** Funktionen die Nutzern die Einstellung individueller Farbschemata erlauben 
** Aktivierung verbesserter Darstellungen des Maus- oder Tastaturfokus
** Anpassung von Textabständen
** Besondere Bedienungsarten mit Tastatur / Tastenkombinationen, z.B. spezielle Tastenkombinationen für die Nutzung mit assistiven Technologien
* Hinweise auf unterstützte Umgebungen, falls es Einschränkungen bei der Nutzbarkeit mit assistiven Technologien gibt

Es wird empfohlen, Metadaten für die unterstützten Barrierefreiheitsfunktionen und Kompatibilität gemäß den Konventionen des https://www.w3.org/2021/a11y-discov-vocab/latest/[Schema.org Accessibility Properties for Discoverability Vocabulary] bereitzustellen.

=== 3. Hinweise
. Das Fehlen von zusätzlichen Barrierefreiheits-Funktionen wird nicht negativ bewertet. Wenn sie eingesetzt werden, müssen sie aber dokumentiert sein.
. Es wird nur die Dokumentation von Barrierefreiheits-Funktionen verlangt, die vom Webangebot selbst implementiert werden. Dazu gehören auch Features wie Vorlesefunktionen, die von Drittanbietern definiert und im Angebot eingebunden werden. Barrierefreiheits-Funktionen des Browsers oder des jeweiligen Betriebssystems müssen dagegen nicht dokumentiert werden.
. Zum Punkt Hinweise auf unterstützte Umgebungen: Wenn das Angebot explizit für einen eingeschränkten Nutzerkreis (zum Beispiel ein Firmen-Intranet) entwickelt wurde und für diesen eine bestimmte unterstützte Nutzungsumgebung (beispielsweise ein bestimmter Browser und ein bestimmter Screenreader) festgelegt wurde, soll die Dokumentation die unterstützte Umgebung nennen. Nutzende, die in anderen Umgebungen auf Barrieren stoßen, können dann wengistens ermitteln, woran es liegt, und können ggf. ihre Nutzungsumgebung anpassen. Für Angebote, die allgemein im Web zugänglich sind und mit verschiedensten Browsern und Hilfsmitteln genutzt werden, sind solche Einschränkungen nicht zulässig.

Für die Prüfpraxis sind weitere Hinweise nützlich, auf GitHub können Sie https://github.com/BIK-BITV/BIK-Web-Test/issues[dazu ein Issue eröffnen].

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

12.1.1 Accessibility and compatibility features

== Quellen

[.BLOCK_LANG_EN]
=== 12.1.1 Accessibility and compatibility features

[.BLOCK_LANG_EN]
--
Product documentation provided with the ICT whether provided separately or integrated within the ICT shall list and explain how to use the accessibility and compatibility features of the ICT. 

NOTE 1:
Accessibility and compatibility features include accessibility features that are built-in and accessibility features that provide compatibility with assistive technology. 

NOTE 2:
It is best practice to use WebSchemas/Accessibility 2.0 [i.38] to provide meta data on the accessibility of the ICT.

NOTE 3:
The accessibility statement and help pages are both examples of the provision of product information.
--

(Aus EN 301 549 V3.1.1 Abschnitt 12.1.1 "Accessibility and compatibility
features")
