= Prüfschritt 12.1.2 Barrierefreie Dokumentation
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Die Produkt-Dokumentation eines Web-Angebots enthält Hilfestellungen für die allgemeine Nutzung von Funktionen des Angebots, aber oft auch Hinweise auf zusätzliche Funktionen, welche die Barrierefreiheit für bestimmte Nutzergruppen verbessern. Auch die Erklärung zur Barrierefreiheit ist eine Produkt-Dokumentation.

Wenn ein Web-Angebot eine Produkt-Dokumentation bereitstellt, soll diese mindestens in einer der folgenden Formate barrierefrei zur Verfügung gestellt werden:

* Als Web-Dokument, erfüllt Kriterien der EN 301 549 Kapitel 9
* Als Nicht-Web-Dokument (u. a. PDF), erfüllt Kriterien der EN 301 549 Kapitel 10 

Nicht-Web-Dokumente werden nicht in diesem Prüfverfahren bewertet.

== Warum wird das geprüft?

Die Dokumentation ist ein wichtiger Teil eines Webangebots. So informiert zum Beispiel die "Erklärung zur Barrierefreiheit" Menschen mit Behinderungen über den Stand der Barrierefreiheit des Angebots und nennt (noch) nicht barrierefreie Inhalte sowie gegebenenfalls Wege, benötigte Informationen in anderer Form zu erhalten. Es ist deshalb wichtig, dass diese Erklärung barrierefrei ist. Sie wird deshalb, wenn vorhanden, immer geprüft. Dies gilt auch für weitere Seiten zur Dokumentation des Webangebots, wenn vorhanden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn eine Produkt-Dokumentation angeboten wird. Dazu gehört auch die Erklärung zur Barrierefreiheit.

Die Prüfung der Barrierefreiheit von nicht-web-basierter Dokumentation (etwa von PDFs) kann nicht Teil des Prüfverfahrens sein, sie muss in einem separaten Auftrag erfolgen.

=== 2. Prüfung

Die Prüfung erfolgt als Teil der Seitenauswahl oder nicht als Teil der Seitenauswahl. Für die Vorgehensweise ist zu prüfen, ob die Voraussetzungen (siehe "3. Hinweise") es erlauben, die Dokumentation nicht in die Seitenauswahl aufzunehmen.

==== 2.1 Prüfung der Dokumentation (Teil der Seitenauswahl)
. Prüfen, ob sämtliche anwendbaren Prüfschritte des Verfahrens mit konform bewertet worden sind.
. Ist dies der Fall, ist auch dieser Prüfschritt konform.

==== 2.2 Prüfung der Dokumentation (nicht Teil der Seitenauswahl)
. Ist die Dokumentation nicht Teil der Seitenauswahl (siehe Erläuterungen unter "3. Hinweise"), prüfen, ob für die seitenübergreifenden Bereiche (z.B. Kopf- und   Fußbereich) sämtliche anwendbaren Prüfschritte des Verfahrens mit konform bewertet wurden.
. Für den Inhaltsbereich der Seite prüfen, ob sämtliche anwendbaren Prüfschritte des Verfahrens mit konform bewertet wurden (in der Regel handelt es sich bei sehr einfachen Seiten um die Prüfung der Struktur und gegebenenfalls die Tastaturbedienbarkeit).

=== 3. Hinweise
* Die Dokumentation muss nicht zwingend Teil der Seitenauswahl sein, wenn Folgendes gegeben ist:
- Der Seitentyp ist bereits in der Seitenauswahl abgedeckt.
- Seitenübergreifende Bereiche (Kopf- und Fußbereich) sind mit den anderen Seiten der Seitenauswahl identisch und bereits geprüft worden.
- Der Inhaltsbereich ist sehr einfach (es handelt sich beispielsweise nur um strukturierter Text und Links).
* Ist die Dokumentation komplexer oder als weiterer Seitentyp einzustufen, wird sie als eine weitere Seite in die Seitenauswahl aufgenommen. Wenn eine weitere web-basierte Dokumentation zum Web-Angebot vorhanden ist, soll auch diese in die Seitenauswahl bzw. Prüfung einbezogen werden.
* Der Prüfschritt schließt nicht die Möglichkeit aus, alternative Formate anzubieten, die die Bedürfnisse einer bestimmten Nutzergruppe erfüllen (z. B. Braille-Dokumente für blinde Menschen oder Informationen in leichter Sprache  für Personen mit eingeschränkter Kognition, Sprache und Lernfähigkeit).

Für weitere Hinweise zu diesem Prüfschritt können Sie auf GitHub https://github.com/BIK-BITV/BIK-Web-Test/issues[ein Issue eröffnen].

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

12.1.2 Accessible documentation

== Quellen

[.BLOCK_LANG_EN]
=== 12.1.2 Accessible documentation

[.BLOCK_LANG_EN]
--
Product documentation provided with the ICT shall be made available in at least one of the following electronic formats:

* a Web format that conforms to the requirements of clause 9; or 
* a non-web format that conforms to the requirements of clause 10. 

NOTE 1:
This does not preclude the possibility of also providing the product documentation in other formats (electronic, printed or audio) that are not accessible. 

NOTE 2:
It also does not preclude the possibility of providing alternate formats that meet the needs of some specific type of users (e.g. Braille documents for blind people or easy-to-read information for persons with limited cognitive, language and learning abilities). 

NOTE 3:
Where documentation is incorporated into the ICT, the documentation falls under the requirements for accessibility in the present document. 

NOTE 4:
A user agent that supports automatic media conversion would be beneficial to enhancing accessibility.
--

(Aus EN 301 549 V3.1.1 Abschnitt 12.1.2 "Accessible documentation")
