= Prüfschritt 12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Die Dokumentation der Webseite / Web-App soll die Eigenschaften und Funktionen
in Bezug auf Barrierefreiheit auflisten undessen Nutzung erklären.
Dazu zählen auch Informationen zur Kompatibilität mit assistiven Technologien.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Dieser Prüfschritt ist anwendbar, wenn der Teil der Dokumentation, der sich
mit Barrierefreiheit und Kompatibilität beschäftigt, auf der Webseite, auf
HTML-Basis, integriert
ist.
Dokumentation, die ausschließlich außerhalb der Webseite bereitgestellt wird
und / oder in anderen Formaten vorliegt, kann nicht im Rahmen dieses
Prüfverfahrens mitgetestet werden.
Die entsprechende Dokumentation muss dann in einem separaten Auftrag geprüft
werden.

=== 2. Prüfung

Alle für die Barrierefreiheit relevanten Informationen zur Webseite sollen
in der Dokumentation aufgelistet und erklärt werden.
Die Dokumentation kann dabei auf der Webseite zur Verfügung gestellt werden
oder separat verfügbar sein.
Zu finden ist die Dokumentation z. B. auf Hilfeseiten bzw. in Support-Bereichen,
Wikis oder der Erklärung zur Barrierefreiheit.

Die Dokumentation muss dabei z. B. folgende Informationen enthalten, sofern
relevant:

* Barrierefreiheitserklärung nach EU-Richtlinie 2016/2102 (ggf. verlinkt)
* Einzelheiten zu Features für die Barrierefreiheit (auf der Webseite 
  integriert)
** Vorlesefunktion
** Kontrastumschalter / Schalter für Farbschemata / Aktivierung verbesserter
   Maus-/Tastaturfokus
** Vergrößerungsfunktion
** Anpassung von Textabständen
** Deaktivierung von Bewegungen oder automatischen Audios
** besondere Bedienungsarten mit Tastatur / Tastenkombinationen
** ...
* Informationen zur Kompatibilität mit assistiven Technologien
* spezielle Tastenkombinationen für die Nutzung mit assistiven Technologien
* Verzeichnisse für Abkürzungen

Die Webseite soll, wenn möglich, Metadaten für die unterstützten
Barrierefreiheitsfunktionen und Kompatibilität maschienenlesbar, in geeigneten
Formaten, bereitstellen.

=== 3. Hinwiese

Für die Prüfpraxis sind weitere Hinweise nützlich, auf GitHub können Sie
https://github.com/BIK-BITV/BIK-Web-Test/issues[dazu ein Issue eröffnen].

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

12.1.1 Accessibility and compatibility features

== Quellen

[.BLOCK_LANG_EN]
=== 12.1.1 Accessibility and compatibility features

[.BLOCK_LANG_EN]
--
Product documentation provided with the ICT whether provided separately or
integrated within the ICT shall list and explain how to use the accessibility
and compatibility features of the ICT. 

NOTE 1:
Accessibility and compatibility features include accessibility features that
are built-in and accessibility features that provide compatibility with
assistive technology. 

NOTE 2:
It is best practice to use Web.
Schemas/Accessibility 2.0 [i.38] to provide meta
data on the accessibility of the ICT.

NOTE 3:
The accessibility statement and help pages are both examples of the provision
of product information.
--

(Aus EN 301 549 V3.1.1 Abschnitt 12.1.1 "Accessibility and compatibility
features")
