= Prüfschritt 12.2.2 Technischer Support
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Der technische Support (über Telefon, Mail, ...) soll Informationen zur
Barrierefreiheit und Kompatibilität zu assistiven Technologien bereitstellen
können, die die Webanwendung betreffen.
Dies soll mindestens die Informationen umfassen, die dazu in der
Dokumentation der Webanwendung erwähnt werden (siehe auch Prüfschritt
ifdef::env_embedded[12.1.1 "Dokumentation von Kompatibilität und Barrierefreiheit"]
ifndef::env_embedded[]
  <<12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit.adoc#,
  12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit>>
endif::env_embedded[]
).

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

=== 2. Prüfung

Zielführend könnte es bspw. sein, anhand der Informationen aus der
Dokumentation der Webanwendung, den technischen Support zu kontaktieren und einige
Fragen zur Barrierefreiheit stichprobenartig zu stellen.

Falls möglich, können auch die Dokumente, die dem technischem Support zur
Verfügung stehen, stichprobenartig geprüft werden.

Verbreitet sollten jedoch Assistenzsysteme sein, die den Support-Mitarbeiter
durch die Problemlösung führt.
Es ist sehr fraglich, ob ein Prüfer zu diesen Systemen Zugang für eine Prüfung
bekommen würde.

=== 3. Hinweise

Wie dieser Prüfschritt in der Praxis getestet werden kann, ist noch nicht
vollständig geklärt.
Hinweise dazu können Sie in einem GitHub https://github.com/BIK-BITV/BIK-Web-Test/issues[Issue hinterlassen].

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

12.2.2 Information on accessibility and compatibility features


== Quellen

[.BLOCK_LANG_EN]
=== 12.2.2 Information on accessibility and compatibility features

[.BLOCK_LANG_EN]
--
ICT support services shall provide information on the accessibility and
compatibility features that are mentioned in the product documentation. 

NOTE:
Accessibility and compatibility features include accessibility features that
are built-in and accessibility features that provide compatibility with
assistive technology.
--

(Aus EN 301 549 V3.1.1 Abschnitt 12.2.2 "Information on accessibility and
compatibility features")
