= Prüfschritt 12.2.4 Vom Support bereitgestellte Dokumentation
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wird durch den technischen Support eines Angebots eine Dokumentation bereitgestellt, wird diese in mindestens einem der folgenden Formate barrierefrei angeboten:

* Als Web-Dokument, das die Kriterien der EN 301 549 Kapitel 9 erfüllt
* Als Nicht-Web-Dokument (z. B. ein PDF oder eine Word-Datei), dass die
  Kriterien der EN 301 549 Kapitel 10 erfüllt

Weitere gegebenenfalls nicht barrierefreie Versionen der Dokumentation werden nicht bewertet.

== Warum wird das geprüft?

Die technische Dokumentation ist ein wichtiger Bestandteil vieler Angebote, besonders bei komplexeren Web-Anwendungen. Damit auch Menschen mit Behinderungen sie gut nutzen können, sollte sie alle Anforderungen der Barrierefreiheit erfüllen.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn Support Services eine technische Dokumentation zur Nutzung des Angebots bereitstellen, etwa HTML-basierte Hilfe-Systeme, PDF-Handbücher, oder Anleitungen. Im BIK BITV-Test können lediglich Dokumente auf Basis von Web-Technologien getestet werden.

Falls von Support Services eine webbasierte Dokumentation bereitgestellt wird, sollte dies vorab mit dem Anbieter geklärt werden, damit diese Dokumentation bereits bei der Seitenauswahl berücksichtigt werden kann. Für andere Formate (etwa PDF) muss gegenenenfalls ein getrennter Prüfauftrag erteilt werden, da sich diese Formate im BITV-Test nicht prüfen lassen.

=== 2. Prüfung

Gibt es eine Support-Dienstleistung, die eine technische Dokumentation zur Nutzung bzw. zum Verständnis der Funktionen eines Angebots bereitstellt?

Beispiele wären:

* Ein Datenbank-Anbieter schickt auf Anfrage den Link zu einer HTML-Anwendung mit einer Erklärung der angebotenen Such- und Filter-Funktionen.
* Ein Dokumenten-Management-System schickt auf Anfrage eine HTML-Referenzseite zu unterstützten Tastaturbefehlen.
* Der Anbieter eines web-basierten Drucker-Management-Systems schickt auf Anfrage ein PDF-Handbuch mit einer vollständige Liste der verfügbaren Touch-Displays eines Druckers mit Dokumentation aller angebotenen Funktionen (dieses Handbuch wäre nicht im Test zu prüfen, der Auftraggeber wird darauf hingewiesen, hier ggf. einen Zusatzauftrag für eine PDF-Prüfung zu erteilen).

Wenn eine zusätzliche technische Dokumentation im HTML-Format bereitgestellt wird, wird diese in der Seitenauswahl des Tests berücksichtigt und mitgetestet.

=== 3. Hinweise

Dokumentation bezieht sich in diesem Prüfschritt auf alle Dokumente, die dem Nutzer auf Anfrage *durch den Support* zur Verfügung gestellt werden.

Der Prüfschritt schließt nicht die Möglichkeit aus, alternative Formate anzubieten, die die Bedürfnisse einer bestimmten Nutzergruppe erfüllen (z. B. Braille-Dokumente für blinde Menschen oder Informationen in leichter Sprache für Personen mit eingeschränkter Kognition, Sprache und Lernfähigkeit).

Wie dieser Prüfschritt in der Praxis berücksichtigt werden kann, ist noch nicht vollständig geklärt. Für Hinweise zu diesem Prüfschritt können Sie auf GitHub
https://github.com/BIK-BITV/BIK-Web-Test/issues[ein Issue eröffnen].

=== 4. Bewertung

==== Erfüllt

Die webbasierte Dokumentation erfüllt alle Anforderungen aus Kapitel 9 (Web) der EN.

==== Nicht erfüllt

Die webbasierte Dokumentation erfüllt eine oder mehrere Anforderungen aus Kapitel 9 (Web) nicht.

== Quellen
* Zurzeit keine Quellen.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.2.1

[.BLOCK_LANG_EN]
==== 12.2.4 Accessible documentation
____
[.BLOCK_LANG_EN]
--
Documentation provided by support services shall be made available in at least
one of the following electronic formats: 
* a Web format that conforms to clause 9; or
* a non-web format that conforms to clause 10.

NOTE 1:
This does not preclude the possibility of also providing the documentation in
other formats (electronic or printed) that are not accessible. 

NOTE 2:
It also does not preclude the possibility of providing alternate formats that
meet the needs of some specific type of users (e.g. Braille documents for
blind people or easy-to-read information for persons with limited cognitive,
language and learning abilities). 

NOTE 3:
Where the support documentation is incorporated into the ICT, the documentation
falls under the requirements for accessibility in the present document. 

NOTE 4:
A user agent that supports automatic media conversion would be beneficial to
enhancing accessibility.
--
____
