= Prüfschritt 12.2.3 Effektive Kommunikation
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Der (technische) Support soll die Kommunikationsbedürfnisse von Menschen mit
Behinderungen berücksichtigen und effektive d. h. funktionierende und
tragfähige Kommunikationskanäle anbieten.
Dies kann auch durch die Vermittlung von Dritten ermöglicht werden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

=== 2. Prüfung

Um diesen Prüfschritt zu erfüllen, ist es sicherlich notwendig, verschiedene
Kommunikationsarten für die Nutzer anzubieten.

.Kommunikation über
* E-Mail
* Chat
* Telefon
* Videotelefonie

=== 3. Hinweise

Wie dieser Prüfschritt in der Praxis berücksichtigt werden kann, ist noch
nicht vollständig geklärt.
Auf GitHub können Sie https://github.com/BIK-BITV/BIK-Web-Test/issues[Hinweise zu diesem Prüfschritt
hinterlassen].

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

12.2.3 Effective communication

== Quellen

[.BLOCK_LANG_EN]
=== 12.2.3 Effective communication

[.BLOCK_LANG_EN]
ICT support services shall accommodate the communication needs of individuals
with disabilities either directly or through a referral point. 

(Aus EN 301 549 V3.1.1 Abschnitt 12.2.3 "Effective communication")
