= Prüfschritt 5.2 Aktivierung von Barrierefreiheitsfunktionen
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Grundlage des Prüfschritts ist die Tabelle A.1 im Annex A der EN 301 549
V3.1.1.
In dieser Tabelle wird auf Abschnitt
5.2 "Activation of accessibility features" verwiesen.

== Warum wird das geprüft?

Barrierefreiheitsfunktionen, die von der zu testenden Webseite bereitgestellt
werden, d. h. *nicht* vom Betriebssystem oder dem Browser bereitgestellt
werden, sollen von ihrer potentiellen Nutzerschaft selbstständig aktivierbar
sein.

Wenn die Webseite beispielsweise eine Funktion zur Verfügung stellt, mit
derer die Kontrastverhältnisse innerhalb der Seite verbessert werden, müssen
sämtliche Bedienelemente, die zur Aktivierung der Funktion bedient werden
müssen, auch in der Standardansicht ein ausreichendes Kontrastverhältnis
aufweisen.
Damit wird sichergestellt, dass auch Nutzer, die mit kontrastarmen Inhalten
und Bedienelementen Schwierigkeiten haben
(also zur Zielgruppe der Barrierefreiheitsfunktion gehören), die Funktion zur
Kontrasterhöhung selbstständig aktivieren können.

== Was wird geprüft?

Wenn die Webseite Funktionen für die Barrierefreiheit bereithält, die
spezielle Bedürfnisse von Nutzern erfüllt, soll die Aktivierung dieser
Funktionen für diese Nutzergruppe barrierefrei möglich sein.
Das bedeutet, dass die Barrierefreiheitsfunktion für die Nutzergruppe, die
sie unterstützen soll, selbstständig aktivierbar sein soll.

Beispiele für Barrierefreiheitsfunktionen:

* Vorlesefunktion
* Kontrasterhöhung, Farbschemata
* Schriftgröße, Schriftformatierungen (z. B. Zeilenabstand, Schriftart usw.)
* Leichte Sprache
* Deutsche Gebärdensprache
* Animationen / automatische Audios pausieren

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die zu prüfende Webseite Funktionen für die
Barrierefreiheit bereithält.
Dieser Prüfschritt ist explizit nicht auf systemseitige Bedienungshilfen
anzuwenden (z. B. vom Browser oder Betriebssystem).

=== Prüfung

. Webseite öffnen
. prüfen, ob Barrierefreiheitsfunktionen auf den zu testenden Seiten
  angeboten werden
. Falls es sich um eine komplexere Web-Anwendung handelt, Einstellungen der
  Web-App aufrufen und auch dort nach entsprechenden Funktionen suchen
. falls Barrierefreiheitsfunktionen angeboten werden:
+
  * Ist die Funktion für die Zielgruppe deutlich identifizierbar? Siehe
    <<Hinweis zur Identifizierbarkeit>>.
  * Ist die Funktion für die Zielgruppe selbstständig aktivierbar?

==== Hinweis zur Identifizierbarkeit

Die Barrierefreiheitsfunktionen müssen insbesondere für deren Zielgruppen
identifizierbar sein.
Dazu erfüllen die Barrierefreiheitsfunktionen bzw. die zugehörigen
Bedienelemente alle auf sie anwendbaren Prüfschritte, z. B.:

* Alternativtexte
* Tastaturbedienbarkeit, sichtbarer Fokus
* Kontrast
* Vergrößerung
* Name, Rolle, Wert

== Quellen

[.BLOCK_LANG_EN]
=== 5.2 Activation of accessibility features

[.BLOCK_LANG_EN]
Where ICT has documented accessibility features, it shall be possible to
activate those documented accessibility 
features that are required to meet a specific need without relying on a method
that does not support that need.

(Aus EN 301 549 V3.1.1 Abschnitt 5.2)
