= Prüfschritt 5.3 Biometrie
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn die Webseite biometrische Merkmale für die Nutzeridentifizierung oder die Steuerung nutzt, soll diese sich nicht nur auf ein biometrisches Merkmal beschränken.

Die Alternativen zu einer biometrischen Identifizierungsmethode werden in der Regel nicht-biometrische Methoden für die Nutzeridentifizierung sein, etwa die Eingabe von Nutzername und Passwort oder von einer Pin. Auch eine zweite biometrische Methode kann diesen Prüfschritt erfüllen, z.B. zusätzlich zu Fingerabdruck-Erkennung die Erkennung des Irismusters, des Sprachmusters, oder des Gesichts.

== Warum wird das geprüft?

Die Biometrische Authentifizierung kann gerade für Menschen mit Behinderung sinnvoll sein und den Zugang zu geschützten Systemen erleichtern. So ist für viele die Berührung eines Sensors mit dem Finger meist schneller und einfacher als die Eingabe einer Pin oder eines Passworts. Es muss aber für menschen, welche z.B. aufgrung von behinderungen die angebotene Methode der biometrischen Authentifizierung nicht nutzen können, eine nutzbare Alternative geben. 

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Webseite biometrische Merkmale für
die Nutzeridentifizierung oder Steuerung nutzt.

=== 2. Prüfung

. Webseite öffnen
. prüfen, ob die Webseite eine Identifizierung über biometrische Merkmale
  benötigt, falls ja, prüfen ob biometrische oder nicht biometrische
  Alternativen zur Identifizierung angeboten werden
. Bedienkonzept der wesentlichen Funktionen auf den zu testenden Webseiten
  untersuchen:
+
  * Wird Biometrie für die Steuerung genutzt?
  * Werden zur biometrischen Steuerung zusätzlich alternative biometrische
    oder nicht biometrische Steuerungsmethoden angeboten?

== Einordnung des Prüfschritts 

EN 301 549, 5.3 "Biometrics"

== Quellen

[.BLOCK_LANG_EN]
=== 5.3 Biometrics

[.BLOCK_LANG_EN]
--
Where ICT uses biological characteristics, it shall not rely on the use of a
particular biological characteristic as the only means of user identification
or for control of ICT. 

NOTE 1:
Alternative means of user identification or for control of ICT could be
non-biometric or biometric. 

NOTE 2:
Biometric methods based on dissimilar biological characteristics increase the
likelihood that individuals with disabilities possess at least one of the
specified biological characteristics.
Examples of dissimilar biological characteristics are fingerprints, eye
retinal patterns, voice, and face.
--

(Aus EN 301 549 V3.1.1 Abschnitt 5.3 "Biometrics")
