= Prüfschritt 5.3 Biometrie
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Grundlage des Prüfschritts ist die Tabelle A.1 im Annex A der EN 301 549
V3.1.1.
In dieser Tabelle wird auf Abschnitt
5.3 "Biometrics" verwiesen.

== Warum wird das geprüft?

Wenn biometrische Merkmale zur Nutzeridentifizierung und/oder zur Bedienung der
Webseite eingesetzt werden, müssen dazu Alternativmethoden angeboten werden,
Nutzeridentifizierung und Bedienung der Seite darf sich *nicht* auf ein
biometrisches Merkmal allein verlassen.

Der Prüfschritt stellt sicher, dass Nutzer, die nicht über ein bestimmtes
biometrisches Merkmal verfügen
(z. B. keine Hände und damit auch kein Fingerabdruck) dennoch in der Lage sind
sich zu authentifizieren bzw. die Webseite zu bedienen.

== Was wird geprüft?

Wenn die Webseite biometrische Merkmale für die Nutzeridentifizierung oder
die Steuerung nutzt, soll diese sich nicht nur auf ein biometrisches Merkmal
beschränken.

Statt sich z. B. auf den Fingerabdruck zu beschränken, könnte eine
Webseite auch zusätzlich Alternativen wie Irismuster, Gesichtserkennung oder
Sprachmuster für die Nutzeridentifizierung anbieten.

Alternativen zu einer biometrischen Identifizierungsmetode oder -Steuerung
können auch nicht biometrische Methoden sein:

.Nutzeridentifizierung
* klassisch über Benutzername und Passwort
* PIN
* Identifizierung per TAN

.Steuerung
* Bedienung per Tastatur
* Bedienung per Maus
* Bedienung per Touch-Gesten

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Webseite biometrische Merkmale für
die Nutzeridentifizierung oder Steuerung nutzt.

=== Prüfung

. Webseite öffnen
. prüfen, ob die Webseite eine Identifizierung über biometrische Merkmale
  benötigt, falls ja, prüfen ob biometrische oder nicht biometrische
  Alternativen zur Identifizierung angeboten werden
. Bedienkonzept der wesentlichen Funktionen auf den zu testenden Webseiten
  untersuchen:
+
  * Wird Biometrie für die Steuerung genutzt?
  * Werden zur biometrischen Steuerung zusätzlich alternative biometrische
    oder nicht biometrische Steuerungsmethoden angeboten?

== Quellen

[.BLOCK_LANG_EN]
=== 5.3 Biometrics

[.BLOCK_LANG_EN]
--
Where ICT uses biological characteristics, it shall not rely on the use of a
particular biological characteristic as the only means of user identification
or for control of ICT. 

NOTE 1:
Alternative means of user identification or for control of ICT could be
non-biometric or biometric. 

NOTE 2:
Biometric methods based on dissimilar biological characteristics increase the
likelihood that individuals with disabilities possess at least one of the
specified biological characteristics.
Examples of dissimilar biological characteristics are fingerprints, eye
retinal patterns, voice, and face.
--

(Aus EN 301 549 V3.1.1 Abschnitt 5.3 "Biometrics")
