= Prüfschritt 5.4 Erhaltung von Barrierefreiheitsinformationen bei Konvertierung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

== Was wird geprüft?

Wenn die Webseite Dokumente in andere Formate konvertiert, sollen vorhandene 
Barrirefreiheitsinformationen im Zielformat übernommen werden, wenn das
Zielformat diese Informationen grundsätzlich unterstützt.

Zum Beispiel könnte eine Web-App HTML-Dateien in PDF konvertieren.
Nach der Konvertierung soll die PDF-Datei sämtliche Überschriftsebenen,
Alternativtexte und Tabelleninformationen enthalten, die auch in der
HTML-Quelle vorhanden sind.

Proprietäre Erweiterungen müssen nicht berücksichtigt werden.
Dies könnten spezielle Dateiformatserweiterungen von einzelnen Herstellern
sein, die nur von einer begrenzten Anzahl an User-Agents / Anzeigeprogrammen
unterstützt werden und dabei nicht offen standardisiert sind.

=== Warum wird das geprüft?

Nutzer, die die Barrierefreiheitsinformationen (Überschriftenauszeichnung, Alternativtexte, 
Untertitel usw.) benötigen, sollen diese auch im Zielformat nutzen können, 
sofern die Zielformate die Information grundsätzlich unterstützen.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Webseite Dokumente konvertiert.
Dokumente umfasst dabei alle digitalen Formate wie Text, Audio und Video.

=== 2. Prüfung

Die Prüfung ist sehr individuell und richtet sich nach den verwendeten Quell-
und Zielformaten.

. Beispieldokumente mit Barrierefreiheits-Information in Zielformate konvertieren. 
. Sind vom Format grundsätzlich unterstützte Barrierefreiheitsinformationen nach der Konvertierung im Zielformat
erhalten geblieben? 

=== 3. Hinweise

Informationen, die das Zielformat nicht unterstützt, sollen bei der Prüfung nicht berücksichtigt werden.

=== 4. Bewertung

==== Erfüllt:

Das Zielformat enthält alle Barrierefreiheitsinformationen des Ausgangsformats, die grundsätzlich unterstützt werden.

==== Nicht voll erfüllt:

Grundsättlich vom Zielformat unterstützte Barrierefreiheitsinformationen des Ausgangsformats gehen bei der Konvertierung verloren.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

* 5.4 "Preservation of accessibility information during conversion"

== Quellen

[.BLOCK_LANG_EN]
=== 5.4 Preservation of accessibility information during conversion

[.BLOCK_LANG_EN]
Where ICT converts information or communication it shall preserve all
documented non-proprietary information that is provided for accessibility, to
the extent that such information can be contained in or supported by the
destination format.

(Aus EN 301 549 V3.1.1 Abschnitt 5.4 "Preservation of accessibility
information")
