= Prüfschritt 5.4 Erhaltung von Barrierefreiheits-Informationen bei Konvertierung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn die Webseite Dokumente in andere Formate konvertiert, sollen vorhandene Barrierefreiheits-Informationen im Zielformat übernommen werden, wenn das Zielformat diese Informationen grundsätzlich unterstützt.

== Warum wird das geprüft?

Wenn die Webseite Konvertierungsfunktionen anbietet, sollen Barrierefreiheitsinformationen im Ausgangsformat nicht unnötigerweise im Zielformat verloren gehen. Unnötig ist der Verlust von Barrierefreiheitsinformationen dann, wenn das Zielformat prinzipiell die Aufnahme der Barrierefreiheitsinformation
unterstützt, durch die Konvertierungsfunktion jedoch nicht genutzt wird. Beispielsweise unterstützen HTML- und PDF-Dateien die Auszeichnung von Überschriften, eine Konvertierungsfunktion könnte daher problemlos die Überschriftenauszeichnung aus dem HTML-Quelltext für PDF adaptieren.

Hinzunehmen ist der Verlust von Barrierefreiheitsinformationen nur dann, wenn das Zielformat keine Unterstützung für die im Ausgangsformat genutzte Informationsart anbietet.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist grundsätzlich anwendbar, wenn die Webseite digitale Formate wie Text, Audio und Video konvertiert. Der Prüfschritt ist jedoch im BIK Web-Test nur anwendbar, wenn sowohl Start- als auch Zielformat HTML ist. Sind entweder das Ausgangs- oder das Zielformat der Konvertierung nicht HTML, kann der Prüfschritt nicht in diesem Verfahren allein geprüft werden, denn hier müsste zusätzlich eine Prüfung des abweichenden Formats durchgeführt werden.

=== 2. Prüfung

Die Prüfung ist sehr individuell und richtet sich nach den verwendeten Quell- und Zielformaten.

. Gegebenenfalls Beispieldokumente mit Barrierefreiheits-Informationen in ein HTML-Zielformat konvertieren. 
. Sind vom Format grundsätzlich unterstützte Barrierefreiheits-Informationen nach der Konvertierung im Zielformat erhalten geblieben? 

=== 3. Hinweise

Bei Konvertierung in ein Nicht-HTML-Format sollte in die Anmerkungen aufgenommen werden, dass die Barrierefreiheits-Informationen (z.B. semantische Überschriften, Links oder Untertitel) im Zielformat erhalten bleiben sollen.

=== 4. Bewertung

==== Erfüllt

Das HTML-Zielformat enthält alle Barrierefreiheits-Informationen des HTML-Ausgangsformats, die grundsätzlich unterstützt werden.

==== Nicht voll erfüllt

Grundsätzlich vom HTML-Zielformat unterstützte Barrierefreiheits-Informationen des HTML-Ausgangsformats gehen bei der Konvertierung verloren.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

5.4 Preservation of accessibility information during conversion

== Quellen

[.BLOCK_LANG_EN]
=== 5.4 Preservation of accessibility information during conversion

[.BLOCK_LANG_EN]
Where ICT converts information or communication it shall preserve all
documented non-proprietary information that is provided for accessibility, to
the extent that such information can be contained in or supported by the
destination format.

(Aus EN 301 549 V3.1.1 Abschnitt 5.4 "Preservation of accessibility
information")
