= Prüfschritt 6.2.2.3 Sprecheridentifizierung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Grundlage des Prüfschritts ist die Tabelle A.1 im Annex A der EN 301 549
V3.1.1.
In dieser Tabelle wird auf Abschnitt
6.2.2 "Display of RTT" verwiesen.

== Was wird geprüft?

Wenn die Web-App Echtzeit Textkommunikation unterstützt und den
aktiven Sprecher über Sprache identifiziert, sollen auch Sprecher, die
Echtzeit-Texteingaben nutzen, gleichermaßen identifizierbar sein.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Web-App Echtzeit Textkommunikation
unterstützt und den aktiven Sprecher über Sprache identifiziert.
Der aktive Sprecher wird dabei in der Web-App markiert oder anderweitig
hervorgehoben.

=== Prüfung

. Web-App öffnen
. Prüfen, ob der aktive Sprecher über Sprache identifiziert und in der App
  markiert oder anderweitig hervorgehoben wird
. Ist dies der Fall, prüfen, ob auch Teilnehmer, die Echtzeit-Texteingabe verwenden, beim Eingaben markiert oder anderweitig hervorgehoben werden

==== Hinweise

Bei diesem Test muss eine Video- und Sprachverbindung mit mehreren Teilnehmern
etabliert werden, um eine eventuelle Markierung oder anderweitige Hervorhebung
zweifelsfrei festzustellen.

== Quellen

[.BLOCK_LANG_EN]
=== 6.2.2.3 Speaker identification

[.BLOCK_LANG_EN]
--
Where ICT has RTT capabilities, and provides speaker identification for voice,
the ICT shall provide speaker identification for RTT.

NOTE:
This is necessary to enable both voice and RTT participants to know who is
currently communicating, whether it be in RTT or voice.
--

(Aus EN 301 549 V3.1.1 Abschnitt 6.2.2.3 "Speaker identification")
