= Prüfschritt 6.2.2.1 Visuell unterscheidbare Anzeige von Textnachrichten
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn das Webangebot Echtzeit Textkommunikation senden und empfangen kann, soll die Anzeige von empfangenen und gesendeten Nachrichten visuell unterscheidbar sein und somit voneinander separiert werden.

== Warum wird das geprüft?

Menschen, die Echtzeit-Textkommunikastion nutzen, sollen in der Lage sein, empfangene und gesendete Nachrichten visuell zu unterscheiden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Webangebot Echtzeit Textkommunikation senden und empfangen kann.

=== 2. Prüfung

. Webangebot öffnen
. Prüfen, ob die Webangebot das Senden und Empfangen von Echtzeit Textkommunikation anbietet
. Prüfen, ob die gesendeten und empfangenen Textnachrichten deutlich voneinander unterscheidbar sind und separat angezeigt werden, z. B.:
+
* Rahmen für Textnachricht (mit gutem Kontrast nach außen)
* Positionierung der eigenen Nachrichten rechtsbündig und der Gesprächsteilnehmer linksbündig oder umgekehrt
* Nennung des Namens vor Beginn der Nachricht
* Nur als Zusatz: Unterscheidung der Nachrichten von verschiedenen Personen durch unterschiedliche Farbgebung (mit gutem Kontrast)

=== 3. Hinweise

Wenn die Webangebot verschiedene Optionen für die Anzeige der Nachrichte anbietet, die gegebenenfalls nicht diesen Anforderungen entsprechen, soll dies nicht schlecht bewertet werden.

Andere Optionen für die Anzeige sind positiv, sie können andere Bedürfnisse der Nutzer erfüllen. Beispielsweise kann die Inline-Darstellung von empfangenen und gesendeten Nachrichten für Braille-Nutzer vorteilhaft sein.

=== 4. Einordnung des Prüfschritss

==== Einordnung des Prüschritts nach der EN 301 549 V3.1.1., Annex A

Tabelle A2 verweist auf Abschnitt 6.2.2 "Display of RTT".

== Quellen

[.BLOCK_LANG_EN]
=== 6.2.2.1 Visually distinguishable display

[.BLOCK_LANG_EN]
--
Where ICT has RTT send and receive capabilities, displayed sent text shall be
visually differentiated from, and separated from, received text. 

NOTE:
The ability of the user to choose between having the send and receive text be
displayed in-line or separately, and with options to select, allows users to
display RTT in a form that works best for them.
This would allow Braille users to use a single field and take turns and have
text appear in the sequential way that they may need or prefer.
--

(Aus EN 301 549 V3.1.1 Abschnitt 6.2.2.1 "Visually distinguishable display")
