= Prüfschritt 6.2.2.2 Programmatische Ermittelbarkeit bei Textnachrichten
include::include/author.adoc[]
include::include/attributes.adoc[]


== Was wird geprüft?

Wenn das Webangebot eine Funktion zur Echtzeit-Textkommunikation anbietet, sind gesendeter und empfangener Text programmatisch unterscheidbar. Dies ermöglicht Hilfsmitteltechnologien wie Screenreadern die Ansage der jeweiligen Sende- oder Empfangsrichtung (zum Beispiel durch Ausgabe der Verfasser:innen).

== Warum wird das geprüft?
Echtzeit-Textkommunikation (real time text, RTT), ermöglicht es, eine Nachricht zeichenweise schon während der Eingabe zu übermitteln. Lesende können also von anderen eingegebene Buchstaben in dem Moment sehen, in dem der Sender ihn schreibt. Die Nutzenden müssen nicht (wie etwa in einem Chat), eine Nachricht zuerst schreiben und anschließend abschicken. Die Kommunikation ist damit ebenso (annähernd) synchron wie bei der Telefonie. 

Die Echtzeit-Textkommunikation ist für Menschen mit einer Hör- oder Spracheinschränkung eine Alternative zum mündlichen Dialog. Menschen, die Echtzeit-Textkommunikation mit einem Hilfsmittel wie etwa einem Screenreader nutzen, sollen in der Lage sein, empfangene und gesendete Nachrichten programmatisch zu unterscheiden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn das Webangebot Echtzeit-Textkommunikation senden und empfangen kann.

=== 2. Prüfung

Das Webangebot mit der Echtzeit-Textkommunikation sollte zusätzlich zur Quelltext-Analyse mit dem Screenreader geprüft werden, um zu beurteilen, ob die notwendigen Informationen korrekt an den Screenreader ausgegeben werden, so dass die Sende-Richtung der einzelnen Textnachrichten verständlich ausgegeben wird.

==== 2.1 Prüfung im Quelltext

. Webangebot öffnen
. Prüfen, ob gesendete und empfangene Textnachrichten semantisch voneinander unterscheidbar sind. Dazu kann z. B. im HTML-Quelltext Verfasser:innen mit Uhrzeit genannt werden. 

==== 2.2 Zusätzliche Prüfung mittels Screenreader

. Screenreader starten
. das zu prüfende Web-Angebot mit der Ansicht für die Echtzeit-Textkommunikation aufrufen
. einige Testnachrichten senden und empfangen (ggf. zweites Gerät notwendig)
. die Textnachrichten antippen bzw. mit dem Screenreader zu diesen navigieren
. auf die Ausgabe des Screenreaders achten, die Sende- und Empfangsrichtung muss durch die Ausgabe deutlich und unmissverständlich hervorgehen, etwa durch Ansage der Kürzel der Verfasser:innen.

== 3. Hinweise

== 4. Bewertung

== Einordnung des Prüfschritts

* 6.6.2.2 Programmatically determinable send and receive direction

=== Abgrenzung zu anderen Prüfschritten
== Quellen

[.BLOCK_LANG_EN]
=== 6.2.2.2 Programmatically determinable send and receive direction

[.BLOCK_LANG_EN]
--
Where ICT has RTT send and receive capabilities, the send/receive direction of
transmitted/received text shall be programmatically determinable, unless the
RTT is implemented as closed functionality. 

NOTE:
This enables screen readers to distinguish between incoming text and outgoing
text when used with RTT functionality.
--

(Aus EN 301 549 V3.1.1 Abschnitt 6.2.2.2 "Programmatically determinable send
and receive direction")
