= Prüfschritt 6.2.2.1 Visuell unterscheidbare Anzeige von Textnachrichten
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn das Webangebot Echtzeit Textkommunikation senden und empfangen kann, soll die Anzeige von empfangenen und gesendeten Nachrichten visuell unterscheidbar sein und somit voneinander separiert werden.

== Warum wird das geprüft?

Menschen, die Echtzeit-Textkommunikastion nutzen, sollen in der Lage sein, empfangene und gesendete Nachrichten visuell zu unterscheiden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Webangebot Echtzeit Textkommunikation senden und empfangen kann.

=== 2. Prüfung

. Webangebot öffnen
. Prüfen, ob die Webangebot das Senden und Empfangen von Echtzeit Textkommunikation anbietet
. Prüfen, ob die gesendeten und empfangenen Textnachrichten deutlich voneinander unterscheidbar sind und separat angezeigt werden, z. B.:
+
* Rahmen für Textnachricht (mit gutem Kontrast nach außen)
* Positionierung der eigenen Nachrichten rechtsbündig und der Gesprächsteilnehmer linksbündig oder umgekehrt
* Nennung des Namens vor Beginn der Nachricht

=== 3. Hinweise

* Wenn die Webangebot weitere Optionen für die Anzeige der Nachrichten anbietet, die gegebenenfalls nicht diesen Anforderungen entsprechen, soll dies nicht negativ bewertet werden. Andere Darstellungsweisen sind positiv, sie können bestimmte Nutzer-Bedürfnisse erfüllen. So kann die Inline-Darstellung von empfangenen und gesendeten Nachrichten für Braille-Nutzer vorteilhaft sein.

* Die Unterscheidung der Nachrichten von verschiedenen Personen sollte nicht ausschließlich über eine unterschiedliche Textfarbe geschehen - vergleiche auch Abschnitt 4.2 Abrenzung zu anderen Prüfschritten

=== 4. Einordnung des Prüfschritss

==== 4.1 Einordnung des Prüschritts nach der EN 301 549 V3.1.1., Annex A

Tabelle A2 verweist auf Abschnitt 6.2.2 "Display of RTT".

==== 4.2 Abgrenzung zu anderen Prüfschritten

Wenn Nachichten des Senders und des Empfängers nur über die Farbe des Textes unterschieden werden können und der Kontrastunterschied beider Arten von Nachricht unter 3:1 liegt, sind sowohl dieser Prüfschritt als auch Prüfschritt 1.4.1a "Ohne Farbe nutzbar" nicht erfüllt.

== Quellen

[.BLOCK_LANG_EN]
=== 6.2.2.1 Visually distinguishable display

[.BLOCK_LANG_EN]
--
Where ICT has RTT send and receive capabilities, displayed sent text shall be
visually differentiated from, and separated from, received text. 

NOTE:
The ability of the user to choose between having the send and receive text be
displayed in-line or separately, and with options to select, allows users to
display RTT in a form that works best for them.
This would allow Braille users to use a single field and take turns and have
text appear in the sequential way that they may need or prefer.
--

(Aus EN 301 549 V3.1.1 Abschnitt 6.2.2.1 "Visually distinguishable display")
