= Prüfschritt 6.2.2.2 Programmatische Ermittelbarkeit bei Textnachrichten
include::include/author.adoc[]
include::include/attributes.adoc[]


== Was wird geprüft?

Wenn das Webangebot eine Funktion zur Echtzeit Textkommunikation anbietet, sind gesendeter und empfangener Text programmatisch unterscheidbar.
Dies ermöglicht Hilfsmitteltechnologien wie Screenreadern die Ansage der jeweiligen Sende- oder Empfangsrichtung.

== Warum wird das geprüft?
Echtzeit-Textkommunikation (real time text, RTT), ermöglicht es, einem Empfänger eine Nachricht zeichenweise anzuzeigen. Ein Empfänger kann jeden Buchstaben, den man schreibt, in dem Moment sehen, in dem der Sender ihn schreibt. Die Nutzenden müssen nicht (wie etwa in einem Chat), eine Nachricht zuerst schreiben und anschließend abschicken.

Diese Kommunikationsform ist beispielsweise in Notsituationen hilfreich, in der keine Zeit vergeudet werden soll. Echtzeit-Textkommunikation kann auch für Menschen mit einer Hör- oder Spracheinschränkung eine Alternative zum mündlichen Dialog darstellen.
Menschen, die Echtzeit-Textkommunikastion mit einem Hilfsmittel  wie Screenreadern nutzen, sollen in der Lage sein, empfangene und gesendete Nachrichten programmatisch zu unterscheiden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn das Webangebot Echtzeit Textkommunikation
senden und empfangen kann.

=== 2. Prüfung

Das Webangebot mit der Echtzeit-Textkommunikation sollte zusätzlich zur
Quelltext-Analyse mit dem
Screenreader geprüft werden, um zu beurteilen, ob die notwendigen
Informationen korrekt an den Screenreader gesendet werden und dieser die
Richtung der einzelnen Textnachrichten verständlich ansagt bzw. diese aus der
Ausgabe deutlich hervorgeht.

==== 2.1 Prüfung im Quelltext

. Webangebot öffnen
. Prüfen, ob das Webangebot das Senden und Empfangen von Echtzeit
  Textkommunikation anbietet
. Prüfen, ob die gesendeten und empfangenen Textnachrichten semantisch
  voneinander unterscheidbar sind. Dazu kann z. B. im HTML-Quelltext der
  jeweilige Verfasser mit Uhrzeit genannt werden.

==== 2.2 Zusätzliche Prüfung mittels Screenreader

. Screenreader starten
. die zu prüfende Web-App mit der Ansicht für die Echtzeit-Textkommunikation
  aufrufen
. einige Testnachrichten senden und empfangen (ggf. zweites Gerät notwendig)
. die Textnachrichten antippen bzw. mit dem Screenreader zu diesen navigieren
. auf die Ausgabe des Screenreaders achten, die Sende- und Empfangsrichtung
  muss durch die Ausgabe deutlich und unmissverständlich hervorgehen

== 3. Hinweise

== 4. Bewertung

== Einordnung des Prüfschritts
Die Tabelle A1 verweist auf 6.6.2.2 Programmatically determinable send and receive direction

=== Abgrenzung zu anderen Prüfschritten
== Quellen

[.BLOCK_LANG_EN]
=== 6.2.2.2 Programmatically determinable send and receive direction

[.BLOCK_LANG_EN]
--
Where ICT has RTT send and receive capabilities, the send/receive direction of
transmitted/received text shall be programmatically determinable, unless the
RTT is implemented as closed functionality. 

NOTE:
This enables screen readers to distinguish between incoming text and outgoing
text when used with RTT functionality.
--

(Aus EN 301 549 V3.1.1 Abschnitt 6.2.2.2 "Programmatically determinable send
and receive direction")
