= Prüfschritt 6.2.4 Reaktionsgeschwindigkeit der Echtzeit-Textkommunikation
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn die Web-App Echtzeit-Textkommunikation (RTT, Real-Time Text) unterstützt und Texteingaben entgegennimmt, soll die kleinste Texteinheit (einzelne Zeichen oder Wörter) in maximal 500 Millisekunden abgeschickt werden. Es geht hier also um Systeme, die eingegebene Zeichen unmittelbar nach der Eingabe an den Empfänger weiterleiten. Die Nachricht muss nicht erst wie in den meisten Chat-Systemen nach Eingabe abgeschickt werden, sondern erscheint unmittelbar.

== Warum wird das geprüft?

Menschen, die über Texteingabe an einer Online-Kommunikation teilnehmen, sollen gegenüber Sprechenden nicht benachteiligt werden. Die Eingaben sollen unmittelbar oder nur mit geringer Verzögerung für andere Teilnehmende sichtbar werden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn das Webangebot Eingaben für Echtzeit-Textkommunikation unterstützt. Das ist z.B. der Fall, wenn es sich um eine Anwendung zur Kommunikation handelt, die Echtzeit-Textkommunikation unterstützt und in der Benutzerschnittstelle eine entsprechende Eingabemöglichkeit bereithält.

=== 2. Prüfung

Für diesen Prüfschritt existieren bislang nur Ansätze für die Prüfung in der Praxis. Eigentlich müsste gemessen werden, wann die Daten, direkt nach der Eingabe,
von der Anwendung abgeschickt werden. Zwischenzeitlich kann man testen, indem eine Echtzeit-Textkommunikation zwischen zwei Geräten hergestellt wird.

Die kleinste Texteinheit (einzelne Zeichen oder Wörter) sollte dabei möglichst unmittelbar nach der Eingabe auf dem zweiten Gerät erscheinen.

Die Übertragung sollte nicht mehr als eine halbe Sekunde dauern. Physikalische Grenzen durch die Netzwerktechnik müssen dabei berücksichtigt und abgezogen werden.
Dies wird z. B. bei weiten Entfernungen der Kommunikationspartner relevant. Die reine Übertragungszeit kann z. B. mit einem "`Ping`" gemessen werden.

=== 3. Hinweise

* Bei Echtzeit-Textkommunkation (RTT, Real-Time Text) erscheint der Text beim Empfänger dynamisch schon während der Eingabe des Senders. RTT ist also nicht das Gleiche wie etwa Chat, wo Nachrichten explizit abgeschickt werden und erst dann beim Empfänger erscheinen.

* Es sollte eine maximale Verzögerung von 300 Millisekunden für das Abschicken der Eingabe angestrebt werden, da dies den wahrgenommenen Informationsfluss verbessert.

Für Hinweise, wie dies zuverlässig in der Praxis gemessen werden kann, können Sie auf GitHub https://github.com/BIK-BITV/BIK-Web-Test/issues[ein Issue eröffnen].

== Quellen
* https://en.wikipedia.org/wiki/Real-time_text[Wikipedia-Eintrag für Real-Time Text]

== Einordnung des Prüfschritts
=== Einordnung des Prüfschritts nach EN 301 549 V3.2.1

[.BLOCK_LANG_EN]
==== 6.2.4 RTT responsiveness
____
[.BLOCK_LANG_EN]
--
Where ICT utilises RTT input, that RTT input shall be transmitted to the ICT
network or platform on which the ICT runs within 500 ms of the time that the
smallest reliably composed unit of text entry is available to the ICT for
transmission.
Delays due to platform or network performance shall not be included in the
500 ms limit. 

NOTE 1:
For character by character input, the "smallest reliably composed unit of text
entry" would be a character.
For word prediction it would be a word.
For some voice recognition systems - the text may not exit the recognition
software until an entire word (or phrase) has been spoken.
In this case, the smallest reliably composed unit of text entry available to
the ICT would be the word (or phrase). 

NOTE 2:
The 500 ms limit allows buffering of characters for this period before
transmission so character by character transmission is not required unless the
characters are generated more slowly than 1 per 500 ms. 

NOTE 3:
A delay of 300 ms, or less, produces a better impression of flow to the user.
--
____
