= Prüfschritt 6.3 Anrufer-Identifizierung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn die Web-Anwendung Telekommunikationsfunktionen mit Anrufidentifizierung bietet, 
soll die Identifizierung (auch) in Textform verfügbar und programmatisch
ermittelbar sein.

== Warum wird das geprüft?

Diese Anforderung stellt sicher, dass auch Nutzende von Hilfsmittel-Technologien 
den Anrufer identifizieren können.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Web-Anwendung Telekommunikationsfunktionen 
mit Anrufidentifizierung bietet. 
Anrufidentifizierung bedeutet hier die Signalisierung bzw. Anzeige des Anrufenden.

=== 2. Prüfung

Für die Prüfung muss die Web-Anwendung ggf. auf zwei Geräten geöffnet werden.

. Screenreader starten
. Web-Anwendung öffnen
. Anruf von einem zweiten Gerät tätigen
. Prüfen, wie der Anruf in Zusammenhang mit dem aktiviertem Screenreader signalisiert wird. 
Wird der Anrufende automatisch angesagt 
oder sind die Informationen über den Anrufenden im Browser für den Screenreader ohne Umwege auslesbar?
. Prüfen, wie der Anruf visuell signalisiert bzw. angezeigt wird. 
Die Anzeige muss den Anrufenden in irgend einer Weise in Textform identifizieren, 
z. B. über die Telefonnummer oder über den für die Nummer hintelegten Namen des Anrufers.

== Quellen
* https://labs.etsi.org/rep/HF/en301549/uploads/272bede3724c5c99efe777f778201f70/tr_103708v010101p.pdf[Human Factors (HF); Real-Time Text (RTT) in Multiparty Conference Calling / ETSI TR 103 708 V1.1.1 (2022-08)]

== Einordnung des Prüfschritts
=== Einordnung des Prüfschritts nach EN 301 549 V3.2.1

[.BLOCK_LANG_EN]
==== 6.3 Caller ID
____
[.BLOCK_LANG_EN]
Where ICT provides caller identification or similar telecommunications
functions, the caller identification and similar telecommunications functions
shall be available in text form as well as being programmatically
determinable, unless the functionality is closed.
____
