= Prüfschritt 6.3 Anrufidentifizierung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Grundlage des Prüfschritts ist die Tabelle A.2 im Annex A der EN 301 549
V3.1.1.
In dieser Tabelle wird auf Abschnitt
6.3 "Caller ID" verwiesen.

== Was wird geprüft?

Wenn die Software Telekommunikationsfunktionen mit Anrufidentifizierung bietet,
soll die Identifizierung (auch) in Textform verfügbar und programmatisch
ermittelbar sein.

Diese Anforderung stellt sicher, dass auch Nutzer von Hilfstechnologien den
Anrufer identifizieren können.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Software Telekommunikationsfunktionen
mit Anrufidentifizierung bietet.

Anrufidentifizierung bedeutet hier, die Signalisierung bzw. Anzeige des
Anrufers.

=== Prüfung

Für die Prüfung muss die App ggf. auf zwei Geräten installiert werden.

. Screenreader Voiceover bzw. TalkBack starten
. App starten
. Anruf von einem zweiten Gerät tätigen
. prüfen, wie der Anruf in Zusammenhang mit dem aktiviertem Screenreader
  signalisiert wird, wird der Anrufer automatisch angesagt oder sind die
  Informationen über den Anrufer auf dem Bildschirm für den Screenreader
  ohne Umwege auslesbar?
. prüfen, wie der Anruf visuell signalisiert bzw. angezeigt wird, die Anzeige
  muss den Anrufer in irgendeinerweise in Textform identifizieren, z. B. über
  die Telefonnummer, Name etc

== Quellen

[.BLOCK_LANG_EN]
=== 6.3 Caller ID

[.BLOCK_LANG_EN]
Where ICT provides caller identification or similar telecommunications
functions, the caller identification and similar telecommunications functions
shall be available in text form as well as being programmatically
determinable, unless the functionality is closed.

(Aus EN 301 549 V3.1.1 Abschnitt 6.3 "Caller ID")
