= Prüfschritt 6.3 Anrufidentifizierung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Grundlage des Prüfschritts ist die Tabelle A.1 im Annex A der EN 301 549
V3.1.1.
In dieser Tabelle wird auf Abschnitt
6.3 "Caller ID" verwiesen.

== Was wird geprüft?

Wenn die Web-App Telekommunikationsfunktionen mit Anrufidentifizierung bietet,
soll die Identifizierung (auch) in Textform verfügbar und programmatisch
ermittelbar sein.

Diese Anforderung stellt sicher, dass auch Nutzer von Hilfstechnologien den
Anrufer identifizieren können.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Web-App Telekommunikationsfunktionen
mit Anrufidentifizierung bietet.

Anrufidentifizierung bedeutet hier, die Signalisierung bzw. Anzeige des
Anrufers.

=== Prüfung

Für die Prüfung muss die Web-App ggf. auf zwei Geräten geöffnet werden.

. Screenreader starten
. Web-App öffnen
. Anruf von einem zweiten Gerät tätigen
. Prüfen, wie der Anruf in Zusammenhang mit dem aktiviertem Screenreader
  signalisiert wird. Wird der Anrufer automatisch angesagt oder sind die
  Informationen über den Anrufer im Browser für den Screenreader
  ohne Umwege auslesbar?
. Prüfen, wie der Anruf visuell signalisiert bzw. angezeigt wird. Die Anzeige
  muss den Anrufer in irgend einer Weise in Textform identifizieren, z. B. über
  die Telefonnummer oder über den für die Nummer hintelegten Namen des Anrufers.

== Quellen

[.BLOCK_LANG_EN]
=== 6.3 Caller ID

[.BLOCK_LANG_EN]
Where ICT provides caller identification or similar telecommunications
functions, the caller identification and similar telecommunications functions
shall be available in text form as well as being programmatically
determinable, unless the functionality is closed.

(Aus EN 301 549 V3.1.1 Abschnitt 6.3 "Caller ID")
