= Prüfschritt 6.4 Alternativen zu sprachbasierten Diensten
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn ein Webangebot Echtzeit-Sprachkommunikation mit Voicemail-Funktion bietet oder interaktive Sprachdialogsysteme einsetzt (z.B. sprachgesteueerte Menüführung), sollen etwaige Aufgaben auch ohne die Fähigkeit zum Hören und Sprechen durchführbar sein.

== Warum wird das geprüft?

Gehörlose und schwerhörige Menschen und Menschen mit Einschränkungen beim Sprechen können sprachbasierte Dienste nicht nutzen. Deshalb muss eine zugängliche Alternative bereitstehen, in der der Zugang zu Informationen und deren Ausgabe auch ohne Sprechen und Hören möglich ist.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn das Webangebot Echtzeit-Sprachkommunikation mit Voicemail-Funktion oder interaktive Sprachdialogsysteme (z.B. sprachgesteuerte Menüführung bei einer Hotline) einsezt.

=== 2. Prüfung
Wenn Informationen über Echtzeit-Sprachkommunikation bereitgestellt werden, prüfen, ob diese auch ohne Sprach- und Hör-Fähigkeit zugänglich ist. Dies beinhaltet:

* eine alternative Zugangsmöglichkeit, z.B. über barrierefreie Menüs oder Formulare
* eine alternative barrierefreie Ausgabe der Information, etwa als sichtbarer programmatisch ermittelbarer Text 

=== 3. Hinweise

Ein Beispiel für einen Dienst, der Sprach und Hörfähigkeiten voraussetzt, ist z.B. das Video-Ident-Verfahren. Dieses wird u. a. bei Online-Banken für die Identifizierung genutzt. Mit einem Videoanruf werden dabei Personalausweis etc. auf Echtheit geprüft. Hier muss eine Alternative geboten werden, die das Hören und Sprechen nicht erfordert.

Ein anderes Beispiel ist telefonische Ansage des Guthabens bei einem Prepaid-Mobilfunkvertrag. Hier müsste der Anbieter das aktuelle Guthaben in Textform auf der Seite bereitstellen.

Für Hinweise zu diesem Prüfschritt können Sie auf GitHub https://github.com/BIK-BITV/BIK-Web-Test/issues[ein Issue anlegen].

== Quellen

[.BLOCK_LANG_EN]
=== 6.4 Alternatives to voice-based services

[.BLOCK_LANG_EN]
--
Where ICT provides real-time voice-based communication and also provides voice
mail, auto-attendant, or interactive voice response facilities, the ICT shall
offer users a means to access the information and carry out the tasks provided
by the ICT without the use of hearing or speech. 

NOTE 1:
Tasks that involve both operating the interface and perceiving the information
would require that both the interface and information be accessible without
use of speech or hearing. 

NOTE 2:
Solutions capable of handling audio, RTT and video media could satisfy the
above requirement.
--

(Aus EN 301 549 V3.1.1 Abschnitt 6.4 "Alternatives to voice-based services")
