= Prüfschritt 6.5.2 Auflösung bei Videotelefonie
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Web-Apps mit Videotelefonie-Funktion sollen mindestens die QVGA-Auflösung
für die Videoübertragung unterstützen.
Üblicherweise entspricht dies 320x240 Pixel.
Bei anderen Seitenverhältnissen müssen entsprechend 76.800 Bildpunkte geboten
werden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Web-App Videotelefonie unterstützt.

=== 2. Prüfung

. Die technische Dokumentation der Web-App konsultieren.  Wird mindestens eine QVGA (320x240 Pixel) angegeben?
. Testübertragung: Den visuellen Eindruck prüfen. Ist die Angabe in der App-Dokumentation plausibel?

=== 3. Hinweise

Für Hinweise zu diesem Prüfschritt eröffnen Sie gerne https://github.com/BIK-BITV/BIK-Web-Test/issues[ein
Issue auf GitHub].

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

* 6.5.2 Resolution

== Quellen

[.BLOCK_LANG_EN]
=== 6.5.2 Resolution

[.BLOCK_LANG_EN]
--
Where ICT that provides two-way voice communication includes real-time video
functionality, the ICT:

* shall support at least QVGA resolution
--

(Aus EN 301 549 V3.1.1 Abschnitt 6.5.2 "Resolution")
