= Prüfschritt 6.5.3 Bildrate bei Videotelefonie
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Grundlage des Prüfschritts ist die Tabelle A.2 im Annex A der EN 301 549
V3.1.1.
In dieser Tabelle wird auf Abschnitt
6.5.3 "Framerate" verwiesen.

== Was wird geprüft?

Wenn die Software Videotelefonie unterstützt, soll die dabei verwendete
Framerate bzw. Bildrate mindestens 20 Bildern pro Sekunde entsprechn.
Besser ist eine Mindestbildrate von 30 Bildern pro Sekunde.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Software Videotelefonie unterstützt.

=== Prüfung

Eine genaue Methode zur Messung de verwendeten Bildrate ist noch offen.
Hinweise zur Weiterentwicklung des Prüfschritts können Sie auf GitHub
{app-issue-url}[in einem Issue] hinterlassen.

Zur Beurteilung der Konformität mit diesem Prüfschritt müssen derzeit die
Angaben des Software-Herstellers mit den eigenen visuellen Eindrücken
abgeglichen werden.

Für die Prüfung muss die Software ggf. auf zwei Geräten installiert werden.

. Verwendete Bildrate der App-Dokumentation entnehmen oder vom Hersteller
  erfragen, sind dies mindestens 20 Bilder pro Sekunde?
. App auf zwei Geräten staten
. Videotelefonieverbindung zwischen den Geräten herstellen
. Prüfen, ob das Bild flüssig dargestellt wird, scheint die Angabe des
  Herstellers über die Bildrate plausibel?

==== Hinweise

Für die Videotelefonie ist eine Mindestbildrate von 30 Bildern pro Sekunde
empfehlenswert, um eine flüssige Darstellung des Bildes zu gewährleisten.

== Quellen

[.BLOCK_LANG_EN]
=== 6.5.3 Framerate

[.BLOCK_LANG_EN]
--
Where ICT that provides two-way voice communication includes real-time video
functionality, the ICT:

* shall support a frame rate of at least 20 frames per second (FPS)
--

(Aus EN 301 549 V3.1.1 Abschnitt 6.5.3 "Framerate")
