= Prüfschritt 7.1.2 Synchrone Untertitel
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Grundlage des Prüfschritts ist die Tabelle A.2 im Annex A der EN 301 549
V3.1.1.
In dieser Tabelle wird auf Abschnitt
7.1.2 "Captioning synchronization" verwiesen.

== Was wird geprüft?

Software, die Untertitel anzeigt, soll diese synchron, wie in der
Untertitel-Quelle definiert, zum Video und Audio anzeigen.

Die Anzeige der Untertitel soll dabei nicht mehr als 100 Millisekunden vom
Zeitstempel in der Untertitel-Datei (oder anderen Quellen) abweichen.
Dies bezieht sich auch auf Live-Untertitel, sobald die Software die Untertitel
empfängt, soll sich die Anzeige der Untertitel nicht länger als um 100
Millisekunden verzögern.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Software Untertitel anzeigt.

=== Prüfung

Wie dieser Prüfschritt optimal in der Praxis geprüft werden kann, ist noch
nicht vollständig geklärt.
Hinweise dazu können Sie in einem {app-issue-url}[Issue auf GitHub, mit Bezug
zu diesem Prüfschritt, hinterlassen].

In der Praxis sollte Software, bei der die Untertitel ohne merkliche
Verzögerung angezeigt werden, zu diesem Prüfschritt konform sein.

Detailliertere Untersuchungen scheinen derzeit nur möglich, wenn die Software
die Wiedergabe von externen Videoinhalten zulässt.

Hier kann dann anhand einer Beispiel-Video-Datei mit eingebetteten Untertiteln,
die korrekte Zeitstempel gesetzt hat, ein Vergleich angestellt
werden:

Das Video wird dabei in einem konformen Player abgespielt und zusätzlich in der
zu testenden Software.
Wenn die Untertitel in der Software im vergleich zum konformen Player verzögert
dargestellt werden, ist dieses Problem damit auf die Software zurückzuführen.

Spielt die Software jedoch nur mitgelieferte Videos ab, sollte
Stichprobenartig geprüft werden, ob es in der Software Videos gibt, bei denen
die Untertitel korrekt und damit synchron zum Video dargestellt werden.
Wenn dies der Fall ist, kann die Software Untertitel prinzipiell korrekt
darstellen.
Der Prüfschritt ist damit bestanden, Probleme mit der Synchronität sind dabei
höchstwahrscheinlich bei den Inhalten zu suchen und nicht in der Software
selbst.

==== Hinweise

In diesem Prüfschritt werden keine Inhalte geprüft!
Die Software soll lediglich grundsätzlich in der Lage sein, Videos mit
Untertiteln synchron darzustellen.

== Quellen

[.BLOCK_LANG_EN]
=== Captioning synchronization

[.BLOCK_LANG_EN]
--
Where ICT displays captions, the mechanism to display captions shall preserve
synchronization between the audio and the corresponding captions as follows: 

* Captions in recorded material:
  within 100 ms of the time stamp of the caption 
* Live captions:
  within 100 ms of the availability of the caption to the player.
--

(Aus EN 301 549 V3.1.1 Abschnitt 7.1.2 "Captioning synchronization")
