= Prüfschritt 7.1.1 Wiedergabe von Untertiteln
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Sind Videos mit synchroner Bild- und Tonspur vorhanden und werden  dynamisch zuschaltbare, textbasierte Untertitel (closed captions) angeboten, bietet der Videoplayer die Möglichkeit, diese ein- und auszublenden. 

== Warum wird das geprüft?

Filme sind in der Regel ohne den Ton nicht zu verstehen. Daher muss für Menschen mit Höreinschränkung der Inhalt der Tonspur durch Untertitel bereitgestellt werden. 

Untertitel können auf unterschiedliche Arten eingebunden werden: 
Manche Player unterstützen nur die dauerhaft sichtbaren „open captions“, 
die meisten jedoch sogenannte textbasierte „closed captions“, die über ein Bedienelement 
am Player flexibel zuschaltbar sind. 

Damit closed captions (dynamisch zuschaltbare Untertitel) von den Nutzenden wahrgenommen werden können, ist es erforderlich, dass der Videoplayer die Möglichkeit bietet, diese ein- und auszublenden. Bei open captions handelt es sich hingegen um immer sichtbare Untertitel, d.h. der Videoplayer wird hier nicht geprüft.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

*	Der Prüfschritt ist anwendbar, wenn die  Webseite aufgezeichnete Videos mit synchroner Bild- und Tonspur anbietet und Untertitel zuschaltbar sind. Die Untertitel sind dann in der Regel innerhalb des ``video``-Elements als getrennte ``track``-Datei verfügbar.
*	Aufgezeichnete Videos ohne Tonspur (stumme Videos) brauchen keine Untertitelung, der Prüfschritt ist für sie nicht anwendbar.

=== 2. Prüfung

. Text-Dateien für Untertitelungen werden meist über das HTML 5 `track`-Element eingebunden. Im Quellcode prüfen, ob über das `track`-Element eine Untertitel-Datei eingebunden ist. Das `kind`-Attribut legt die Art der Texteinblendung fest. Der Wert `subtitles` zeigt an, dass es sich um Untertitel handelt (Transkription oder Übersetzung des Dialogs). Der Wert `captions` zeigt an, dass es sich um Untertitel für hörgeschädigte und gehörlose Menschen handelt.
. Ggf. binden Player Untertitel-Dateien auch außerhalb des `video`-Elements ein.
. Wenn eine Untertitel-Datei eingebunden ist, prüfen, ob der Videoplayer eine Möglichkeit bietet, diese ein- und auszublenden.

=== 3. Hinweise

* Empfehlenswert wäre, wenn der Videoplayer eine Funktion zur Verfügung stellt, um die Untertitel auf einer Braillezeile anzuzeigen.
* Nicht negativ bewertet wird, wenn ein alternatives Video mit open captions bei Aktivierung eines Bedienelements im Player neu geladen wird, oder wenn das Video mit open captions über einen zweiten Player angezeigt wird.

=== 4. Bewertung

==== Erfüllt

Sind Videos mit synchroner Bild- und Tonspur vorhanden, werden Untertitel als fester Bestandteil des Videos angezeigt (open captions) oder können über ein Bedienelement des Videoplayers ein- und ausgeblendet werden (closed captions).

==== Nicht voll erfüllt

Es wird eine Untertitel-Datei angeboten, der Player bietet jedoch keine Möglichkeit, diese anzuzeigen.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten

Bei diesem Prüfschritt geht es um den eigentlichen Prozess der Anzeige von Untertiteln während der Wiedergabe sowie um die Bedienelemente zum Ein- und Ausschalten von Untertiteln im Videoplayer.

ifdef::env_embedded[9.1.2.2 "Aufgezeichnete Videos mit Untertiteln"]
ifndef::env_embedded[]
<<9.1.2.2 Aufgezeichnete Videos mit Untertiteln.adoc#,9.1.2.2 Aufgezeichnete
Videos mit Untertiteln>> bezieht sich hingegen auf den Inhalt der Untertitel.
Es geht darum, dass der Autor bei der Erstellung der Untertitel sicherstellen muss, dass Audioinhalt korrekt transkribiert wurde und in einem Format erfasst werden, das für die Bereitstellung synchronisierter Untertitel verwendet werden kann. 

Anforderungen der Video-Bedienelemente bezüglich Kontrast, zugänglichem Namen, Tastaturbedienbarkeit, Fokushervorhebung usw. werden in den entsprechenden Prüfschritten geprüft.

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

7.1.1 Captioning playback

== Quellen

[.BLOCK_LANG_EN]
=== 7.1.1 Captioning playback

[.BLOCK_LANG_EN]
--
Where ICT displays video with synchronized audio, it shall have a mode of
operation to display the available captions.
Where closed captions are provided as part of the content, the ICT shall allow
the user to choose to display the captions.

NOTE 1:
Captions may contain information about timing, colour and positioning.
This caption data is necessary for caption users.
Timing is used for caption synchronization.
Colour can be used for speaker identification.
Position can be used to avoid obscuring important information.

NOTE 2:
If a Braille device is connected, the ICT should provide an option to display
captions on the Braille device.
--

(Aus EN 301 549 V3.1.1 Abschnitt 7.1.1 "Captioning playback")
