= Prüfschritt 7.1.5 Gesprochene Untertitel
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn das Webangebot Videos mit einem Orginalton enthält, der nicht der Hauptsprache des Webangebots entspricht, sollen zuschaltbaren bzw. programmatisch ermittelbaren Untertitel, die in der Hauptsprache der Seite angeboten werden als akustische Ausgabe zugänglich sein, z.B. über eine eigene Tonspur, die den Untertiteln entspricht, oder über eine gnerierte Sprachausgabe der Untertitel. Nicht programmatisch ermittelbar sind Untertitel, die "fest eingebrannt", also Teil der Bildinformation, sind.

== Warum wird das geprüft?

Für Menschen, die den fremdsprachigen Originalton eines Videos nicht verstehen, ist eine Übersetzung in Untertiteln in der eigenen Sprache wichtig. Diese Untertitel sollen auch für blinde oder seheingeschränkte Menschen als akustische Ausgabe zugänglich sein.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar:

* wenn der Original-Ton des Videos fremdsprachig ist (d.h. er entspricht nicht der Hauptsprache des Webauftritts) 
* und Untertitel in der Hauptsprache des Webauftritts bereitgestellt werden
* und wenn es keine Version des Videos mit einer Tonspur in der Hauptsprache des Webauftritts gibt.

=== 2. Prüfung

. Webangebot öffnen.
. Prüfen, ob der Originalton des Videos von der Hauptsprache des Webangebots abweicht.
. Prüfen, ob für Videos mit fremdsprachiger Tonspur Untertitel in der Hauptsprache des Webangebots angeboten werden.
. Prüfen, ob sich eine alternative Tonspur in der Hauptsprache des Angebots oder eine generierte Sprachausgabe der Untertitel aktivieren lässt.

=== 3. Hinweise

* Gängige Video-Player verfügen derzeit meist nicht über die Möglichkeit einer einschaltbaren Sprachausgabe der Untertitel.
* Die Anforderung 7.1.5 Gesprochene Untertitel soll blinden und seheingeschränkten Nutzenden Untertitel in der Hauptsprache der Seite zugänglich machen, sofern der Original-Ton des Videos dieser nicht entspricht. 
Ist der Original-Ton des Videos bereits in der Hauptsprache, so gelten Untertitel in anderen Sprachen als zusätzliche Informationen und sind daher nicht von der Anforderung betroffen.

Hinweise zu diesem Prüfschritt können Sie auf GitHub https://github.com/BIK-BITV/BIK-Web-Test/issues[in einem Issue anlegen].

=== 4. Bewertung

==== Nicht erfüllt:

* Bei Videos mit fremdsprachiger Tonspur und zuschaltbaren Untertiteln in der Hauptsprache, sind die Untertitel nicht als akustische Ausgabe zugänglich. 

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 v.3.2.1

==== 7.1.5  Spoken subtitles

== Quellen

=== EN 301 549 V3.2.1
[.BLOCK_LANG_EN]
=== 7.1.5 Spoken subtitles

[.BLOCK_LANG_EN]
--
Where ICT displays video with synchronized audio, it shall have a mode of operation to provide a spoken output of the available captions, except where the content of the displayed captions is not programmatically determinable.

NOTE 1: Being able to manage speech output range for spoken subtitles independently from general ICT speech is preferable for most users. That is possible when the audio file with spoken subtitle is delivered in a separate audio track and mixed in the end users device.
