= Prüfschritt 7.1.2 Synchrone Untertitel
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Web-Angebote, die Untertitel anzeigen, sollen diese synchron zum Video und dessen Audio anzeigen, wie in der Untertitel-Quelle definiert.

Die Anzeige der Untertitel soll dabei nicht mehr als 100 Millisekunden vom Zeitstempel in der Untertitel-Datei (oder anderen Quellen) abweichen. Dies bezieht sich theoretisch auch auf Live-Untertitel, die jedoch naturgemäß einer Verzögerung durch die Konvertierung von gesprochener Sprache in Text unterliegen, besonders wenn die Konvertierung nicht automatisch erfolgt, sondern durch Menschen geschieht. 

== Warum wird das geprüft?

Wenn Untertitel nicht synchron laufen, wird für Menshcn mit Hörbehinderung das Verständnis der Video-Inhalte schwierig bis unmöglich, gerade wenn es sich um Dialoge handelt oder die Ton sich auf Bildinhalte bezieht.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Web-App Videos mit zusätzlich eingebundenen Untertiteln (open captions) enthält.

=== 2. Prüfung

. Video mit zusätzlich eingebundenen Untertitel abspielen. Ist die Untertitelung synchron?
. Wenn Ton und Untertitelung auseinanderlaufen, die Video-Datei in einem konformen Player abspielen. Laufen Ton und Untertitelung auch hier auseinander?

Detailliertere Untersuchungen scheinen derzeit nur möglich, wenn die Web-App
die Wiedergabe von externen Videoinhalten zulässt.

=== 3. Hinweise

Falls sich die niht synchrone Video-Datei nicht herunterladen lässt um sie in einem anderen konformen Player abzuspielen, muss ggf. der Anbieter um Zugang zu der Videodatei einschließlich Untertitel-Track gebeten werden.

Ist ein Vergleich zwischen dem eingebundenen Player und einem konformen Player nicht möglich, kann ggf. stichprobenartig geprüft werden, ob es im Webangebot Videos gibt, bei denen die Untertitel synchron zum Ton dargestellt werden. Wenn dies der Fall ist, ist das ein Hinweis, dass der Player Untertitel prinzipiell korrekt darstellt. Der Prüfschritt ist damit erfüllt, Probleme mit der Synchronität sind dann höchstwahrscheinlich bei den Inhalten zu suchen und nicht im eingebundenen Player.

Wie dieser Prüfschritt optimal in der Praxis geprüft werden kann, ist noch nicht geklärt. Hinweise dazu können Sie in einem https://github.com/BIK-BITV/BIK-Web-Test/issues[Issue auf GitHub, mit Bezug zu diesem Prüfschritt, hinterlassen].

=== 4. Bewertung

==== Erfüllt: 

Die Untertitel sind auch beim Abspeilen im konformen Player nicht synchron, das Problem liegt damit höchstwahrscheinlich an der Codierung der Untertitel-Datei und nicht am eingebundenen Player. Dann ist voraussichtlich der Prüfschritt 9.1.2.2 Untertitel nicht oder nicht voll erfüllt.

==== Nicht voll erfüllt:

Die im der Web-Anwendung nicht synchron Untertitel laufen beim Abspielen in einem konformen Player synchron. Hier liegt vermutlich ein Bug des eingebundenen Players vor.

==== Hinweise

== Einordnung des Prüfschritts

=== Einordnung des Prüfschrtts nach EN 301 549 V3.1.1

* 7.1.2 Captioning synchronization

=== Abgrenzung zu anderen Prüfschritten

In diesem Prüfschritt werden nicht Inhalte, Qualität und Angemessenheit der Untertitel geprüft, dies geschieht in Prüfschritt 9.1.2.2.  Der eingebundene Player soll lediglich grundsätzlich in der Lage sein, Videos mit Untertiteln synchron darzustellen.

== Quellen

[.BLOCK_LANG_EN]
=== Captioning synchronization

[.BLOCK_LANG_EN]
--
Where ICT displays captions, the mechanism to display captions shall preserve
synchronization between the audio and the corresponding captions as follows: 

* Captions in recorded material:
  within 100 ms of the time stamp of the caption 
* Live captions:
  within 100 ms of the availability of the caption to the player.
--

(Aus EN 301 549 V3.1.1 Abschnitt 7.1.2 "Captioning synchronization")
