= Prüfschritt 7.1.5 Gesprochene fremdsprachige Untertitel
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn das Webangebot Videos mit zuschaltbaren bzw. programmatisch ermittelbaren fremdsprachigen Untertiteln überträgt, kann eine Sprachausgabe der Untertitel aktiviert werden. Nicht programmatisch ermittelbar sind Untertitel, die "fest eingebrannt", also Teil der Bildinformation, sind.

== Warum wird das geprüft?

Menschen, die die Originalsprache eines Videos nicht verstehen, profitieren beispielsweise von Untertiteln in ihrer Landessprache. Wenn Untertitel in einer anderen Sprache angeboten werden, sollen diese Untertitel auch blinden oder sehbehinderten Menschen zugänglich sein. Sie können zum Beispiel als zusätzliche Tonspur oder über eine Text-to-Speech Funktionalität bereitgestellt werden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn das Webangebot Videos mit zuschaltbaren bzw. programmatisch ermittelbaren Untertiteln in einer anderen Sprache enthält (subtitles). Auf permanent sichtbare Untertitel, die "fest eingebrannt", also Teil der Bildinformation, sind, ist der Prüfschritt nicht anwendbar.

=== 2. Prüfung

. Webangebot öffnen.
. Prüfen ob neben der Originalsprache Unteritel in anderen Sprachen angeboten werden.
. Falls es sich um zuschaltbare bzw. programmatisch ermittelbare fremdsprachige Untertitel handelt: Prüfen, ob sich eine Sprachausgabe der Untertitel aktivieren lässt.

=== 3. Hinweise

Gängige Video-Player verfügen derzeit meist nicht über die Möglichkeit einer einschaltbaren Sprachausgabe der Untertitel. 

Hinweise zu diesem Prüfschritt können Sie auf GitHub https://github.com/BIK-BITV/BIK-Web-Test/issues[in einem Issue anlegen].

=== 4. Bewertung

==== Nicht erfüllt:

* Bei zuschaltbaren, programmatisch ermittelbaren fremdsprachigen Untertiteln gibt es keine Möglichkeit, eine Sprachausgabe der Untertitel zu aktivieren.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 v.3.2.1

==== 7.1.5  Spoken subtitles

== Quellen

=== EN 301 549 V3.2.1
[.BLOCK_LANG_EN]
=== 7.1.5 Spoken subtitles

[.BLOCK_LANG_EN]
--
Where ICT displays video with synchronized audio, it shall have a mode of operation to provide a spoken output of the available captions, except where the content of the displayed captions is not programmatically determinable.

NOTE 1: Being able to manage speech output range for spoken subtitles independently from general ICT speech is preferable for most users. That is possible when the audio file with spoken subtitle is delivered in a separate audio track and mixed in the end users device.
