= Prüfschritt 7.1.2 Synchrone Untertitel
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Sind Videos mit synchroner Bild- und Tonspur vorhanden, ist gewährleistet, 
dass der Videoplayer Untertiel und Ton synchron darstellt. Das bedeutet

* für Untertitel aufgezeichneter Videos: Die Anzeige des Untertitels weicht 
  nicht mehr als 100ms vom Zeitstempel der Untertitel-Datei ab.

* für Live-Untertitelung: Die Anzeige des Untertitels erfolgt innerhalb 
  von 100 ms nachdem sie im Player verfügbar ist.

== Warum wird das geprüft?
Die https://www.ndr.de/fernsehen/barrierefreie_angebote/untertitel/Untertitel-Standards,untertitelstandards102.html[Untertitel-Standards] fordern für eine Untertitelung "Synchronität". Das bedeutet, dass die Einblendung zeitgleich mit dem Bild/Ton und möglichst lippensynchron erfolgen soll. Hintergrund ist, dass Menschen mit Höreinschränkungen neben der Untertitelung auch auf das Mundbild achten.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn auf der Webseite aufgezeichnete Videos mit synchroner Bild- und 
Tonspur sowie Untertiteln vorhanden sind. Für Live-Videos muss eine Live-Untertitelung verfügbar sein.

=== 2. Prüfung
==== 2.1 Prüfung von Untertiteln eines aufgezeichneten Videos:
. Das Video in dem auf der Webseite eingebundenen Player abspielen.
. Prüfen, ob die Untertitel synchron zum Ton angezeigt werden.
. Werden Untertitel nicht synchron angezeigt, kann das an den technischen Möglichkeiten des Players oder 
  an fehlerhaften Zeitstempel in der Untertitel-Datei liegen. 
  Die Ursache kann derzeit nur vom Web-Autor geprüft werden.

==== 2.2 Prüfung von Live-Untertitelung:
. Das Video in dem auf der Webseite eingebundenen Player abspielen.
. Prüfen, ob die Untertitel synchron zum Ton angezeigt werden.
. Werden Untertitel nicht synchron angezeigt, kann das unterschiedliche Ursachen haben und kann derzeit nur 
  vom Web-Autor geprüft werden. 

=== 3. Hinweise
Hinweise zu diesem Prüfschritt können Sie auf GitHub https://github.com/BIK-BITV/BIK-Web-Test/issues[in einem Issue hinterlassen].

=== 4. Bewertungen
==== Nicht erfüllt:
Der Videoplayer stellt Untertitel nicht synchron zum Ton dar. Die Zeitstempel der 
Untertiteldatei sind korrekt gesetzt.

== Einordnung des Prüfschritts nach EN 301 549 V3.1.1
7.1.2 Captioning synchronization

=== Abgrenzung zu anderen Prüfschritten

In diesem Prüfschritt wird geprüft, ob der Videoplayer Untertitel synchron anzeigt. 
In Prüfschritt 9.1.2.2 Aufgezeichnete Videos mit Untertiteln erfolgt hingegen die inhaltliche 
Prüfung der Untertitel  (@dfischer auch - theoretisch - der korrekte Zeitstempel?). Die Prüfung, ob der Player oder die Untertitel-Datei Ursache von 
nicht-synchronen Untertiteln ist, kann derzeit nicht erfolgen. 
Werden Untertitel nicht synchron dargestellt, wird bei beiden Prüfschritten negativ bewertet mit dem Hinweis auf eine unklare Ursache.

== Quellen

[.BLOCK_LANG_EN]
=== 7.1.2 Captioning synchronization

[.BLOCK_LANG_EN]
--
Where ICT displays captions, the mechanism to display captions shall preserve
synchronization between the audio and the corresponding captions as follows: 

* Captions in recorded material:
  within 100 ms of the time stamp of the caption 
* Live captions:
  within 100 ms of the availability of the caption to the player.
--

(Aus EN 301 549 V3.1.1 Abschnitt 7.1.2 "Captioning synchronization")
