= Prüfschritt 7.1.3 Erhaltung von Untertiteln
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn das Webangebot Videos mit Untertiteln überträgt, konvertiert oder aufnimmt, bleiben 
die Untertitel erhalten, so dass die Prüfschritte
ifdef::env_embedded[7.1.1 "Wiedergabe von Untertiteln"]
ifndef::env_embedded[]
  <<7.1.1 Wiedergabe von Untertiteln.adoc#,7.1.1 Wiedergabe von
  Untertiteln>>
endif::env_embedded[]
und
ifdef::env_embedded[7.1.2 "Synchrone Untertitel"]
ifndef::env_embedded[]
  <<7.1.2 Synchrone Untertitel.adoc#,7.1.2 Synchrone Untertitel>>
endif::env_embedded[]
erfüllt sind.
Das bedeutet, die Untertitel sind nach Übertragung, Konvertierung oder Aufnahme des Videos abspielbar 
(7.1.1 Wiedergabe von Untertiteln) und werden weiterhin synchron zu Audio 
(7.1.2 Synchrone Untertitel) dargestellt. Die Zeitstempel der Untertitel bleiben erhalten. 
Darstellungsbezogene Aspekte, die eine Bedeutung tragen, sind in unverändert vorhanden.

== Warum wird das geprüft?

Wenn das Webangebot Videos mit Untertiteln überträgt, konvertiert oder aufnimmt, 
sollen diese Untertitel in gleicher Weise nutzbar sein, wie vor der Aktion. 
Dazu gehört, dass Nutzende sie weiterhin anzeigen können und dass sie synchron zu 
Audio abgespielt werden. Zusätzlich kann eine bestimmte Darstellung der Untertitel, 
je nach regionalen Konventionen, eine Bedeutung tragen. Wenn sich die Darstellung 
aufgrund der Übertragung, Konvertierung oder Aufnahme ändert, wird die Bedeutung nicht mehr 
übermittelt. Damit dies nicht passiert, sollen darstellungsbezogene Aspekte, 
die eine Bedeutung tragen, nicht verändert sein.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn das Webangebot Videos mit Untertiteln übertragen, 
konvertieren oder aufnehmen kann.

=== 2. Prüfung

* Wenn die Webangebot Videos mit Untertiteln konvertiert oder aufnimmt, 
  anschließend Video in einem konformen Player abspielen:

** Sind alle Untertitel aus der Quelle weiterhin vorhanden?
** Lassen sich alle Untertitel anzeigen?
** Sind alle Untertitel weiterhin synchron zu Ton?

* Prüfen, ob Untertitel in einer Art und Weise dargestellt werden, 
  die eine Bedeutung vermitteln. Bleiben bedeutungstragende Aspekte erhalten?

=== 3. Hinweise

Hinweise zu diesem Prüfschritt können Sie auf GitHub https://github.com/BIK-BITV/BIK-Web-Test/issues[in
einem Issue hinterlassen].

=== 4. Bewertung

==== Nicht erfüllt:
Nach der Übertragung, Konvertierung oder Aufnahme lassen sich Untertitel nicht mehr anzeigen 
oder sind nicht mehr synchron zu Bild und Ton.

== Einordnung des Prüfschritts
* In der Tabelle A1 wird auf 7.1.3  Preservation of captioning verwiesen.

=== Abgrenzung zu anderen Prüfschritten

In diesem Prüfschritt wird geprüft, ob es durch die Übertragung, Konvertierung oder Aufnahme 
zu Problemen hinsichtlich der Anzeige oder Synchronität von Untertiteln kommt. 
In den Prüfschritten 7.1.1 Wiedergabe von Untertiteln und 7.1.2 Synchrone Untertitel 
geht es hingegen um Videos, die auf der Webseite bereits vorhanden sind. 

== Quellen

[.BLOCK_LANG_EN]
=== 7.1.3 Preservation of captioning

[.BLOCK_LANG_EN]
--
Where ICT transmits, converts or records video with synchronized audio, it
shall preserve caption data such that it can be displayed in a manner
consistent with clauses 7.1.1 and 7.1.2. 

Additional presentational aspects of the text such as screen position, text
colours, text style and text fonts may convey meaning, based on regional
conventions.
Altering these presentational aspects could change the meaning and should be
avoided wherever possible.
--

(Aus EN 301 549 V3.1.1 Abschnitt 7.1.3 "Preservation of captioning")
