= Prüfschritt 7.1.2 Synchrone Untertitel
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Sind Videos mit synchroner Bild- und Tonspur vorhanden, ist gewährleistet, 
dass der Videoplayer Untertiel und Ton synchron darstellt. Das bedeutet

* für Untertitel aufgezeichneter Videos: Die Anzeige des Untertitels weicht 
  nicht mehr als 100ms vom Zeitstempel der Untertitel-Datei ab.

* für Live-Untertitelung: Die Anzeige des Untertitels erfolgt innerhalb 
  von 100 ms nach der Verfügbarkeit im Player.

== Warum wird das geprüft?
Folgt

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn auf der Webseite Videos mit synchroner Bild- und 
Tonspur sowie Untertiteln vorhanden sind.

=== 2. Prüfung
==== 2.1 Prüfung von Untertiteln eines aufgezeichneten Videos:
. Das Video in dem auf der Webseite eingebundenen Player abspielen.
. Prüfen, ob die Untertitel synchron zum Ton angezeigt werden.
. Werden Untertitel nicht synchron angezeigt, prüfen, ob die Zeitstempel korrekt gesetzt sind. 
  Sind die Zeitstempel korrekt, ist ist davon auszugehen, dass der Videoplayer die Untertitel 
  nicht synchron darstellt.

==== 2.2 Prüfung von Live-Untertitelung:
. Das Video in dem auf der Webseite eingebundenen Player abspielen.
. Prüfen, ob die Untertitel synchron zum Ton angezeigt werden.
. ???

=== 3. Hinweise
Hinweise zu diesem Prüfschritt können Sie auf GitHub https://github.com/BIK-BITV/BIK-Web-Test/issues[in einem Issue hinterlassen].

=== 4. Bewertungen
==== Nicht erfüllt:
Der Videoplayer stellt Untertitel nicht synchron zum Ton dar. Die Zeitstempel der 
Untertiteldatei sind korrekt gesetzt.

== Einordnung des Prüfschritts
Die Tabelle A1 verweist auf 7.1.2 Captioning synchronization

=== Abgrenzung zu anderen Prüfschritten

In diesem Prüfschritt wird geprüft, ob der Videoplayer Untertitel synchron anzeigt. 
In Prüfschritt 9.1.2.2 Aufgezeichnete Videos mit Untertiteln erfolgt hingegen die inhaltliche 
Prüfung der Untertitel (@dfischer auch - theoretisch - der korrekte Zeitstempel?)

== Quellen

[.BLOCK_LANG_EN]
=== 7.1.2 Captioning synchronization

[.BLOCK_LANG_EN]
--
Where ICT displays captions, the mechanism to display captions shall preserve
synchronization between the audio and the corresponding captions as follows: 

* Captions in recorded material:
  within 100 ms of the time stamp of the caption 
* Live captions:
  within 100 ms of the availability of the caption to the player.
--

(Aus EN 301 549 V3.1.1 Abschnitt 7.1.2 "Captioning synchronization")
