= Prüfschritt 7.1.5 Gesprochene Untertitel
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn das Webangebot Videos mit einem Orginalton enthält, der nicht der Hauptsprache des Webangebots entspricht, sollen zuschaltbaren bzw. programmatisch ermittelbaren Untertitel, die in der Hauptsprache der Seite angeboten werden über eine Sprachausgabe zugänglich sein. Nicht programmatisch ermittelbar sind Untertitel, die "fest eingebrannt", also Teil der Bildinformation, sind.

== Warum wird das geprüft?

Menschen, die fremdsprachigen Originalton eines Videos nicht verstehen, profitieren von Untertiteln in ihrer Landessprache. Wenn Untertitel in der Hauptsprache des Webangebots angeboten werden, sollen diese Untertitel auch blinden oder sehbehinderten Menschen zugänglich sein. Sie können zum Beispiel als zusätzliche Tonspur oder über eine Text-to-Speech Funktionalität bereitgestellt werden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar:

* wenn der Original-Ton des Videos fremdsprachig ist (d.h. er entspricht nicht der Hauptsprache des Webauftritts) 
* und Untertitel in der Hauptsprache des Webauftritts bereitgestellt werden
* und wenn es keine Version des Videos mit einer Tonspur in der Hauptsprache des Webauftritts gibt.

=== 2. Prüfung

. Webangebot öffnen.
. Prüfen, ob der Originalton des Videos in der Hauptsprache des Webangebots ist.
. Prüfen ob neben der Originalsprache Untertitel in der Hauptsprache des Webangebots angeboten werden.
. Falls es sich dabei um zuschaltbare bzw. programmatisch ermittelbare Untertitel handelt: Prüfen, ob sich eine Sprachausgabe der Untertitel aktivieren lässt.

=== 3. Hinweise

Gängige Video-Player verfügen derzeit meist nicht über die Möglichkeit einer einschaltbaren Sprachausgabe der Untertitel. 

Hinweise zu diesem Prüfschritt können Sie auf GitHub https://github.com/BIK-BITV/BIK-Web-Test/issues[in einem Issue anlegen].

=== 4. Bewertung

==== Nicht erfüllt:

* Bei Angeboten mit fremdsprachiger Tonspur und Untertiteln in der Hauptsprache gibt es keine Möglichkeit, eine Sprachausgabe dieser Untertitel zu aktivieren.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 v.3.2.1

==== 7.1.5  Spoken subtitles

== Quellen

=== EN 301 549 V3.2.1
[.BLOCK_LANG_EN]
=== 7.1.5 Spoken subtitles

[.BLOCK_LANG_EN]
--
Where ICT displays video with synchronized audio, it shall have a mode of operation to provide a spoken output of the available captions, except where the content of the displayed captions is not programmatically determinable.

NOTE 1: Being able to manage speech output range for spoken subtitles independently from general ICT speech is preferable for most users. That is possible when the audio file with spoken subtitle is delivered in a separate audio track and mixed in the end users device.
