= Prüfschritt 7.1.2 Synchrone Untertitel
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Sind Videos mit synchroner Bild- und Tonspur vorhanden, ist gewährleistet, dass der Videoplayer Untertitel und Ton synchron darstellt. 

Das bedeutet für Untertitel aufgezeichneter Videos: Die Anzeige des Untertitels weicht nicht mehr als 100ms vom Zeitstempel der Untertitel-Datei ab. 
Dies bezieht sich theoretisch auch auf Live-Untertitel. Hier liegt jedoch naturgemäß einer Verzögerung durch die Konvertierung von gesprochener Sprache in Text vor, besonders, wenn die Konvertierung nicht automatisch, sondern durch Menschen erfolgt.

== Warum wird das geprüft?
Die https://www.ndr.de/fernsehen/barrierefreie_angebote/untertitel/Untertitel-Standards,untertitelstandards102.html[Untertitel-Standards] fordern für eine Untertitelung "Synchronität". Das bedeutet, dass die Einblendung zeitgleich mit dem Bild/Ton und möglichst lippensynchron erfolgen soll. Hintergrund ist, dass Menschen mit Höreinschränkungen neben der Untertitelung auch auf das Mundbild achten. Außerdem leidet die Gesamtverständlichkeit, wenn Bild/Ton und Untertitel nicht synchron sind.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn auf der Webseite aufgezeichnete Videos mit synchroner Bild- und Tonspur sowie zuschaltbare Untertitel (closed captions) vorhanden sind.

=== 2. Prüfung

==== 2.1 Prüfung von Untertiteln eines aufgezeichneten Videos:

. Das Video in dem auf der Webseite eingebundenen Player abspielen.
. Prüfen, ob die Untertitel synchron zum Ton angezeigt werden.
. Werden Untertitel nicht synchron angezeigt, kann das an den technischen Möglichkeiten des Players oder an fehlerhaften Zeitstempel in der Untertitel-Datei liegen.
. Um festzustellen, ob die Ursache beim Player liegt oder an der Untertitel-Datei, können die Zeitstempel der Untertitel-Datei stichprobenartig geprüft werden. 
** Dazu im Inspektor des Browsers das `track`-Element suchen. Die Untertitel-Datei ist als .vtt oder .srt-Datei über das `track`-Element eingebunden. 
** Mit der Maus über den Dateipfad fahren. Mit der rechten Maustaste das Kontextmenü öffenen und mit Hilfe der Funktion "Link in neuem Tab anzeigen" die Untertitel anzeigen.
** Alternativ den Pfad kopieren. Den Pfad im Browser hinter dem / der Top-Level-Domain eingeben.
. Prüfen, ob die Zeitstempel korrekt sind.
. Wenn die Zeitcodierung in der Track-Datei Fehler aufweist, ist davon auszugehen, dass der Fehler nicht beim Player liegt. Dieser Prüfschritt ist erfüllt. 

=== 3. Hinweise

Wenn Fehler in der Zeitcodierung der Track-Datei gefunden werden, ist davon auszuegehen, dass der Fehler nicht beim Player liegt. Es ist es jedoch nicht ganz auszuschließen, dass eine nicht vorhandene Synchronität an der Untertitel-Datei _und_ am Player liegt.

Es ist sinnvoll, stichprobenartig zu prüfen, ob es im Webangebot Videos gibt, bei denen die Untertitel synchron zum Ton dargestellt werden. Wenn dies der Fall ist, ist das ein Hinweis, dass der Player Untertitel prinzipiell korrekt darstellt. Der Prüfschritt ist damit erfüllt, Probleme mit der Synchronität sind dann höchstwahrscheinlich bei den Inhalten zu suchen und nicht im eingebundenen Player.

Hinweise zu diesem Prüfschritt können Sie auf GitHub https://github.com/BIK-BITV/BIK-Web-Test/issues[in einem Issue hinterlassen].

=== 4. Bewertungen

==== Nicht erfüllt:

* Bild/Ton und Untertitel sind nicht synchron. 

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten

Inhalte, Qualität und Angemessenheit der Untertitel werden in Prüfschritt
ifdef::env_embedded[9.1.2.2 "Aufgezeichnete Videos mit Untertiteln"]
ifndef::env_embedded[]
<<9.1.2.2 Aufgezeichnete Videos mit Untertiteln.adoc#,9.1.2.2 Aufgezeichnete Videos mit Untertiteln>>
endif::env_embedded[]
geprüft.
In diesem Prüfschritt wird geprüft, ob der eingebundene Player grundsätzlich in der Lage ist, Videos mit Untertiteln synchron darzustellen. 

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

7.1.2 Captioning synchronization

== Quellen

[.BLOCK_LANG_EN]
=== 7.1.2 Captioning synchronization

[.BLOCK_LANG_EN]
--
Where ICT displays captions, the mechanism to display captions shall preserve
synchronization between the audio and the corresponding captions as follows: 

* Captions in recorded material:
  within 100 ms of the time stamp of the caption 
* Live captions:
  within 100 ms of the availability of the caption to the player.
--

(Aus EN 301 549 V3.1.1 Abschnitt 7.1.2 "Captioning synchronization")
