= Prüfschritt 7.2.1 Wiedergabe von Audiodeskription
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn Videos mit synchroner Bild- und Tonspur vorhanden sind 
(und Informationen über das Bildgeschehen für das Verständnis erforderlich sind), 
ist ein Mechanismus für die Auswahl und Wiedergabe der verfügbaren Audiodeskription 
vorhanden.

Audiodeskription kann alternativ auch aus einer von mehrere Audiospuren ausgewählt 
und abgespielt werden. 

== Warum wird das geprüft?
Werden Inhalte eines Videos nur über Bilder vermittelt, sind Beschreibungen der Bildsequenzen 
für blinde Menschen notwendig. Nur dann ist das Video für sie verständlich. Man setzt dafür 
das Verfahren der Audiodeskription ein.

Damit Nutzende Audiodeskription ein- und ausschalten können, muss der eingesetzte Player ein 
entsprechendes AD-Bedienelement oder die Möglichkeit, eine Tonspur mit Audiodeskription in den 
Spracheinstellungen zu aktivieren, anbieten.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn auf der Webseite ein Videoplayer eingebunden ist, 
der aufgezeichnete Videos mit synchroner Bild- und Tonspur abspielt und die Videos Audiodeskription benötigen.

=== 2. Prüfung

. Das Video wird im auf der Website eingebundenen Player abgespielt.
. Prüfen, ob der Player ein Bedienelement anbietet, dass das Ein- und Ausschalten 
  von Audiodeskription ermöglicht.
. Sollte es keine Schaltfläche für Audiodeskription geben, prüfen, 
  ob aus einer von mehreren Tonspuren Audiodeskription ausgewählt werden kann.
  
=== 3. Hinweise

* Weder das Laden eines zweiten Videos mit Audiodeskription (bei Aktivierung eines AD-Buttons), 
noch die Bereitstellung von Audiodeskription mit Hilfe eines zweiten Videos über einen zweiten 
Player wird negativ bewertet.
* Wenn alle wichtigen Informationen der Bildsequenz bereits über der Audiospur vermittelt werden, ist keine 
Audiodeskription und damit auch kein AD-Button erforderlich.
* Die Anforderung 7.2.1 erlaubt zwar die Auswahl der Audiodeskription aus einer von mehreren Tonspuren. 
Anforderung  7.3.1 verlangt jedoch, dass sich die Bedienelemente zur Aktivierung der Audiodeskription 
auf der gleichen Interaktionsebene wie die Bedienelemente zur Wiedergabekontrolle 
(z.B. Abspielen, Pause, Lautstärke etc.) befinden.
* Wenn 7.3 Bedienelemente für Untertitel und Audiodeskription erfüllt ist, ist 7.2.1 Wiedergabe von 
Audiodeskripiton ebenfalls erfüllt.

=== 4. Bewertung

==== Nicht erfüllt:

Der Videoplayer bietet keine Möglichkeit, Audiodeskription zuzuschalten.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten
Dieser Prüfschritt fordert, dass der Videoplayer Bedienelemente zum Ein- und Ausschalten der 
Audiobeschreibung anbietet. Eine Bereitstellung von Audiodeskription 
soll dadurch während der Wiedergabe möglich sein.
In Prüfschritt 9.1.2.5 Audiodeskription für Videos wird hingegen geprüft, ob für Inhalte eines Videos, 
die nur über Bilder vermittelt werden, eine Audiodeskription vorhanden ist. Es geht dort um die inhaltliche 
Beurteilung.

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1 Annex A 

* In der Tabelle A1 wird auf 7.2.1 UpAudio Description Playback verwiesen.

== Quellen

[.BLOCK_LANG_EN]
=== 7.2.1 Audio description playback

[.BLOCK_LANG_EN]
--
Where ICT displays video with synchronized audio, it shall provide a mechanism
to select and play available audio description to the default audio channel. 

Where video technologies do not have explicit and separate mechanisms for
audio description, an ICT is deemed to satisfy this requirement if the ICT
enables the user to select and play several audio tracks. 

NOTE 1:
In such cases, the video content can include the audio description as one of
the available audio tracks. 

NOTE 2:
Audio descriptions in digital media sometimes include information to allow
descriptions that are longer than the gaps between dialogue.
Support in digital media players for this "extended audio description" feature
is useful, especially for digital media that is viewed personally.
--

(Aus EN 301 549 V3.1.1 Abschnitt 7.2.1 "Audio description playback")
