= Prüfschritt 7.2.2 Synchrone Audiodeskription
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Sind Videos mit synchroner Bild- und Tonspur vorhanden, ist gewährleistet, 
dass der Videoplayer Audiodeskription synchron zu  Bild und Ton wiedergibt. 

== Warum wird das geprüft?
Folgt

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn auf der Webseite Videos mit synchroner 
Bild- und Tonspur sowie Audiodeskription vorhanden sind.

=== 2. Prüfung

. Das Video in dem auf der Webseite eingebundenen Player abspielen.
. Prüfen, ob die Audiodeskription synchron zu Bild und Ton wiedergegeben wird.

=== 3. Hinweise

Hinweise zu diesem Prüfschritt können Sie auf GitHub https://github.com/BIK-BITV/BIK-Web-Test/issues[in einem Issue hinterlassen].

=== 4. Bewertungen
==== Nicht erfüllt:
Der Videoplayer stellt Audiodekription nicht synchron zum Bild und Ton dar.

== Einordnung des Prüfschritts
Die Tabelle A1 verweist auf 7.2.2 Audio description synchronization

=== Abgrenzung zu anderen Prüfschritten

== Quellen

[.BLOCK_LANG_EN]
=== 7.2.2 Audio description synchronization

[.BLOCK_LANG_EN]
Where ICT has a mechanism to play audio description, it shall preserve the
synchronization between the audio/visual content and the corresponding audio
description.

(Aus EN 301 549 V3.1.1 Abschnitt 7.2.2 "Audio description synchronization")
