= Prüfschritt 7.2.2 Synchrone Audiodeskription
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn die Web-App Videos mit Audiodeskription abspielen kann, soll die
Synchronität zwischen Bild und Audiodeskription beim Abspielen erhalten
bleiben.

== Warum wird das geprüft?
Folgt

== Wie wird geprüft?

=== 1 Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Web-App Videos mit Audiodeskription
abspielen kann.

=== 2 Prüfung

Falls die Web-App keine eigenen Inhalte bereithält, muss ggf. eine
Beispiel-Video-Datei mit Audiodeskription in der Web-App geöffnet werden.

. App öffnen
. prüfen, ob Video-Inhalte mit Audiodeskription in der App zu finden sind
. ein Video mit Audiodeskription aufrufen
. prüfen, ob die Audiodeskription synchron zum Bild abgespielt wird

=== 3 Hinweise

=== 4 Bewertungen
==== Nicht erfüllt:
Folgt

== Einordnung des Prüfschritts
Folgt

=== Abgrenzung zu anderen Prüfschritten

== Quellen

[.BLOCK_LANG_EN]
=== 7.2.2 Audio description synchronization

[.BLOCK_LANG_EN]
Where ICT has a mechanism to play audio description, it shall preserve the
synchronization between the audio/visual content and the corresponding audio
description.

(Aus EN 301 549 V3.1.1 Abschnitt 7.2.2 "Audio description synchronization")
