= Prüfschritt 7.2.3 Erhaltung von Audiodeskription
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn das Webangebot Videos mit Audiodeskription überträgt, konvertiert oder aufnimmt, bleibt die Audiodeskription nach dem Vorgang erhalten. Sie ist weiterhin  zuschaltbar und wird synchron zu Bild und Ton dargestellt. Die Prüfschritte 
ifdef::env_embedded[7.2.1 "Wiedergabe von Audiodeskription"]
ifndef::env_embedded[]
  <<7.2.1 Wiedergabe von Audiodeskription.adoc#,7.2.1 Wiedergabe von
  Audiodeskription>>
und 
ifdef::env_embedded[7.2.2 "Synchrone Audiodeskription"]
ifndef::env_embedded[]
  <<7.2.2 Synchrone Audiodeskription.adoc#,7.2.2 Synchrone
  Audiodeskription>> sind weiterhin erfüllt.

== Warum wird das geprüft?

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn das Webangebot Videos mit Audiodeskription übertragen, konvertieren oder aufnehmen kann.

=== 2. Prüfung
Wenn das Webangebot Videos mit Untertiteln konvertiert oder aufnimmt, das Video anschließend in einem konformen Player abspielen:

* Ist Audiodeskription aus der Quelle weiterhin vorhanden?
* Lässt sich Audiodeskription abspielen?
* Ist die Audiodeskription weiterhin synchron zu Bild und Ton?

=== 3. Hinweise
Hinweise zu diesem Prüfschritt können Sie auf GitHub https://github.com/BIK-BITV/BIK-Web-Test/issues[in einem Issue hinterlassen].

=== 4. Bewertungen
==== Nicht erfüllt:

== Einordnung des Prüfschritts
* In dieser Tabelle A1 wird auf 7.2.3 Preservation of audio description verwiesen.

=== Abgrenzung zu anderen Prüfschritten

In diesem Prüfschritt wird geprüft, ob es durch die Übertragung, Konvertierung oder Aufnahme zu Problemen hinsichtlich der Anzeige oder Synchronität von Audiodeskription kommt. In den Prüfschritten 7.2.1 und 7.2.2 geht es hingegen um Videos, die auf der Webseite bereits vorhanden sind. 

== Quellen

[.BLOCK_LANG_EN]
=== 7.2.3 Preservation of audio description

[.BLOCK_LANG_EN]
Where ICT transmits, converts, or records video with synchronized audio, it
shall preserve audio description data such that it can be played in a manner
consistent with clauses 7.2.1 and 7.2.2.

(Aus EN 301 549 V3.1.1 Abschnitt 7.2.3 "Preservation of audio description")
