= Prüfschritt 7.3 Bedienelemente für Untertitel und Audiodeskription
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn ein Videoplayer Video-Inhalte mit zugehörigen Audioinhalten abspielt, 
befinden sich die Bedienelemente zur Aktivierung der Untertitelung und Audiodeskription 
auf der gleichen Interaktionsebene wie die Bedienelemente zur Wiedergabekontrolle 
(z.B. Abspielen, Pause, Lautstärke etc.).

== Warum wird das geprüft?

Videoplayer bieten den Menschen eine Vielzahl von Interaktionsmöglichkeiten. 
Am wichtigsten sind dabei die Bedienelemente zur Wiedergabekontrolle. Sie sind daher prominent auf der obersten Interaktionsebene 
des Players positioniert. Bedienelemente für das Ein- und Ausblenden der Untertitel bzw. 
das Starten und Beenden der Audiodeskription sind für Menschen, die diese Funktion benötigen, 
ebenfalls wichtige Steuerelemente. Sie sollen leicht gefunden werden 
und müssen daher ebenfalls auf der obersten Interaktionsebene positioniert sein.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn auf der Webseite ein Videoplayer eingebunden ist, 
der Video-Inhalte mit zugehörigen Audioinhalten abspielt und wenn Untertitel und / oder 
Audiodeskription für das Verständnis nötig sind.

=== 2. Prüfung

. Das Video mit dem auf der Website eingebundenen Player abspielen.
. Prüfen, ob Bedienelemente zur Anzeige von Untertiteln und / oder Audiodeskription auf 
  gleicher Ebene wie die Bedienelemente zur Wiedergabekontrolle (z.B. Abspielen, Pause, 
  Lautstärke etc.) angeboten werden.

=== 3. Hinweise

Wenn 7.3 Bedienelemente für Untertitel und Audiodeskription erfüllt ist, 
ist 7.1.1 Wiedergabe von Untertiteln und 7.2.1 Wiedergabe von Audiodeskripiton ebenfalls 
erfüllt.

Für Hinweise zu diesem Prüfschritt können Sie auf GitHub
https://github.com/BIK-BITV/BIK-Web-Test/issues[ein Issue anlegen].

=== 4. Bewertung
==== Nicht erfüllt:
Die Bedienelemente zur Aktivierung der Untertitel und Audiodeskription sind nicht auf der 
gleichen Interaktionsebene positioniert wie die Bedienelemente zur Wiedergabekontrolle.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten
Bei diesem Prüfschritt geht es darum, *wo* die Bedienelemente für Untertitel und Audiodeskription 
positioniert sind. In Prüfschritt 7.2.1 Wiedergabe von Audiodeskription geht es darum, dass überhaupt 
entsprechende Bedienelemente vorhanden sind.

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1
User controls for captions and audio description

=== Quellen

[.BLOCK_LANG_EN]
==== 7.3 User controls for captions and audio description

[.BLOCK_LANG_EN]
--
Where ICT primarily displays materials containing video with associated audio
content, user controls to activate subtitling and audio description shall be
provided to the user at the same level of interaction (i.e. the number of
steps to complete the task) as the primary media controls. 

NOTE 1:
Primary media controls are the set of controls that the user most commonly
uses to control media.

NOTE 2:
Products that have a general hardware volume control, such as a telephone, or
a laptop which can be configured to display video through Web-App but which
is not its primary purpose, would not need dedicated hardware controls for
captions and descriptions; however Web-App controls, or hardware controls
mapped through Web-App, would need to be at the same level of interaction. 

NOTE 3:
It is best practice for ICT to include additional controls enabling the user to
select whether captions and audio description are turned on or off by default.
--

(Aus EN 301 549 V3.1.1 Abschnitt 7.3 "User controls for captions and audio
description")
