= Prüfschritt 7.3 Bedienelemente für Untertitel und Audiodeskription
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn ein Videoplayer Video-Inhalte mit zugehörigen Audioinhalten abspielt, 
befinden sich die Bedienelemente zur Aktivierung der Untertitelung und 
Audiodeskription auf der gleichen Interaktionsebene wie die Bedienelemente 
zur Wiedergabekontrolle (z.B. Abspielen, Pause, Lautstärke etc.).

== Warum wird das geprüft?

Videoplayer bieten den Menschen eine Vielzahl von Interaktionsmöglichkeiten. 
Primäre Mediensteuerelemente (die Bedienelemente zur Wiedergabekontrolle) sind 
Steuerelemente, die der Nutzende am häufigsten zur Mediensteuerung verwendet. 
Sie sind daher prominent auf der obersten Interaktionsebene des Players positioniert. 
Bedienelemente für das Ein- und Ausblenden der Untertitel bzw. das Starten und Beenden 
der Audiodeskription sind für Nutzende, die diese Funktion benötigen, ebenfalls wichtige 
Steuerelementen, die viel genutzt und schnell gefunden werden müssen, sie sollten daher 
ebenfalls auf der obersten Interaktionsebene positioniert sein.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn auf der Webseite ein Videoplayer eingebunden ist, 
der Video-Inhalte mit zugehörigen Audioinhalten abspielt und Untertitel und / oder 
Audiodeskription für das Verständnis nötig sind.

=== 2. Prüfung

. Das Video auf der Website eingebundenen Player abspielen.
. Prüfen, ob die Bedienelemente für das Ein- und Ausblenden der Untertitel auf der 
  gleichen Interaktionsebene wie die Bedienelemente zur Wiedergabekontrolle positioniert sind.
. Prüfen, ob die Bedienelemente für die Audiodeskription auf der gleichen Interaktionsebene 
  wie die Bedienelemente zur Wiedergabekontrolle positioniert sind.


=== 3. Hinweise

Nicht negativ bewertet werden sollte ein Bedienelement, dass durch das Einblenden eines 
Popups die Einstellungen für Audiodeskription und Untertitel ermöglicht.

=== 4. Bewertung

==== Nicht erfüllt

Die Bedienelemente zur Aktivierung der Untertitel und Audiodeskription sind nicht 
auf der gleichen Interaktionsebene wie die Bedienelemente zur Wiedergabekontrolle.

== Einordnung des Prüfschritts

Bei diesem Prüfschritt geht es darum, wo die Bedienelemente für Untertitel und 
Audiodeskription positioniert sind. In Prüfschritt 7.2.1 Wiedergabe von Audiodeskription 
geht es darum, dass überhaupt entsprechende Bedienelemente vorhanden sind, die die 
entsprechende Funktionalität ermöglichen.

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1 Annex A 

In der Tabelle A1 wird auf 7.3 "User controls for captions and audio description" verwiesen.

== Quellen

[.BLOCK_LANG_EN]
=== 7.3 User controls for captions and audio description

[.BLOCK_LANG_EN]
--
Where ICT primarily displays materials containing video with associated audio
content, user controls to activate subtitling and audio description shall be
provided to the user at the same level of interaction (i.e. the number of
steps to complete the task) as the primary media controls. 

NOTE 1:
Primary media controls are the set of controls that the user most commonly
uses to control media.

NOTE 2:
Products that have a general hardware volume control, such as a telephone, or
a laptop which can be configured to display video through Web-App but which
is not its primary purpose, would not need dedicated hardware controls for
captions and descriptions; however Web-App controls, or hardware controls
mapped through Web-App, would need to be at the same level of interaction. 

NOTE 3:
It is best practice for ICT to include additional controls enabling the user to
select whether captions and audio description are turned on or off by default.
--

(Aus EN 301 549 V3.1.1 Abschnitt 7.3 "User controls for captions and audio
description")
