= Prüfschritt 9.1.1.1a Alternativtexte für Bedienelemente9.1.1.1b Alternativtexte für Grafiken und Objekte9.1.1.1c Leere alt-Attribute für Layoutgrafiken9.1.1.1d Alternativen für CAPTCHAs9.1.2.1a Alternativen für Audiodateien und stumme Videos9.1.2.2a Aufgezeichnete Videos mit Untertiteln9.1.2.3a Audiodeskription oder Volltext-Alternative für Videos9.1.2.4a Videos (live) mit Untertiteln9.1.2.5a Audiodeskription für Videos9.1.3.1a HTML-Strukturelemente für Überschriften9.1.3.1b HTML-Strukturelemente für Listen9.1.3.1c HTML-Strukturelemente für Zitate9.1.3.1d Inhalt geglieder9.1.3.1e Datentabellen richtig aufgebaut9.1.3.1f Zuordnung von Tabellenzellen
include::include/author.adoc[]
include::include/attributes.adoc[]

[[multileiste]]
link:/index.php?a=eb&iid=78[die bisherigen Bewertungen für dieses Prüfschritt]

[.stopFloat]

== Technische Angaben

Version

link:/index.php?a=di&iid=34[bis 10.07.2017] | Aktuell

BITV-Bedingung

1.3.1 Informationen und Beziehungen

WCAG-Erfolgskriterium

1.3.1 Info und Beziehungen

Bewertungsalternativen

ja / eher erfüllt / teilweise erfüllt / eher nicht erfüllt / nein / nicht anwendbar

Bezieht sich auf

einzelne Webseite

Prüfschritt erfüllt

In komplexen Datentabellen ist der Bezug von Überschriften und Inhalten (über `scope` oder über `id` und `headers`) definiert, Zuordnungen von Überschriften in einfachen Datentabellen sind korrekt.

Prüfschritt nicht anwendbar

Komplexe Datentabellen sind nicht vorhanden, in einfachen Datentabellen sind Überschriften nicht zugeordnet.

== Was wird geprüft?

In komplexen Datentabellen soll der Bezug von Überschriften und Inhalten (über `scope` oder über `id` und `headers`) definiert sein, ausdrückliche Zuordnungen von Überschriften und Inhalten in einfachen Datentabellen sollen korrekt sein.

== Warum wird das geprüft?

Bei komplexen Tabellen können Screenreader aus dem Tabellengerüst allein nicht schließen, welche Bezüge es zwischen Daten- und Überschriftenzellen gibtDeshalb müssen diese Verknüpfungen mithilfe der in HTML zur Verfügung stehenden Attribute ausdrücklich definiert werden.

In der Praxis sind manchmal auch einfache Datentabellen mit `headers`- und `id`-Attributen ausgezeichnetScreenreader richten sich dann nicht nach allgemeinen Regeln, sondern nach der vorliegenden AuszeichnungDeshalb muss die Auszeichnung auch dann richtig sein, wenn sie eigentlich nicht nötig wäreDenn bei falscher direkter Zuordnung von Datenzellen werden die Überschriften nicht oder fehlerhaft ausgegeben.

Hinweis: +
Für Benutzer von Screenreadern sind komplexe Tabellen schwerer zu erfassen als einfache, selbst bei perfekter AuszeichnungZu empfehlen ist also die Vermeidung von Tabellen mit mehreren logischen Ebenen (siehe link:#log[Frage zu Tabellen mit mehreren logischen Ebenen])In vielen Fällen können komplexe Tabellen geteilt und durch mehrere einfache Tabellen ersetzt werdenDie beste Bewertung für dieses Prüfschritt ist deshalb immer "nicht anwendbar".

== Wie wird geprüft?

=== 1Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar,

wenn eine Datentabelle komplex ist, also mehrstufige Zeilen- oder Spaltenüberschriften vorhanden sind oder
wenn in einer einfachen Datentabelle Zellen ausdrücklich (per `headers` und `id`) bestimmten Überschriften zugeordnet sind (auch wenn diese Zuordnung eigentlich nicht erforderlich wäre).

Einfache Datentabellen haben im Unterschied zu komplexen Datentabellen nur jeweils eine Zeile oder Spalte für ÜberschriftenBei solchen Tabellen ist es eigentlich nicht erforderlich, die Zellen "ihren" Überschriften zuzuordnen.

=== 2Prüfung

Seite im Firefox laden.
Das https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste.html[Tables bookmarklet] aufrufenTabellen-Auszeichnungen werden jetzt angezeigt.
Prüfen, ob der Geltungsbereich der Überschriften korrekt über das `scope`-Attribut definiert ist oder die einzelnen Zellen mithilfe von `headers`- und `id`-Attributen korrekt ihren Überschriften zugeordnet sind.

=== 3Hinweis

Grundlage der Prüfung ist die vorangegangene Überprüfung des Aufbaus der Datentabelle und der Auszeichnung von Überschriften in Prüfschritt link:/index.php?a=di&iid=77&s=n[1.3.1e] "Datentabellen richtig aufgebaut"Dieser Prüfschritt 1.3.1f beschränkt sich auf die Vollständigkeit und die formale Korrektheit der Zuordnung von Inhalten zu Überschriften.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131#adaptable[Guideline 1.3 Adaptable: Create content that can be presented in different ways (for example simpler layout) without losing information or structure]

==== Success criterion

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131#info-and-relationships[1.3.1 Info and Relationships] (Level A)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G115.html[G115: Using semantic elements to mark up structure]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G140.html[G140: Separating information and structure from presentation to enable different presentations]

===== HTML Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/html/H43.html[H43 Using `id` and `headers` attributes to associate data cells with header cells in data tables]
* https://www.w3.org/WAI/WCAG21/Techniques/html/H63.html[H63 Using the `scope` attribute to associate header cells and data cells in data tables]

===== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F90.html[F90: Failure of Success Criterion 1.3.1 for incorrectly associating table headers and content via the `headers` and `id` attributes]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F92.html[F92: Failure of Success Criterion 1.3.1 due to the use of role presentation on content which conveys semantic information]

== Quellen

=== [#log]Was sind Tabellen mit mehreren logischen Ebenen?

____
(...) the average table of data with a row of headers across the top, and a column of headers down one side or the other (or sometimes the same headers reproduced at either side, to make life easier) has only one logical level of headers.

Tables with two or more levels are those where the row of headers "closest to the content" itself has headersA trivial example would be months, which have season headers (...)
____

Quelle: http://lists.w3.org/Archives/Public/wai-wcag-editor/2000OctDec/0155.html

=== Technique H63: Using the scope attribute to associate header cells and data cells in data tables

____
"At the current time, those who want to ensure consistent support across Assistive Technologies for tables where the headers are not in the first row/column may want to use the technique for complex tables H43: Using id and headers attributes to associate data cells with header cells in data tablesFor simple tables that have headers in the first column or row we recommend the use of the th and td elements."
____

Quelle: https://www.w3.org/WAI/WCAG21/Techniques/html/H63.html

=== Technique H43: Using id and headers attributes to associate data cells with header cells in data tables

____
"The objective of this technique is to associate each data cell (in a data table) with the appropriate headersThis technique adds a headers attribute to each data cell (td element)It also adds an id attribute to any cell used as a header for other cellsThe headers attribute of a cell contains a list of the id attributes of the associated header cellsIf there is more than one id, they are separated by spaces.

This technique is used when data cells are associated with more than one row and/or one column headerThis allows screen readers to speak the headers associated with each data cell when the relationships are too complex to be identified using the th element alone or the th element with the scope attributeUsing this technique also makes these complex relationships perceivable when the presentation format changes.

This technique is not recommended for layout tables since its use implies a relationship between cells that is not meaningful when tables are used for layout."
____

Quelle: https://www.w3.org/WAI/WCAG21/Techniques/html/H43.html

=== Weiterführende Links:

* pro-barrierefreiheit: http://www.pro-barrierefreiheit.de/entwickler/tabellen/strukturierung/[Strukturierung von Tabelleninhalten]
* Roger Hudson, Web Usability: http://www.usability.com.au/resources/tables.cfm[Accessible Data Tables]
