= Prüfschritt 9.1.1.1a Alternativtexte für Bedienelemente9.1.1.1b Alternativtexte für Grafiken und Objekte9.1.1.1c Leere alt-Attribute für Layoutgrafiken9.1.1.1d Alternativen für CAPTCHAs9.1.2.1a Alternativen für Audiodateien und stumme Videos9.1.2.2a Aufgezeichnete Videos mit Untertiteln9.1.2.3a Audiodeskription oder Volltext-Alternative für Videos9.1.2.4a Videos (live) mit Untertiteln9.1.2.5a Audiodeskription für Videos9.1.3.1a HTML-Strukturelemente für Überschriften9.1.3.1b HTML-Strukturelemente für Listen9.1.3.1c HTML-Strukturelemente für Zitate9.1.3.1d Inhalt geglieder9.1.3.1e Datentabellen richtig aufgebaut9.1.3.1f Zuordnung von Tabellenzellen9.1.3.1g Kein Strukturmarkup für Layouttabellen9.1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar9.1.3.2a Sinnvolle Reihenfolge9.1.3.3a Ohne Bezug auf sensorische Merkmale nutzbar9.1.3.4a Keine Beschränkung der Bildschirmausrichtung
include::include/author.adoc[]
include::include/attributes.adoc[]

[[multileiste]]
link:/index.php?a=eb&iid=118[die bisherigen Bewertungen für dieses Prüfschritt]

[.stopFloat]

== Technische Angaben

Version

Aktuell

BITV-Bedingung

1.3.4 Ausrichtung

Bewertungsalternativen

ja / eher erfüllt / teilweise erfüllt / eher nicht erfüllt / nein

Bezieht sich auf

einzelne Webseite

Prüfschritt erfüllt

Inhalte sind hinsichtlich Ansicht und Bedienung nicht auf eine einzige Ausrichtung (Hoch- oder Querformat) beschränkt, es sei denn, eine bestimmte Ausrichtung ist unerlässlich.

== Was wird geprüft?

Webinhalte sollen sich an die nutzergewählte Ausrichtung von Ausgabegeräten anpassenSie sollten sowohl im Hochformat als auch im Querformat dargestellt werden und nutzbar sein, es sei denn, eine bestimmte Ausrichtung des Inhalts ist unerlässlich.

Beispiele für Inhalte, bei denen die Ausrichtung unerlässlich sein können, sind ein Bankcheck, eine online-Klavier-Tastatur, Präsentationsfolien für einen Projektor oder Bildschirm, oder Inhalte eine Virtual-Reality (VR) Anwendung bei der es keine binäre Ausrichting gibt (also nicht: entweder Hoch- oder Querformat).

Es wird nicht verlangt, dass in beiden Ausrichtungen Inhalte und Funktionen in der gleichen Form angeboten werdenSo können in einer anderen Orientierung Inhalte ggferst nach Aktivierung von Ausklapbereichen oder mittels Links auf andere Seiten angeboten werden.

== Warum wird das geprüft?

Für Menschen mit Behinderung ist es oft besonders wichtig, ein Ausgabegerät (z.Bein Smartphone) in einer bestimmten Ausrichtung nutzen könnenWenn beispielsweise Text stark vergrößert wird, bietet die Verwendung des Querformats oft ein besseres Leseerlebnis, da mehr Wörter in eine Zeile passen.

Außerdem haben einige Benutzer ihre Geräte in einer festen Ausrichtung montiert (z.Bam Arm eines Elektrorollstuhls)Daher sollten Websites und Anwendungen die Darstellung vion Inhalten nicht auf eine Ausrichtung einschränken.

== Wie wird geprüft?

=== 1Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

=== 2Prüfung

Ein aktuelles Android-Smartphone oder iPhone mit ca4-6 Zoll Bildschirmdiagonale zur Prüfung verwenden.
Sicherstellen, dass auf dem mobilen Prüfgerät die Ausrichtung nicht hardware- oder betriebssystemseitig festgestellt bzwarretiert ist.
Der zu prüfende Inhalt wird im Browser Chrome (Android) oder Safari (iOS) erst in der einen Ausrichtung neu geladen.
Prüfen, ob Inhalte dargestellt werden und nutzbar sind.
Der zu prüfende Inhalt wird in der anderen Ausrichtung neu geladen.
Prüfen, ob Inhalte dargestellt werden und nutzbar sindTreten Beschränkungen beim Wechsel der Ausrichtung auf, etwa Meldungen, welche zur Nutzung der jeweils anderen Ausrichtung auffordern?
Wenn nur eine Ausrichtung unterstützt wird und in der anderen Ausrichtung entweder der Inhalt nicht erscheint, um 90 Grad gedreht erscheint, oder aber eine Meldung ausgegeben wird, dass die andere Ausrichtung zu nutzen ist: Prüfen, ob die unterstützte Ausrichtung unerlässlich ist, die Inhalte in der nicht unterstützten Ausrichtung also nicht oder nur schlecht dargestellt werden könnten.

=== 3Hinweise

Es wird nicht verlangt, dass eine Änderung der Ausrichtung die Inhalte dynamisch anpasst (obwohl dies wünschenswert und bei responsiven Angeboten meist auch der Fall ist)Der Inhalt muss also in beiden Ausrichtungen jeweils neu geladen werden.

=== 4Bewertung

==== Prüfschritt erfüllt:

* Beide Ausrichtungen werden unterstützt.
* Wenn nur eine Ausrichtung angeboten wird, ist sie für den Inhalt unerlässlich.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten

Gegenstand dieses Prüfschritts ist die Anpassbarkeit der Bildschirm-Ausrichtung, nicht jedoch Änderungen hinsichtlich der Verfügbarkeit von Inhalten oder Funktionalität, die durch den Wechsel hervorgerufen werdenDies ist Gegenstand von Prüfschritt link:/index.php?a=di&iid=87&s=n[1.4.4a] "Text auf 200% vergrößerbar" und link:/index.php?a=di&iid=108&s=n[1.4.10a] "Inhalte brechen um".

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#adaptable[Guideline 1.3 Adaptable: Create content that can be presented in different ways (for example simpler layout) without losing information or structure.]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#orientation[1.3.4 Orientation] (Level AA)

==== Sufficient Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G214[G214: Using a control to allow access to content in different orientations which is otherwise restricted]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F97.html[F97: Failure due to locking the orientation to landscape or portrait view]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F100[F100: Failure of Success Criterion 1.3.4 due to showing a message asking to reorient device]

== Quellen

https://www.w3.org/WAI/WCAG21/Understanding/orientation.html[Understanding Success Criterion 1.3.4: Orientation] (zur Zeit nur auf Englisch verfügbar)
