= Prüfschritt 9.1.3.1b HTML-Strukturelemente für Listen
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Zur Auszeichnung von Listen auf der Seite sollen HTML-Strukturelemente für
Listen (`ul`, `ol` und so weiter) genutzt werden.

== Warum wird das geprüft?

Die Verwendung der HTML-Strukturelemente stellt sicher, dass der Aufbau einer
Seite unabhängig von der Präsentation auf einer abstrakten Ebene festgelegt
und zugänglich ist.

Benutzer, die mit der vorgegebenen visuellen Präsentation der Elemente auf der
Seite nichts anfangen können, finden sich dann trotzdem zurecht oder sie
können eine eigene, besser passende Präsentation anwenden.

Mögliche Anwendungen der Strukturelemente für Listen:

* Listen oder Listeneinträge überspringen (Screenreader-Nutzer)
* Listen können hierarchische Strukturen angemessen abbilden

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Seite Elemente enthält, die von ihrem
Erscheinungsbild oder ihrer Funktion her Listen sind.
Das ist bei informationsorientierten Seiten häufig der Fall.

Da auch die missbräuchliche Verwendung der HTML-Elemente für Listen geprüft
wird, ist der Prüfschritt darüber hinaus immer anwendbar, wenn die Seite
Elemente enthält, die als Listen ausgezeichnet worden sind.

=== 2. Prüfung

* Seite im Firefox aufrufen.
* Lists Bookmarklet aufrufen.
Listenauszeichnungen, soweit vorhanden, werden nun dargestellt.
* Prüfen, ob alle Listen inklusive der Menüs mit den vorgesehenen
  HTML-Strukturelementen für Listen ausgezeichnet sind (``ul``, ``ol``, ``dl``).
* Prüfen, ob Listen-Markup für Elemente verwendet wird, die nicht Listen sind.

=== 3. Hinweise

Es soll nicht beurteilt werden, ob auf der Seite enthaltene Texte vielleicht besser in Listenform dargestellt werden sollten.
Es soll nur geprüft werden, ob vorhandene, erkennbare Listen auch entsprechend ausgezeichnet sind.

Listen erkennt man normalerweise an ihrer Darstellung auf dem Bildschirm.
Sie heben sich deutlich von normalen Textabschnitten ab, oft sind sie
eingerückt, meist sind den Listeneinträgen Aufzählungszeichen oder Zahlen
vorangestellt.

Menüs listen Auswahloptionen auf und sind deshalb von ihrer Aufgabe her immer
Listen, egal wie sie gestaltet sind.
Sie sollten deshalb auch als Listen ausgezeichnet werden.

Definitionslisten dienen hauptsächlich zur Auszeichnung von Glossaren.
Ihr Einsatz für andere gemeinhin übliche paarige Informationen, 
etwa Bild und Bildtext, wird akzeptiert.

Es gibt einige Ausnahmen, bei denen eine Auszeichnung als Liste nicht
gefordert ist:

* Die "Sie-sind-hier"-Navigation am Seitenanfang (auch breadcrumb trail oder Krümelpfad)
* Die horizontale Seitenauswahl (Blättermenü) am Kopf- und Fußende, etwa bei mehrseitigen Artikeln
* Auswahlleisten mit seriellen Einträgen, etwa alphabetische Einträge (A-Z)
  bei Glossaren, oder eine Auswahlleiste mit Jahreszahlen
* Gruppen von verschiedenartigen Links am Seitenende mit drei oder weniger
  Elementen (etwa: "Copyright-Notiz" und "Impressum")

=== 4. Bewertung

==== Erfüllt

* Alle Listen inklusive der Menüs sind mit den vorgesehenen
  HTML-Strukturelementen für Listen ausgezeichnet.

==== Nicht voll erfüllt

* Menüs sind nicht mit geeigneten HTML-Strukturelementen ausgezeichnet.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guidelines

* https://www.w3.org/TR/WCAG21/#adaptable[
  Guideline 1.3 Adaptable: Create content that can be presented in different
  ways (for example simpler layout) without losing information or structure]
* https://www.w3.org/TR/WCAG21/#navigable[
  Guideline 2.4 Navigable: Provide ways to help users navigate, find content,
  and determine where they are]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#info-and-relationships[
  1.3.1 Info and Relationships] (Level A)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G115.html[
  G115: Using semantic elements to mark up structure]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G140.html[
  G140: Separating information and structure from presentation to enable
  different presentations]

===== HTML Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/html/H48.html[
  H48: Using ol, ul and dl for lists]
* https://www.w3.org/WAI/WCAG21/Techniques/html/H97.html[
  H97: Grouping related links using the nav element]

===== Client-side Scripting Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR28.html[
  SCR28: Using an expandable and collapsible menu to bypass block of content]

===== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F2.html[
  F2: Failure of Success Criterion 1.3.1 due to using changes in text
  presentation to convey information without using the appropriate markup or
  text]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F43.html[
  F43: Failure of Success Criterion 1.3.1 due to using structural markup in a
  way that does not represent relationships in the content]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F92.html[
  F92: Failure of Success Criterion 1.3.1 due to the use of role presentation
  on content which conveys semantic information]
