= Prüfschritt 9.1.1.1a Alternativtexte für Bedienelemente9.1.1.1b Alternativtexte für Grafiken und Objekte9.1.1.1c Leere alt-Attribute für Layoutgrafiken9.1.1.1d Alternativen für CAPTCHAs9.1.2.1a Alternativen für Audiodateien und stumme Videos9.1.2.2a Aufgezeichnete Videos mit Untertiteln9.1.2.3a Audiodeskription oder Volltext-Alternative für Videos9.1.2.4a Videos (live) mit Untertiteln
include::include/author.adoc[]
include::include/attributes.adoc[]

[[multileiste]]
link:/index.php?a=eb&iid=70[die bisherigen Bewertungen für dieses Prüfschritt]

[.stopFloat]

== Technische Angaben

Version

Aktuell

BITV-Bedingung

1.2.4 Live-Untertitel

WCAG-Erfolgskriterium

1.2.4 Untertitel (Live)

Bewertungsalternativen

ja / eher erfüllt / teilweise erfüllt / eher nicht erfüllt / nein / nicht anwendbar

Bezieht sich auf

einzelne Webseite

Prüfschritt erfüllt

Live-Übertragungen haben synchrone Untertitel.

Prüfschritt nicht anwendbar

Es sind keine Live-Übertragungen vorhanden.

== Was wird geprüft?

Wenn die Tonspur einer Live-Übertragung Informationen enthält, müssen Untertitel als Alternative bereitgestellt werden.

== Warum wird das geprüft?

Filme sind in der Regel ohne den Ton nicht zu verstehenDies gilt auch für Live-ÜbertragungenDaher muss für Menschen mit Hörbehinderung der Inhalt der Tonspur durch Untertitel bereitgestellt werden+
Untertitel können auch für andere Nutzer hilfreich sein, zum Beispiel für Personen, die mit der Sprache des Films nicht vertraut sind.

== Wie wird geprüft?

=== 1Anwendbarkeit des Prüfschritts

* Der Prüfschritt ist anwendbar, wenn Live-Übertragungen mit synchroner Bild- und Tonspur vorhanden sind.
* Live-Videos ohne Tonspur brauchen keine Untertitel, der Prüfschritt ist für sie nicht anwendbarAlternativen für Videos ohne Tonspur werden in Prüfschritt link:/index.php?a=di&iid=16&s=n[1.2.1a] "Audiodateien und stumme Videodateien mit Textalternativen" geprüft.

=== [#G87][#G93]2Prüfung auf Untertitel

Das Video wird im auf der Website eingebundenen Player oder in einem externen, vom Format abhängigen Video-Player abgespielt.
Es wird geprüft, ob parallel zum Video Untertitel automatisch angezeigt werden oder zugeschaltet werden können.
[#F8][#F75]Wenn Untertitel vorhanden sind, wird eine kurze Sequenz des Videos mit Untertiteln angesehen, um stichprobenartig festzustellen, ob die Untertitel dem hörbaren Inhalt entsprechenDies betrifft auch akustische Ereignisse, die für das Verständnis des Inhalts wichtig sind.

=== 3Bewertung

==== Erfüllt:

Live-Übertragungen mit synchroner Bild- und Tonspur haben erweiterte Untertitel, die alle Informationen der Tonspur enthaltenDazu gehört gegebenenfalls die Anzeige, wer spricht, und bedeutungstragende Tonereignisse (etwa informationstragende Geräusche, Lachen, oder Applaus).

==== Nicht erfüllt:

Live-Übertragungen sind ohne Untertitel.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten

==== Aufgezeichnete Videos

Die Untertitelung von aufgezeichneten Videos wird in Prüfschritt link:/index.php?a=di&iid=67&s=n[1.2.2a] "Aufgezeichnete Videos mit Untertiteln" geprüft.

==== Stumme Videodateien

Bei diesem Prüfschritt geht es um die synchrone Vermittlung von visuellen und akustischen InformationenDer Prüfschritt ist relevant, wenn für das Verständnis eines Elements die parallele Wahrnehmung von Bild und Ton erforderlich istEin einfacher Alternativtext oder eine zusammenfassende Beschreibung ist dann nicht (mehr) ausreichendStumme Video-Dateien werden im Prüfschritt Prüfschritt link:/index.php?a=di&iid=16&s=n[1.2.1a] "Alternativen für Audiodateien und stumme Videos" geprüft.

==== Alternativtexte für Objekte

Alternativtexte für Multimedia-Objekte, etwa Video- oder Audio-Dateien oder Applets, werden in Prüfschritt link:/index.php?a=di&iid=65&s=n[1.1.1b] "Alternativtexte für Grafiken und Objekte" geprüft.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#time-based-media[Guideline 1.2 Time-based Media: Provide alternatives for time-based media]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#captions-live[1.2.4 Captions (Live)] (Level AA)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G9[G9: Creating captions for live synchronized media]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G87[G87: Providing closed captions]
* http://www.w3.org/TR/WCAG20-TECHS/G93[G93: Providing open (always visible) captions]

===== SMIL Techniques

* http://www.w3.org/TR/WCAG20-TECHS/SM11.html[SM11: Providing captions through synchronized text streams in SMIL 1.0]
* http://www.w3.org/TR/WCAG20-TECHS/SM12.html[SM12: Providing captions through synchronized text streams in SMIL 2.0]
