= Prüfschritt 9.1.2.2 Aufgezeichnete Videos mit Untertiteln
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn die Tonspur eines aufgezeichneten Videos Informationen enthält, müssen Untertitel als Alternative bereitgestellt werden.

== Warum wird das geprüft?

Filme sind in der Regel ohne den Ton nicht zu verstehen. Daher muss für Menschen mit Hörbehinderung der Inhalt der Tonspur durch Untertitel bereitgestellt werden.

Untertitel können auch für andere Nutzende hilfreich sein, zum Beispiel für Personen, die mit der Sprache des Films nicht vertraut sind.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

* Der Prüfschritt ist anwendbar, wenn aufgezeichnete Videos mit synchroner
  Bild- und Tonspur vorhanden sind.
* Aufgezeichnete Videos ohne Tonspur brauchen keine Untertitel, der
  Prüfschritt ist für sie nicht anwendbar.
  Alternativen für Videos ohne Tonspur werden in Prüfschritt
ifdef::env_embedded[9.1.2.1 "Alternativen für Audiodateien und stumme Videos"]
ifndef::env_embedded[]
  <<9.1.2.1 Alternativen für Audiodateien und stumme Videos.adoc#,9.1.2.1
  Alternativen für Audiodateien und stumme Videos>>
endif::env_embedded[]
  geprüft.

=== 2. Prüfung

==== 2.1 Prüfung auf Untertitel

. Das Video im auf der Website eingebundenen Player abspielen.
. Prüfen, ob parallel zum Video Untertitel automatisch angezeigt werden oder zugeschaltet werden können.
. Wenn Untertitel vorhanden sind, eine kurze Sequenz des Videos mit Untertiteln ansehen, um stichprobenartig festzustellen, ob die Untertitel dem hörbaren Inhalt entsprechen.
  Dies betrifft auch akustische Ereignisse, die für das Verständnis des Inhalts wichtig sind.

==== 2.2 Prüfung von Videos als Medienalternative

. Falls keine Untertitel vorhanden sind: Prüfen, ob das Video als ergänzende Medienalternative zu einem Text angeboten wird.
. Prüfen, ob die Beschriftung des Videos klar auf eine dazugehörige Textversion verweist und diese entweder in unmittelbarer Nachbarschaft verfügbar ist oder durch einen aussagekräftigen Link erreichbar ist.
. Prüfen, ob das Video alle wesentlichen Inhalte des Textes über den Ton transportiert.
  . Wenn das Video wichtige über den Textinhalt hinausgehende Informationen trägt, ist das Video keine Medienalternative, es braucht Untertitel und muss auch auf Audiodeskription geprüft werden (siehe auch Prüfschritt
ifdef::env_embedded[9.1.2.3 "Audiodeskription oder Volltext-Alternative für Videos").]
ifndef::env_embedded[]
  <<9.1.2.3 Audiodeskription oder Volltext-Alternative für Videos.adoc#,9.1.2.3
  Audiodeskription oder Volltext-Alternative für Videos>>).
endif::env_embedded[]

=== 3. Hinweis

Die Anforderung 9.1.2.3 Audiodeskription oder Volltextalternative ist in den WCAG der Konformitätsstufe A zugeordnet. Auf Konformitätsstufe AA gibt es ein Erfolgskriterium, das die Volltext-Alternative nicht akzeptiert. Der BITV-Test prüft dieses Erfolgskriterium der Stufe AA im Prüfschritt 
ifdef::env_embedded[9.1.2.5 Audiodeskription für Videos]
ifndef::env_embedded[]
  <<9.1.2.5 Audiodeskription für Videos.adoc#,9.1.2.5
  Audiodeskription für Videos>>.
endif::env_embedded[]

Bietet die Website eine Volltextalternative, so ist zwar 9.1.2.3 (A) erfüllt, nicht aber 9.1.2.5 (AA). Da der BITV-Test Konformität auf Stufe AA prüft, wird dann die Seite in der Auswertung des Tests als "nicht konform" bewertet. Eine Audiodeskription ist also für eine konforme Bewertung der Seite im BITV-Test gefordert, sofern der Prüfschritt anwendbar ist.

=== 4. Bewertung

==== Erfüllt

* Aufgezeichnete Videos mit synchroner Bild- und Tonspur haben erweiterte Untertitel, die alle Informationen der Tonspur enthalten.
  Dazu gehören gegebenenfalls die Anzeige, wer spricht, und bedeutungstragende Tonereignisse (etwa informationstragende Geräusche, Lachen, Applaus).

==== Teilweise erfüllt

* Aufgezeichnete Videos mit synchroner Bild- und Tonspur haben keine Untertitel, aber folgende Bedingung ist erfüllt: Es gibt im unmittelbaren Kontext des
  Videos eine vollständige Textalternative (Transkription) oder einen klar bezeichneten Link zu einer vollständigen Textalternative.
* Wenn das Videobild Inhalte hat, die nicht in der Transkription vorkommen oder nicht adäquat darstellbar sind, kommen die Abstufungen der Bewertung von eher nicht erfüllt bis nicht erfüllt in Betracht.

==== Nicht voll erfüllt

* Bei Medienalternativen fehlt die direkte Nachbarschaft oder der klar bezeichnete Link auf das primäre Medium, dass die Medienalternative ersetzt.

==== Nicht erfüllt

* Aufgezeichnete Videos sind ohne Untertitel, eine Textalternative ist ebenfalls nicht vorhanden.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten

==== Live-Videos

Die Untertitelung von Live-Videos wird in Prüfschritt
ifdef::env_embedded[9.1.2.4 "Videos (live) mit Untertiteln"]
ifndef::env_embedded[]
  <<9.1.2.4 Videos (live) mit Untertiteln.adoc#,9.1.2.4 Videos (live) mit
  Untertiteln>>
endif::env_embedded[]
geprüft.

==== Stumme Videodateien

Bei diesem Prüfschritt geht es um die synchrone Vermittlung von visuellen und
akustischen Informationen.
Der Prüfschritt ist relevant, wenn für das Verständnis eines Elements die
parallele Wahrnehmung von Bild und Ton erforderlich ist.
Ein einfacher Alternativtext oder eine zusammenfassende Beschreibung ist dann
nicht (mehr) ausreichend.
Stumme Video-Dateien werden im Prüfschritt
ifdef::env_embedded[9.1.2.1 "Alternativen für Audiodateien und stumme Videos"]
ifndef::env_embedded[]
  <<9.1.2.1 Alternativen für Audiodateien und stumme Videos.adoc#,9.1.2.1
  Alternativen für Audiodateien und stumme Videos>>
endif::env_embedded[]
geprüft.

==== Alternativtexte für Objekte

Alternativtexte für Multimedia-Objekte, etwa Video- oder Audio-Dateien oder
Applets, werden in Prüfschritt
ifdef::env_embedded[9.1.1.1b "Alternativtexte für Grafiken und Objekte"]
ifndef::env_embedded[]
  <<9.1.1.1b Alternativtexte für Grafiken und Objekte.adoc#,9.1.1.1b
  Alternativtexte für Grafiken und Objekte>>
endif::env_embedded[]
geprüft.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#time-based-media[
  Guideline 1.2 Time-based Media: Provide alternatives for time-based media]

==== Success criteria

* https://www.w3.org/TR/WCAG21/#captions-prerecorded[
  1.2.2 Captions (Prerecorded)] (Level A)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G87[
  G87: Providing closed captions]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G93[
  G93: Providing open (always visible) captions]

===== HTML Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/html/H95[
  H95: Using the track element to provide captions]

===== SMIL Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/smil/SM11[
  SM11: Providing captions through synchronized text streams in SMIL 1.0]
* https://www.w3.org/WAI/WCAG21/Techniques/smil/SM12[
  SM12: Providing captions through synchronized text streams in SMIL 2.0]

===== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F8[
  F8: Failure of Success Criterion 1.2.2 due to captions omitting some dialogue or important sound effects]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F74[
  F74: Failure of SC1.2.2 and 1.2.8 due to not labeling a synchronized media
  alternative to text as an alternative]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F75[
  F75: Failure of Success Criterion 1.2.2 by providing synchronized media
  without captions when the synchronized media presents more information than
  is presented on the page]

== Quellen

=== BIK für Alle: Leitfaden barrierefreie Online-Videos

* http://www.bik-fuer-alle.de/fuer-webentwickler-einbindung-in-die-internetseite.html[
  Für Webentwickler: Einbindung in die Internetseite]
  Hinweise zur Wahl von Mediaelementen.
* http://www.bik-fuer-alle.de/untertitelung.html[
  Untertitelung]

=== 'Sprungmarker' zur Barrierefreiheit von Media-Playern

* http://sprungmarker.de/2010/barrierefreiheit_mediaplayer_eine_kurzuebersicht/[
  Barrierefreiheit & Media Player: eine Kurzübersicht - Teil 1]
* http://sprungmarker.de/2010/barrierefreiheit_mediaplayer_captioning/[
  Barrierefreiheit & Media Player: Captioning - Teil 2]

=== Zum Stellenwert von Untertiteln und Gebärdensprache

[.BLOCK_LANG_EN]
____
Sign languages for the Deaf (I know of three used in english-speaking countries
besides "signed english") normally have their own grammar and syntax, their
own ways of adding emphasis or modifying the "tone" of a statement.
They are generally recognised as being languages in their own right, and not
just a pictorial representation of words in a spoken language.
Which brings up all the problems associated with translation - it is not easy,
and automatic translators are still quite primitive.

This explains why sign language users (not all people who are deaf are sign
users) generally prefer sign language interpretation to captioning - with
captions they have to read what amounts to a foreign language, and reading
text is not a skill that is easy to acquire without hearing (since it is based
on an abstract representation of the sound of a language, whereas sign
languages tend to be based on an abstract representation of visual experience
of the world, and since sign languages generally don't have a written form).

So being able to communicate in their own language, and not required to use a
foreign language for chat systems etc is important.

Note that typically this applies to the minority who lose their hearing before
they learn to speak a language - people who are hearing impaired or lose their
hearing later in life, tend to be more (or often only) proficient in a
spoken/written language, so captions are indeed necessary.
____

(http://lists.w3.org/Archives/Public/w3c-wai-ig/2003JulSep/0222.html)

== Fragen zu diesem Prüfschritt

=== Können an Stelle der Untertitel auch Filme mit gebärdensprachlicher Darstellung eingeblendet werden?

Solche Filme sind hilfreich für Personen, die über Gebärdensprache kommunizieren. Meist sind das Personen, die gehörlos geboren oder schon früh ertaubt sind.
Dagegen können Personen, die erst im Alter ertaubt sind, in der Regel nicht über Gebärdensprache kommunizieren. Sie benötigen Untertitel. Gebärdensprachliche Darstellungen sind also kein Ersatz für die Untertitel.
