= Prüfschritt 9.1.4.12 Textabstände anpassbar
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Die Anpassung der Zeilenhöhe auf das 1,5-fache der Textgröße, des Abstands
nach Absätzen auf das 2-fache der Textgröße, von Buchstabenabständen auf das
0,12-fache der Textgröße und von Wortabständen auf das 0,16-fache der
Textgröße führt nicht zu einem Verlust an Inhalten oder Funktionalitäten, zum
Beispiel durch das Abschneiden von Inhalten in Elementen, deren Größe sich bei
Einstellung größerer Textabstände und dadurch erfolgender Textspreizungen oder
Umbrüche nicht dynamisch anpasst.

Anmerkung: Die Anforderung verlangt nicht von Autoren, die genannten Werte bei
Ihren Inhalten umzusetzen, sondern lediglich, dass von Nutzern vorgenommene
Anpassungen nicht zum Abschneiden von Text oder Verlust von Funktionalitäten
führt.

== Warum wird das geprüft?

Menschen mit Sehbehinderungen können die Lesbarkeit von Texten verbessern,
wenn sie über Werkzeuge wie Bookmarklets oder über eigene Stylesheets die
Abstände zwischen Zeilen, Absätzen, Zeichen und Worten anpassen können.
Solche Anpassungen führen dazu, dass Texte ggf. mehr Platz brauchen und
Inhalts-Container dementsprechend dynamisch angelegt sein müssen, um den
längeren Text ohne Verlust zu zeigen.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Seite echten Text enthält (also Text,
der nicht über eine Grafik bereitgestellt wird).

=== 2. Prüfung

. Textabstände mit dem
  https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste/bookmarklets.html[
  Bookmarklet Textabstände] oder mit einer Browser-Erweiterung setzen.
  Die Werte für Zeilenhöhe, Abstand nach Absätzen, Buchstabenabstand und
  Wortabstand werden auf die maximal geforderten Werte gesetzt.
. Prüfen, ob es durch die neuen Werte zum Abschneiden oder Überlappen von Text
  oder den Verlust von Funktionalität kommt.
  
=== 3. Hinweise
* Die Anforderung ist nicht anwendbar ist auf Elemente wie `input type="file"`, auf die CSS-Anpassungen keine Auswirkung haben.

=== 4. Bewertung
==== Erfüllt:
* Nach Anwendung des Bookmarklets sind alle Texte, auch in Ausklappbereichen und Menüs, vollständig lesbar, Sie sind nicht abgeschnitten und überlagern keine anderen Inhalte.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.2

==== Guideline

* https://www.w3.org/TR/WCAG21/#distinguishable[
  Guideline 1.4 Distinguishable: Make it easier for users to see and hear
  content including separating foreground from background]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#text-spacing[
  1.4.12 Text Spacing] (Level AA)

==== Sufficient Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/css/C36.html[
  C36: Allowing for text spacing override]
* https://www.w3.org/WAI/WCAG21/Techniques/css/C35.html[
  C35: Allowing for text spacing without wrapping]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F104[
  F104: Failure of Success Criterion 1.4.12 due to clipped or overlapped
  content when text spacing is adjusted]

== Quellen

* https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html[
  Understanding Success Criterion 1.4.12: Text Spacing]
  (zur Zeit nur auf Englisch verfügbar)
* https://github.com/openstyles/stylus/blob/master/README.md[
  Stylus Browsererweiterung]
* https://www.html5accessibility.com/tests/tsbookmarklet.html[
  Text Spacing Bookmarklet]
