= Prüfschritt 9.1.2.5 Audiodeskription für Videos
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Für informationstragende visuelle Videoinhalte muss eine Audiodeskription
bereitgestellt werden.

== Warum wird das geprüft?

Die Handlung von Videos kann oft auch ohne Bild recht gut verfolgt werden.
Den Sprecher einer Nachrichtensendung muss man zum Beispiel nicht sehen, um zu
verstehen, worum es geht.
Dagegen enthalten Spielfilme und Reportagen oft Passagen, in denen wenig
gesprochen wird und Inhalte über das Bild vermittelt werden.
Damit ein blinder Zuschauer den Film verfolgen kann, müssen ihm solche
Passagen beschrieben werden.
Hierfür wird das Verfahren der Audiodeskription eingesetzt.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

* Der Prüfschritt ist anwendbar, wenn Videos mit synchroner Bild- und Tonspur
  vorhanden sind und Informationen über das Bildgeschehen für das
  Verständnis erforderlich sind.
* Videos brauchen keine Audiodeskription, wenn der Fortgang des Bildgeschehens
  nicht in Worte gefasst werden kann.
  Der Prüfschritt ist dann nicht anwendbar.
* Verzichtbar ist die Audiodeskription, wenn die synchrone Wahrnehmung von
  Bild und Ton für das Verständnis des Videos nicht erforderlich ist oder
  wenn das Video keine Tonspur hat (siehe Prüfschritt
ifdef::env_embedded[9.1.2.1 "Alternativen für Audiodateien und stumme Videos").]
ifndef::env_embedded[]
  <<9.1.2.1 Alternativen für Audiodateien und stumme Videos.adoc#,9.1.2.1
  Alternativen für Audiodateien und stumme Videos>>).
endif::env_embedded[]
* Verzichtbar ist die Audiodeskription auch für Videos, die lediglich als
  Medienalternative zu einem textbasierten Inhalt dienen, das heißt
  ergänzend zu einem Text angeboten werden, um den Textinhalt zusätzlich in
  anderer Form zu vermitteln.
  Dies gilt nur für Videos, die keine über den Textinhalt hinausgehende
  Informationen bieten und die klar als Medienalternative zum Text erkennbar
  sind.
* Gebärdensprachvideos brauchen keine Audiodeskription.

=== 2. Prüfung

Es wird eine Sicht- und Hörprüfung vorgenommen:

. Art der Einbindung feststellen.
  Die Audiodeskription kann auf verschiedenem Wege angeboten werden:
+
* Die Audiodeskription ist bereits in der normalen Tonspur enthalten.
* Eine weitere Version des Videos mit Audiodeskription wird angeboten. Diese Version wird geprüft. Ein funktionierender Link zu dieser Version muss im unmittelbaren Kontext des Videos angeboten werden, ebenso wie ein Zurück-Link (oder das Zurückspringen funktioniert über den Zurück-Button des Browsers).
* Das Video hat eine zuschaltbare Tonspur mit der Audiodeskription. Diese Spur wird zusätzlich geschaltet.

. Das Video wird im auf der Website eingebundenen Player oder in einem externen, vom Format abhängigen Video-Player abgespielt.
. Sind im Video wichtige informationstragende Bildinhalte vorhanden, die nicht in der Tonspur bzw. einer zusätzlichen Audiodeskription vorkommen?

=== 3. Bewertung

==== Teilweise erfüllt

* Die Bildbeschreibungen der Audiodeskription sind nicht aussagekräftig oder nicht vollständig.

==== Nicht erfüllt

* Das Video enthält wichtige informationstragende Bildinhalte, die weder in der Tonspur noch in einer zusätzlichen Audiodeskription vorkommen.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten

In diesem Prüfschritt wird nur geprüft, ob das Video eine Audiodeskription hat.
Eine Volltextalternative wird im Prüfschritt
ifdef::env_embedded[9.1.2.3 "Audiodeskription oder Volltext-Alternative für Videos"]
ifndef::env_embedded[]
  <<9.1.2.3 Audiodeskription oder Volltext-Alternative für Videos.adoc#,9.1.2.3
  Audiodeskription oder Volltext-Alternative für Videos>>
endif::env_embedded[]
bewertet.
Braucht ein Video eine Audiodeskription und sind weder eine Audiodeskription
noch eine Volltextalternative vorhanden, sind sowohl dieser Prüfschritt als auch
Prüfschritt
ifdef::env_embedded[9.1.2.3 "Audiodeskription oder Volltext-Alternative für Videos"]
ifndef::env_embedded[]
  <<9.1.2.3 Audiodeskription oder Volltext-Alternative für Videos.adoc#,9.1.2.3
  Audiodeskription oder Volltext-Alternative für Videos>>
endif::env_embedded[]
nicht bzw. nicht voll erfüllt.

=== Einordnung des Prüfschritts nach WCAG 2.2

==== Guideline

* https://www.w3.org/TR/WCAG22/#time-based-media[
  Guideline 1.2 Time-based Media: Provide alternatives for time-based media]

==== Success criterion

* https://www.w3.org/TR/WCAG22/#audio-description-prerecorded[
  1.2.5 Audio Description (Prerecorded)] (Level AA)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG22/Techniques/general/G78.html[
  G78: Providing a second, user-selectable, audio track that includes audio
  descriptions]
* https://www.w3.org/WAI/WCAG22/Techniques/general/G173.html[
  G173: Providing a version of a movie with audio descriptions]
* https://www.w3.org/WAI/WCAG22/Techniques/general/G203.html[
  G203: Using a static text alternative to describe a talking head video]

===== SMIL Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/smil/SM1.html[
  SM1: Adding extended audio description in SMIL 1.0]
* https://www.w3.org/WAI/WCAG21/Techniques/smil/SM2.html[
  SM2: Adding extended audio description in SMIL 2.0]
* https://www.w3.org/WAI/WCAG21/Techniques/smil/SM6.html[
  SM6: Providing audio description in SMIL 1.0]
* https://www.w3.org/WAI/WCAG21/Techniques/smil/SM7.html[
  SM7: Providing audio description in SMIL 2.0]

== Quellen

=== BIK für Alle: Leitfaden barrierefreie Online-Videos

* http://www.bik-fuer-alle.de/fuer-webentwickler-einbindung-in-die-internetseite.html[
  Für Webentwickler: Einbindung in die Internetseite]
  Hinweise zur Wahl von Mediaelementen.
* http://www.bik-fuer-alle.de/audiodeskription.html[
  Audiodeskription]

=== Blogartikel von 'Sprungmarker' zur Barrierefreiheit von Media-Playern (Stand 09/2014)

* http://sprungmarker.de/2010/barrierefreiheit_mediaplayer_eine_kurzuebersicht/[
  Barrierefreiheit & Media Player: eine Kurzübersicht - Teil 1]

=== Blogartikel von Terrill Thompson zu Audio Description (Stand 03/2017):

* http://terrillthompson.com/blog/813[
  My Audio Description Talk @ CSUN]

== Fragen zu diesem Prüfschritt
=== Was sind "wichtige informationstragende Bildinhalte"? 
* Sehr häufig tauchen in Videos eingeblendete Texte auf, die etwa Sprecher oder Sprecherin bzw. deren Rolle benennen. Ohne diese Information ist für nicht-visuelle Nutzer unklar, wer da eigentlich spricht oder interviewt wird. Wenn es eher unwichtig ist, wie die Person heißt, die spricht (z.B. in Passantenbefragungen), sind solche Einblendungen nicht als "wichtige informationstragende Bildinhalte" zu betrachten.
* Oft sind Videos auch über visuelle Zwischentitel oder eingeblendete Fragen strukturiert. Hier ist zu prüfen, inwieweit die Informationen auch ohne Audiodeskription oder Transkription der Bildinhalte sinnvoll und verständlich sind - zum Beispiel, weil die Tonspur in der Folge ausreichend Kontext liefert.
