= Prüfschritt 9.1.1.1a Alternativtexte für Bedienelemente
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Grafische Bedienelemente (alle verlinkten / interaktiven Grafiken und Bilder)
müssen mit Alternativtexten versehen werden (nicht verlinkte bzw. nicht
interaktive Grafiken und Bilder werden in Prüfschritt
ifdef::env_embedded[9.1.1.1b "Alternativtexte für Grafiken und Objekte"]
ifndef::env_embedded[]
  <<9.1.1.1b Alternativtexte für Grafiken und Objekte.adoc#,9.1.1.1b
  Alternativtexte für Grafiken und Objekte>>
endif::env_embedded[]
geprüft).

Die Alternativtexte für Bedienelemente (z. B. Icons oder Logos) oder
Teaserbilder sollen das *Ziel* des Links bezeichnen.
Alternativtexte für grafische Schaltflächen (Buttons) sollen die *Aktion*
bezeichnen, die der Button auslöst.
Wenn Image maps eingesetzt werden, sollen deren Bereiche (``area``-Elemente)
sinnvolle Alternativtexte haben.

Thema dieses Prüfschritts sind auch Textlinks, die per CSS durch
Hintergrundbilder ersetzt werden sowie Textalternativen für Icon Fonts und
SVGs.

== Warum wird das geprüft?

Für blinde Benutzer oder für Benutzer, die für schnellere Zugriffszeiten das
Laden von Grafiken abschalten, sind Grafiken nicht zugänglich.
Die Textalternative tritt dann an die Stelle der Grafik, sie soll die Grafik
ersetzen.

Icon Fonts sind Schriftarten, die Symbole statt Buchstaben beinhalten.
Sie werden per CSS eingebunden und werden entweder von assistiven Technologien
nicht ausgegeben oder es wird ein Unicode-Äquivalent wiedergegeben, was die
Bedeutung im Kontext nicht vermittelt.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn Grafiken, Icon Fonts oder SVGs als
Bedienelemente (Menüs, Logos, Teaserbilder oder Schaltflächen) eingesetzt
werden.

=== 2. Prüfung

==== 2.1 Anzeige der Alternativtexte von Grafiken

. Die Seite im https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste.html#firefox[
  Firefox] aufrufen.
. Bedienelemente feststellen (zum Beispiel horizontale oder vertikale
  Navigationsleisten, Logo, Banner, Teaserbilder, grafische Schaltflächen).
. In der https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste.html#webdeveloper[
  Web Developer Toolbar] das Menü _Images > Display Alt Attributes_
  aufrufen und prüfen, ob die Bedienelemente mit äquivalenten
  Alternativtexten versehen sind (siehe
  <<2.6 Gleichwertige (äquivalente) Alternativtexte>>). Alternativ kann
  auch das
  https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste.html#imagesbm[
  Images bookmarklet] eingesetzt werden.
. Feststellen, ob die Seite Image maps enthält.
  Hierfür kann gegebenenfalls der Quelltext nach `map` durchsucht werden.
  Ist ein Image map vorhanden, weiter mit <<2.2 Anzeige von Image maps>>.

==== 2.2 Anzeige von Image maps

Falls Image maps eingesetzt werden:

Die Web Developer Tools öffnen und im Quellcode prüfen, ob für jeden
Link (`area`-Element der Image map, aktiver Bereich) *und* für das Gesamtbild
der Image map ein gleichwertiger Alternativtext vorhanden ist (siehe
  <<2.6 Gleichwertige (äquivalente) Alternativtexte>>).

Der Alternativtext für die gesamte Image map sollte in der Regel die Image map
beschreiben, die Alternativtexte für die aktiven Bereiche (``area``-Elemente)
sollten die Linkziele bezeichnen.

==== 2.3 Textalternativen für Hintergrundgrafiken

Hintergrundgrafiken haben kein ``alt``-Attribut, auf diese Weise kann also keine
Textalternative hinterlegt werden.

Falls eine Hintergrundgrafik aber einen im HTML-Dokument tatsächlich
vorhandenen Textlink ersetzt (CSS-Bildersetzungsverfahren), dann gilt dieser
Textlink als Textalternative für die Hintergrundgrafik.
Voraussetzung ist allerdings, dass ein geeignetes Bildersetzungsverfahren
verwendet wurde (nicht ``display:none``).

===== Grundeinstellung in Firefox

. https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste.html#firefox[
  Firefox] aufrufen und im Menü _Extras_ den Dialog _Einstellungen..._
  aufrufenDen Reiter _Inhalt_ wählen und im Bereich _Schriftarten & Farben_ die
  Option _Farben..._ wählen.
. Im Dialog _Farben_ im Bereich _Text und Hintergrund_ als Hintergrundfarbe eine
  Farbe wählen, die normalerweise eher selten für die Seitengestaltung verwendet
  wird (gut geeignet sind z. B. helle Rosa- oder Grüntöne).
. Im Select _Ausgewählte Farben anstatt Farben der Seite verwenden_ die
  Option _Immer_ wählen.
. Die Dialogfenster mit "OK" schließen.

===== Prüfung

. Seite in
  https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste.html#firefox[
  Firefox] aufrufen.
. Prüfen, ob grafische Bedienelemente verschwinden.
  Das passiert, wenn sie als Hintergrundbilder eingebunden sind.
. Falls nicht redundante grafische Bedienelemente als Hintergrundbilder
  eingebunden sind: Prüfen, ob das Hintergrundbild einen tatsächlich im
  HTML-Dokument vorhandenen Textlink ersetzt oder ein aussagekräftiger Alternativtext auf andere Art hinterlegt ist (z.B. als ``aria-label`` oder ``title`` auf dem Link).
. Wenn ein leeres ``a``-Element ohne
  eingeschlossenen Text durch ein Hintergrundbild ersetzt wird, ist dies wie ein
  nicht vorhandenes oder leeres ``alt``-Attribut zu werten.
. Falls Textlinks durch Hintergrundbilder ersetzt werden: Prüfen, welches
  Verfahren für die Bildersetzung verwendet wurde.
  Wenn `display:none` verwendet
  wird, ist dies wie ein nicht vorhandenes oder leeres ``alt``-Attribut zu werten.
. Falls ein geeignetes Bildersetzungsverfahren verwendet wurde:
  Prüfen, ob der Textlink eine äquivalente Textalternative für das
  Hintergrundbild darstellt (siehe
  <<2.6 Gleichwertige (äquivalente) Alternativtexte>>).

==== 2.4 Textalternativen für Icon Fonts

Beim Einsatz von Icon Fonts ist es nicht möglich, mittels ``alt``-Attribut eine
Textalternative zu hinterlegen.

Falls ein Bedienelement aus einem solchen Icon sowie einem HTML-Text besteht,
der den Zweck des Bedienelements wiedergibt, dann gilt dieser Text als
Alternative für das Icon.
Es ist sinnvoll, das Icon selbst mit einer geeigneten Technik für Screenreader
zu verstecken (z. B. ``aria-hidden="true"``).
Handelt es sich dabei um ein informationstragendes Icon ohne visuell sichtbaren
Text (Stand-alone-Icon), so sollte eine Textalternative vorhanden sein.
Dies kann beispielsweise Text sein, der mit einem geeigneten Verfahren
versteckt ist (nicht ``display:none``) oder der über ein `aria-label`
bereitgestellt wird.

===== Prüfung

. Seite in
  https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste.html#firefox[
  Firefox] aufrufen.
. Bedienelemente feststellen.
. Mit Firebug oder dem Seiteninspektor des Browsers prüfen, ob mit der
  CSS-Eigenschaft `content` für die Pseudoelemente `:before` oder `:after`
  Inhalt (Font Icons) eingebunden wird.
. Falls nicht redundante Icons eingebunden sind: Prüfen, ob eine
  HTML-Textalternative vorhanden ist.
  Ein leeres ``a``-Element ohne eingeschlossenen
  Text, ist wie ein nicht vorhandenes oder leeres ``alt``-Attribut zu werten.
. Falls HTML-Textalternativen vorhanden sind, die nicht am Bildschirm sichtbar
  sind: Prüfen, welches Verfahren verwendet wurde, um diese zu verstecken.
  Wenn `display:none` verwendet wird, ist dies wie ein nicht vorhandenes oder
  leeres ``alt``-Attribut zu werten.
. Falls ein geeignete CSS-Technik verwendet wurde: Prüfen, ob der Textlink eine
  äquivalente Textalternative für das Icon darstellt
  (siehe
  <<2.6 Gleichwertige (äquivalente) Alternativtexte>>).
. Falls keine HTML-Textalternative vorhanden ist, prüfen, ob die Textalternative
  über ein ``title``-Attribut oder `aria-label` bereitgestellt wird.
. Falls für die Icons Text ausgegeben wird (z. B. ``content: "k"``), prüfen,
  ob das Icon mit einer geeigneten Technik für Screenreader versteckt wird (z. B.
  ``aria-hidden="true"``).

==== 2.5 Textalternativen für Inline-SVGs

===== Prüfung

. Seite im
  https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste.html#firefox[
  Firefox] aufrufen.
. Bedienelemente feststellen.
. Mit den Web Developer Tools des Browsers prüfen, ob es sich um ein
  direkt in HTML eingebundene SVG handelt (Inline SVG).
. Prüfen, ob eine Textalternative vorhanden ist
. Prüfen, ob ein ``title``-Element (für längere Beschreibungen das
  ``desc``-Element) vorhanden ist und die dort hinterlegte Textalternative das
  Bild in angemessener Weise ersetzt (siehe
  <<2.6 Gleichwertige (äquivalente) Alternativtexte>>).
  Das `title-` bzw. ``desc-``Element sollte das erste Kind-Element des
  ``svg``-Eltern-Elements sein.
. Da SVG noch nicht ausreichend von allen Screenreader-Browser-Kombinationen
  unterstützt wird, prüfen, ob die Zugänglichkeit über ARIA-Auszeichnung
  gewährleistet ist:
+
* SVG-Grafiken sollten `role="img"` tragen, sonst wird ggf. ihr
  ``title``-Element nicht ausgegeben.
* Wird das SVG ``title``-Element als zugänglicher Name genutzt, sollte das
  ``svg``-Element mittels `aria-labelledby` auf das ``title``-Element verweisen.
* Wenn ein Link sowohl die SVG-Grafik als auch einen in sich aussagekräftigen
  Linktext enthält, sollte die SVG-Grafik über `aria-hidden="true"` aus der
  Screenreader-Ausgabe entfernt werden.
  Die Nutzung einer `role` ist dann nicht erforderlich.
* Wenn kein `title-` oder ``desc``-Element eingesetzt wird, prüfen, ob über
  `aria-label` auf dem umschließenden Link eine Textalternative bereitgestellt
  wird.
  Für die Rolle kommt bei SVGs auch `role="graphics-document"`  in Frage.
  Diese kommt für komplexere SVG-Grafiken wie z. B. Erklärbilder, Diagramme,
  oder Bilder mit eingebundenen Links zum Einsatz (das Ausmaß der
  Unterstützung durch Screenreader ist zur Zeit unklar).

==== 2.6 Gleichwertige (äquivalente) Alternativtexte

Entscheidend ist: die Seite soll benutzbar sein, wenn Grafiken, oder Bilder
oder Objekte durch die entsprechenden Alternativtexte oder Textalternativen
ersetzt sind.

In der Regel bedeutet das:

* Bei *Schriftgrafiken* soll der Alternativtext den Text der Schriftgrafik
  wiederholen.
* Bei *Symbolen* soll der Alternativtext das Symbol nicht beschreiben, sondern
  ersetzen.
  Also zum Beispiel Alternativtext "Kontakt" für einen Briefkasten, der als
  Symbol für die Kontakt-Seite verwendet wird.
* Bei *Objekten*, die nicht angezeigt werden können, sollen der
  Alternativtext (ganz gleich ob Fallback-Text des Objekts oder skriptgeneriert)
  eine kurze Beschreibung oder Identifizierung bieten.
  Zusätzlich ist es sinnvoll, dass ein Skript auswertet, ob das Objekt wegen
  deaktiviertem JavaScript und/oder deaktiviertem Plugin nicht angezeigt
  werden kann, und eine entsprechende Meldung generiert.
  In diesem Fall ist es auch ausreichend, wenn das Objekt etwa durch eine
  Überschrift im unmittelbaren Kontext identifiziert wird.
* Bei *verlinkten Abbildungen* gibt es folgende
  Möglichkeiten:
** Beschreibung des abgebildeten Gegenstandes in den Alternativtext (wenn der
   abgebildete Gegenstand wichtig ist und daraus das Linkziel hervorgeht, zum
   Beispiel Logo),
** Ziel des Links in den Alternativtext (nur wenn der abgebildete Gegenstand
   unwichtig ist, zum Beispiel Illustration),
** Beschreibung des abgebildeten Gegenstandes und Ziel des Links in den
   Alternativtext (wenn beides wichtig ist).
   Generell gilt: Alternativtexte sollen kurz sein.
   Ausführliche Beschreibungen von Abbildungen sollen nicht im
   Alternativtext, sondern im Kontext der Abbildung zur Verfügung gestellt
   werden.

=== 3. Hinweise

==== 3.1 Alternativtexte für redundant verlinkte Abbildungen

Wenn eine Abbildung und ein danebenstehender Textlink auf dasselbe Ziel
verweisen, muss geprüft werden, ob Abbildung und Text in den selben Link
eingeschlossen sind.

Wenn Abbildung und Text innerhalb des selben Links stehen, soll der
Alternativtext der Abbildung nicht den Text des Links wiederholen.
Je nach Inhalt der Abbildung kann das ``alt``-Attribut dann leer bleiben oder
den abgebildeten Inhalt beschreiben, während der Linktext Zweck oder Ziel des
Links beschreibt.

Wenn Abbildung und Text zwei unabhängige Links auf dasselbe Ziel sind, dann
kann das ``alt``-Attribut dagegen _nicht_ leer bleiben.
Denn gängige Screenreader verlassen sich nicht darauf, dass leere
``alt``-Attribute sachgerecht eingesetzt werden, sie behandeln bei
Bedienelementen leere wie fehlende ``alt``-Attribute und lesen den Dateinamen
der Grafik / die URL der Zieldatei vor.

==== 3.2 Unterstützung von SVGs durch assistive Technologien

Da SVG noch nicht ausreichend in allen Screenreader-Browser-Kombinationen
unterstützt werden, sollte derzeit die Rolle über WAI-ARIA vermittelt werden
(siehe
ifdef::env_embedded[9.4.1.2 "Name, Rolle, Wert verfügbar").]
ifndef::env_embedded[]
  <<9.4.1.2 Name-Rolle-Wert verfügbar.adoc#,9.4.1.2 Name, Rolle, Wert
  verfügbar>>).
endif::env_embedded[]
Die Rolle kann entfallen, wenn Text im gleichen Link das Linkziel
aussagekräftig beschreibt: dann sollte die SVG-Grafik mit `aria-hidden="true"`
ausgezeichnet werden.

=== 4. Bewertung

==== Nicht voll erfüllt

* Der Alternativtext fehlt beim Link zum Seitenanfang oder bei einem anderen
  für die Benutzung der Seite weniger wichtigen Bedienelement.
* Alternativtexte sind missverständlich, undeutlich oder extrem lang.

==== Nicht erfüllt

* Der Alternativtext für ein wichtiges Bedienelement fehlt oder er ist
  unbrauchbar.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten

Verlinkte Grafiken sind stets in diesem Prüfschritt zu bewerten.
Das gilt auch dann, wenn die Grafiken neben der Information über das Linkziel
auch noch eine andere Information vermitteln sollen, wie zum Beispiel auf die
Startseite verlinkte Logos.

Einzige Ausnahme: Grafik und danebenstehender Text sind ein zusammengehöriger
Link.
Der Alternativtext bezieht sich dann nur auf die Grafik, die
Prüfkriterien
ifdef::env_embedded[9.1.1.1b "Alternativtexte für Grafiken und Objekte"]
ifndef::env_embedded[]
  <<9.1.1.1b Alternativtexte für Grafiken und Objekte.adoc#,9.1.1.1b
  Alternativtexte für Grafiken und Objekte>>
endif::env_embedded[]
oder
ifdef::env_embedded[9.1.1.1c "Leere alt-Attribute für Layoutgrafiken"]
ifndef::env_embedded[]
  <<9.1.1.1c Leere alt-Attribute für Layoutgrafiken.adoc#,9.1.1.1c Leere
  alt-Attribute für Layoutgrafiken>>
endif::env_embedded[]
sind anzuwenden.

* Alternativtexte für grafische Überschriften: siehe Prüfschritt
ifdef::env_embedded[9.1.1.1b "Alternativtexte für Grafiken und Objekte".]
ifndef::env_embedded[]
  <<9.1.1.1b Alternativtexte für Grafiken und Objekte.adoc#,9.1.1.1b
  Alternativtexte für Grafiken und Objekte>>.
endif::env_embedded[]
* CAPTCHAs werden im Prüfschritt
ifdef::env_embedded[9.1.1.1d "Alternativen für CAPTCHAs"]
ifndef::env_embedded[]
  <<9.1.1.1d Alternativen für CAPTCHAs.adoc#,9.1.1.1d Alternativen für
  CAPTCHAs>>
endif::env_embedded[]
  geprüft.
* Textäquivalent (``title``-Attribut) für Frames: siehe Prüfschritt
ifdef::env_embedded[9.2.4.1 "Bereiche überspringbar".]
ifndef::env_embedded[]
  <<9.2.4.1 Bereiche überspringbar.adoc#,9.2.4.1 Bereiche überspringbar>>.
endif::env_embedded[]
* Linktexte sind auch in Prüfschritt
ifdef::env_embedded[9.2.4.4 "Aussagekräftige Linktexte"]
ifndef::env_embedded[]
  <<9.2.4.4 Aussagekräftige Linktexte.adoc#,9.2.4.4 Aussagekräftige
  Linktexte>>
endif::env_embedded[]
  Thema.
  Dort geht es um die allgemeine Aussagekraft, in diesem Prüfschritt 9.1.1.1a
  geht es dagegen nur um die Gleichwertigkeit von Alternativtext und
  grafischem Link.
* Die Ausgabe der entsprechenden Rolle von SVGs wird im Prüfschritt
ifdef::env_embedded[9.4.1.2 "Name, Rolle, Wert verfügbar"]
ifndef::env_embedded[]
  <<9.4.1.2 Name-Rolle-Wert verfügbar.adoc#,9.4.1.2 Name, Rolle, Wert
  verfügbar>>
endif::env_embedded[]
  geprüft (s. olink:#3.2[3.2 Unterstützung von SVGs durch assistive
  Technologien]).

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* http://www.w3.org/TR/WCAG21/#text-alternatives[
  Guideline 1.1 Text Alternatives: Provide text alternatives for any non-text
  content so that it can be changed into other forms people need, such as
  large print, braille, speech, symbols or simpler language.]

==== Success criterion

* http://www.w3.org/TR/WCAG21/#x1-1-1-non-text-content[
  1.1.1 Non-text Content] (Level A)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G94[
  G94: Providing short text alternative for non-text content that serves the
  same purpose and presents the same information as the non-text content]

===== HTML Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/html/H2[
  H2: Combining adjacent image and text links for the same resource]
* https://www.w3.org/WAI/WCAG21/Techniques/html/H24[
  H24: Providing text alternatives for the `area` elements of image maps]
* https://www.w3.org/WAI/WCAG21/Techniques/html/H30[
  H30: Providing link text that describes the purpose of a link for anchor
  elements]
* https://www.w3.org/WAI/WCAG21/Techniques/html/H36[
  H36: Using `alt` attributes on images used as submit buttons]
* https://www.w3.org/WAI/WCAG21/Techniques/html/H37[
  H37: Using `alt` attributes on `img` elements]

===== ARIA Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA6[
  ARIA6 Using `aria-label` to provide labels for objects]
* https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA10[
  ARIA10: Using `aria-labelledby` to provide a text alternative for non-text
  content]

===== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F3[
  F3: Failure of Success Criterion 1.1.1 due to using CSS to include images
  that convey important information]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F20[
  F20: Failure of Success Criterion 1.1.1 and 4.1.2 due to not updating text
  alternatives when changes to non-text content occur]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F30[
  F30: Failure of Success Criterion 1.1.1 and 1.2.1 due to using text
  alternatives that are not alternatives]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F65[
  F65: Failure of Success Criterion 1.1.1 due to omitting the `alt` attribute
  on `img` elements, `area` elements, and `input` elements of type 'image']

== Quellen

=== Anleitungen zum Erstellen guter Alternativtexte

* W3C Web Accessibility Tutorials:
  https://www.w3.org/WAI/tutorials/images/[Images Concepts]
* WebAIM: https://webaim.org/techniques/alttext/[Alternative Text]
* HTML 5.1 Spezifikation:
  https://www.w3.org/TR/html51/semantics-embedded-content.html#alt-text[
  Requirements for providing text to act as an alternative for images]

=== W3C - Scalable Vector Graphics (SVG) 1.1

* https://www.w3.org/TR/SVG11/struct.html#DescriptionAndTitleElements[
  The 'desc' and the 'title' elements]
* Zu Rollen wie `role="graphics-document"` für komplexere SVG-Grafiken:
  https://www.w3.org/TR/graphics-aria-1.0/[
  WAI-ARIA Graphics Module] (W3C Recommendation 02 October 2018)

=== SVGs zugänglich einbinden

* https://www.scottohara.me/blog/2019/05/22/contextual-images-svgs-and-a11y.html[
  Contextually marking up accessible images and SVGs] (Scott O'Hara, May 2019)
* https://www.deque.com/blog/creating-accessible-svgs/[Creating accessible SVGs] (Deque blog, January 2019)
* https://simplyaccessible.com/article/7-solutions-svgs/[
  7 solutions for creating more accessible SVGs] (SimplyAccessible, March 2017)
* https://css-tricks.com/accessible-svgs/[
  Accessible SVGs] (CSS-Tricks, updated August 2016)

== Fragen zu diesem Prüfschritt

=== Kann nicht das ``alt``-Attribut leer gelassen werden, wenn stattdessen ein sinnvolles ``title``-Attribut verwendet wird? Das wird in meinem Screenreader problemlos ausgegeben.

Es stimmt, dass neuere Screenreader bei Vorhandensein eines ``title``-Attributs
dieses anstelle eines fehlenden ``alt``-Attributs ausgeben.
Das trifft aber nicht auf alle gängigen Hilfsmittel zu.
Deshalb verlangt der Test grundsätzlich die standardkonforme Umsetzung
gemäß HTML 5.0 und WCAG 2.0:

* Das ``alt``-Attribut soll den *Inhalt* des Bildes *ersetzen*
* Das ``title``-Attribut ist für *zusätzliche
  (nicht essenzielle) Informationen* gedacht

Deshalb steht ja in der WCAG 2.0-Technik
http://www.w3.org/TR/WCAG20-TECHS/H33.html[H33]:

[.BLOCK_LANG_EN]
____
Because of the extensive user agent limitations in supporting access to the title attribute, authors should use caution in applying this techniqueFor this reason, it is preferred that the author use technique http://www.w3.org/TR/WCAG20-TECHS/C7.html[C7]: Using CSS to hide a portion of the link text (CSS) or http://www.w3.org/TR/WCAG20-TECHS/H30.html[H30]: Providing link text that describes the purpose of a link for anchor elements (HTML).
____

Ein weiterer Punkt, der die Wichtigkeit des ``alt``-Attributs unterstreicht, ist
die Nutzung mit abgeschalteten Bildern.
Auch wenn Alternativtexte im Bereich der Bildumrisse in manchen Browsern nicht vollständig angezeigt werden, ist das
immer noch besser als eine Nicht-Anzeige beim Einsatz von `title`.

=== Der Alternativtext beschreibt die Grafik, der ``title``-Text beschreibt das Link-Ziel: Ist das ein geeigneter Lösungsansatz für grafische Links?

Vorgeschlagen wurde diese Lösung für Fälle, in denen die Grafik nicht einfach
das Linkziel abbildet (Schriftgrafik) oder für das Linkziel steht, sondern
zusätzlich eine eigenständige Aussagekraft hat (zum Beispiel bei aus
Anreißertext und einer verlinkten Abbildung bestehenden Teasern).

Die Idee ist einleuchtend:

Der sehende Benutzer klickt auf das Bild, denn er vermutet, dass hinter dem
Bild eine Seite steht.
Der beschreibende Alternativtext ersetzt das Bild, der blinde Benutzer
schließt wie der sehende Benutzer vom (beschriebenen) Bildinhalt auf das
Linkziel.
Wenn aus dem Bild / der Bildbeschreibung nicht hinreichend klar hervorgeht, wo
es hinführt, kann der sehende wie der blinde Benutzer auf die ergänzenden
Informationen im ``title``-Attribut zugreifen.

In der Praxis funktioniert das aber nicht:

Sehende Benutzer orientieren sich nicht an den Inhalten des Bildes, sondern
eher an der Position.
Viele Teaser-Bilder sind vom Inhalt her ohnehin nicht geeignet, 
etwas über das Linkziel zu sagen, der Bezug zum Thema des Linkziels
ist oft nur ansatzweise nachvollziehbar.
Aber sie _müssen_ auch gar nichts über
das Linkziel sagen: Das Linkziel steht im Text daneben, es muss nicht aus dem
Bild erraten werden.
Geklickt wird auf das Bild, weil es vielleicht leichter zu
treffen ist und der Benutzer weiß, dass Teaser-Bilder üblicherweise mit
weiterführenden Informationen zum jeweiligen Textabschnitt verlinkt sind.

Für den blinden Benutzer ist der Zusammenhang von Bild und (darauf folgendem)
Kontext dagegen normalerweise nicht klar. Er müsste also tatsächlich 
Vermutungen anstellen, wo ein Link hinführen könnte, der mit dem 
beschriebenen Bild verbunden ist.
Und da das Bild die entsprechende Aussagekraft nicht hat, wäre er
auf die Informationen im ``title``-Attribut in der Regel _angewiesen_.
Sie sind also für ihn _nicht ergänzend_.

Hinzu kommt: Das ``title``-Attribut wird von gängigen Screenreadern
unterschiedlich behandelt und schlecht unterstützt.
Nach wie vor werden von JAWS die Inhalte von ``alt``-Attribut und 
``title``-Attribut nur alternativ vorgelesen.

Das ``title``-Attribut ist für ergänzende Informationen vorgesehen.
Die Information über das Linkziel ist in aller Regel keine ergänzende
Information, denn sie geht aus dem Bildinhalt nicht hervor.
Der Alternativtext muss daher das Linkziel beschreiben.

=== Sollte im ``alt``-Attribut und im ``title``-Attribut eines Bildes derselbe Inhalt stehen?

Der Alternativtext soll das Bild _ersetzen_.
Sehr häufig bedeutet das: Der Alternativtext sagt, 
was abgebildet ist.

Das ``title``-Attribut ist dagegen für _ergänzende_ Informationen zum Bild
vorgesehen.
Es kann zum Beispiel verwendet werden, um zu sagen, 
von welcher Quelle das Bild stammt.
Dort stehen also Informationen, die man dem Bild _nicht_
entnehmen kann.

Eigentlich also ein klarer Fall: Die Aufgaben der Attribute sind
unterschiedlich, entsprechend sollten sie normalerweise nicht denselben Inhalt
haben. Es gibt aber eine wichtige Ausnahme:

Häufig werden Symbole oder Zeichen als _Bedienelemente_ verwendet.
Die Bedeutung solcher Bilder kann undeutlich sein.
Der Benutzer sieht nicht genau, was abgebildet ist, oder er versteht nicht, 
wofür das Bild stehen soll. Für diesen Besucher ist eine ergänzende 
Beschriftung nützlich. Sie steht am besten als Text neben dem Bild, 
denn dann ist sie auch für Tastaturnutzer sichtbar.
Aber auch das ``title``-Attribut kann verwendet werden, denn die 
Beschriftung ist (für den sehenden Benutzer) ergänzend.

Das ist also ein Fall, in dem es Sinn machen kann, dass der Alternativtext und
das ``title``-Attribut dieselbe Information bereitstellen:

Für blinde Benutzer ersetzt der Alternativtext das Bild. Und zwar am besten,
indem er die für blinde Benutzer unbrauchbare Bildform umgeht, also das Bild
durch die Bezeichnung des Linkziels oder der auszulösenden Aktion ersetzt.

Für sehende Benutzer stellt das ``title``-Attribut die Bedeutung des Bildes
klarEs bezeichnet das Ziel des Links oder die Aktion, die ausgelöst wird.

Alternativtext und ``title``-Attribut liefern für unterschiedliche
Benutzergruppen die selbe Information, für die einen als Ersatz und für die
anderen als Ergänzung zum Bild. Mit dem unguten Begleiteffekt, dass der blinde
Benutzer (je nach Hilfsmittel und Benutzereinstellung) unter Umständen zwei
Mal dasselbe hört.

Ideal ist diese Lösung sicher nicht, einerseits, weil die ergänzende
Information im ``title``-Attribut nicht für jeden zugänglich ist und
andererseits, weil dieselbe Information zwei Mal geliefert wird.
Die zweifache Angabe von Linkzielen im Alternativtext und im 
``title``-Attribut wird aber im BITV-Test nicht negativ bewertet, 
wenn sie im Kontext hilfreich ist.

=== Screenreader zeigen den Dateinamen der Bilddatei an, wenn kein Alternativtext zur Verfügung steht. 
So kann das Fehlen des Alternativtextes kompensiert werden. Soll man das bei der Prüfung berücksichtigen?

Nein, die Dateinamen sollen bei der Prüfung nicht berücksichtigt werden.
Denn dieser Zugangsweg ist nicht verlässlich. 
Nicht alle Browser oder Screenreader zeigen Dateinamen an, auch ist die
Eignung des Dateinamens als Navigationshilfe eher zufällig.

Allgemein gesagt: Gute Nutzbarkeit mit speziellen Hilfsmitteln gewährleistet
nicht ein positives Ergebnis des BITV-Tests. Der Webauftritt wird positiv bewertet, 
wenn er das Seine zur Sicherung der Zugänglichkeit beisteuert.
Das Hilfsmittel ist dagegen gut, wenn es auch mit schlechten Webauftritten klarkommt.
Es sorgt dafür, dass auch Webauftritte, die nicht barrierefrei sind,
irgendwie genutzt werden können.

=== Soll im Alternativtext stehen, dass es sich um ein Navigationselement handelt?

Nein, das ist nicht erforderlich. Screenreader oder Textbrowser stellen den
Bezug des Alternativtextes zum Link ohnehin her.
Wenn im Alternativtext steht, dass es sich um ein Navigationselement handelt,
liefert der Screenreader diese Information also zwei Mal.

Im BITV-Test wird ein entsprechender Vorsatz im Alternativtext jedoch nicht
negativ bewertet, er ist für die Bewertung nicht relevant.

=== Sollte der Alternativtext für grafische Bedienelemente auch sagen, was abgebildet ist?

Manchmal ergibt sich das von selbst, wie bei Schriftgrafiken: das Linkziel ist
abgebildet, die Beschreibung des abgebildeten Gegenstandes sagt zugleich auch,
wohin der Link führt.

Schwieriger ist es bei SymbolenDem visuell orientierten Besucher ist
vielleicht klar, für welches Linkziel das abgebildete Symbol steht.
Für einen blinden Besucher ist der Weg über das Symbol aber weniger vertraut,
er ist auf jeden Fall umständlich.

In solchen Fällen, wenn die Abbildung nicht hinreichend klar über das Linkziel
Auskunft gibt, sollte man sich fragen: Ist es wichtig, zu wissen, was da
abgebildet ist, soll dem sehenden Besucher da etwas gezeigt werden? Oder hat die
Abbildung eigentlich _nur_ die Aufgabe, das Linkziel zu vermitteln?

Ein Beispiel für den ersten Fall: das Logo einer Website ist auf die
Startseite verlinkt.
Es dient also als Bedienelement, der Alternativtext muss
das Ziel des Links angeben.
Das Logo ist aber auch selbst wichtig, es soll dem Besucher gezeigt werden. 
Der Alternativtext muss also auch sagen, was abgebildet ist.

Ein Beispiel für den zweiten Fall: ein Briefumschlag verweist auf die
Kontaktseite des Webangebotes.
In diesem Fall kommt es nur (oder jedenfalls hauptsächlich) auf 
die Vermittlung des Linkziels an.
Der Alternativtext muss also nicht sagen, was abgebildet ist, 
er kann sich auf die Angabe des Linkziels beschränken.

Für die Bewertung im BITV-Test gilt: Das Ziel des Links muss immer angegeben
werden.
Manchmal reicht dafür die Bezeichnung des abgebildeten Gegenstandes aus,
andernfalls muss das Linkziel ausdrücklich angegeben werden.
Zusätzliche Angaben zum abgebildeten Gegenstand sind nur erforderlich, wenn
die Abbildung etwas zeigen soll, also einen weitergehenden Informationsgehalt
hat.

=== Links oben ist das Firmenlogo abgebildet, es ist außerdem mit der Startseite verlinkt. Welcher Alternativtext ist angemessen?

Der Alternativtext in diesem Fall hat zwei Aufgaben: Er soll für das Logo
stehen und er soll das Linkziel vertreten.
Auf dieser Grundlage kann man verschieden argumentieren:

Das Bild zeigt das Logo der Firma.
Das ist auch seine vorrangige Aufgabe.
Auch für einen blinden Benutzer ist es gut, zu wissen, 
dass die Firma ihr Logo auf der Seite zeigt.
Zusätzliche Informationen zum Ziel des Links sind überflüssig.
Wo soll das Logo von Müllermilch schon hinführen.
Also sollte "Logo: Müllermilch" im Alternativtext stehen.

Das Bild hat zwei Funktionen.
Es zeigt das Logo der Firma und es dient als Link auf die Startseite des
Webauftritts.
Der sehende Benutzer hat damit kein Problem, er wundert sich nicht, wenn er
das Bild anklickt und auf der Startseite von Müllermilch landet.
Ebenso der blinde Benutzer.
Ein grafischer Link namens Müllermilch.
Der zeigt und verweist wohl auf Müllermilch.
Also kurz und knapp: "Müllermilch" in den Alternativtext!

Das Bild hat zwei Funktionen.
Es zeigt das Logo der Firma und es dient als Link auf die Startseite des
Webauftritts.
Für beides soll auch der Alternativtext stehen: "Logo: Müllermilch - zur
Startseite".

Alle drei Alternativen unterstützen den blinden Besucher.
Im BITV-Test gelten daher alle drei Alternativen als angemessen.
