= Prüfschritt 9.1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Beschriftungen sollen über Markup mit den Formularelementen, die sie
beschriften, verknüpft sein.

Bei `label`-Elementen geschieht das über das `for`-Attribut oder den
Einschluss des beschrifteten Formularelements in das `label`-ElementSind
Beschriftungen nicht mit dem `label`-Element ausgezeichnet, soll eine
Beschriftung des zugehörigen Formularelements auf anderem Weg (etwa über das
`aria-labelledby`-Attribut) sichergestellt sein.

Ist bei Gruppen von Formularelementen eine Gruppenbeschriftung für das
Verständnis der Beschriftung der einzelnen Formularelemente nötig, sollte die
Verfügbarkeit sichergestellt werden (z.Bmit Hilfe von `fieldset` mit `legend`).

Visuell voneinander abgesetzte oder logisch miteinander verbundene Gruppen von
Formularelementen sollten mit `fieldset` oder mithilfe von Überschriften
sinnvoll strukturiert sein.

== Warum wird das geprüft?

Die Verknüpfung von Beschriftungen mit den zugeordneten Eingabefeldern stellt
sicher, dass der Aufbau einer Seite unabhängig von der Präsentation festgelegt
und zugänglich ist:

* Der Screenreader liest die Beschriftungen vor, wenn der Benutzer durch die Formularelemente wandert.
* Ein Vorteil der Nutzung nativer `label`-Elemente: Mausnutzer können durch einen Klick auf das Label den Fokus auf das zugeordnete Formularelement setzen.

== Wie wird geprüft?

=== 1Anwendbarkeit des Prüfschritts

* Der Prüfschritt ist anwendbar, wenn die Seite Formularelemente enthält.

=== 2Prüfung

==== 2.1Sind Beschriftungen und Formular-Elemente verküpft?

Mit der Maus auf die Beschriftung von Formular-Elementen klicken und prüfen,
ob der Cursor dadurch auf das Formular-Element gesetzt wird.
Ist das nicht der Fall, prüfen, ob Beschriftung und Formular-Element mit
`aria-labelledby` verknüpft sind oder ein Name für das Formular-Element auf
andere Weise programmatisch bereitgestellt wird

==== 2.2Prüfung von Gruppen von Formular-Elementen

Prüfen, ob visuell voneinander abgesetzte oder logisch miteinander verbundene
Gruppen von Formular-Elementen mithilfe `fieldset` oder Überschriften sinnvoll
strukturiert sind.
Falls eine Gruppenbeschriftung für das Verständnis der Beschriftung der einzelnen Formularelemente nötig sind, prüfen, ob die Gruppenbeschriftung mit dem `legend`-Element eines `fieldset` oder über eine ausreichend unterstützte Alternative (etwa `role="group"`) ausgezeichnet ist.

==== 2.3Gliederung von Auswahllisten

* Wenn Auswahllisten (`select`) voneinander abgesetzte Gruppen von Optionen enthalten, sind diese mit `optgroup` ausgezeichnet (mit der Web Developer Toolbar > Informationen > Elementinformationen einblenden > Kindelemente überprüfen)

=== 3Hinweise

==== 3.1 Ergänzende Beschriftungen (etwa über `fieldset` / `legend`)

Auch wenn die Beschriftungen (Labels) der Formularelemente korrekt ausgezeichnet sind, kann es sein, dass diese für sich genommen nicht ausreichen und z.Beine gemeinsame Überschrift (`legend`-Element eines `fieldset`) für das Verständnis notwendig ist - etwa bei Radio-Inputs mit den Labels "Ja" / "Nein" oder bei Adressen, bei denen es unklar ist, ob es sich um eine Rechnungs- oder eine Versandadresse handelt.

==== 3.2 Kombinierte Formular-Elemente (etwa bei Datumseingabe)

Bei kombinierten Formular-Elementen hat nicht immer jedes Element eine
zugeordnete BeschriftungIn diesem Fall sollen Elemente mit einem erklärenden
`title`-Attribut versehen werdenBeispiel: In einem Formular werden für die
Eingabe eines Datums drei Auswahllisten angeboten (Tag, Monat und Jahr)Die
drei Auswahllisten haben eine gemeinsame Beschriftung: DatumDie Auswahllisten
für Tag, Monat und Jahr sind mit einem erklärenden `title`-Attribut
versehenAlternativ kann in diesem Fall die Beschriftung auch mit Hilfe von
`aria-label` oder `aria-labelledby` zur Verfügung gestellt werden.

==== 3.3 Suchfeld mit nachfolgenem Button bzwInput

Wenn ein einfaches Suchformular nur aus einem Eingabefeld und einem Button besteht, ist oftmals keine sichtbare Beschriftung notwendigHier ist es ausreichend, wenn Eingabefeld und Button sichtbar nebeneinander (und im Quellcode nacheinander) positioniert sind, das Eingabefeld eine Textvorbelegung hat oder die Beschriftung des Buttons die Funktion eindeutig kennzeichnet (etwa "Suchen" oder Lupen-Icon mit aussagekräftigem Alternativtext)Das unbeschriftete Eingabefeld mit Textvorbelegung muss in solchen Fällen entweder ein aussagekräftiges `title`-Attribut, ein verküpftes verstecktes Label oder ein `aria-label`-Attriut haben, da für Screenreader-Nutzer der nachfolgende Button nicht gleichermaßen als Beschriftung taugt.

==== 3.4 Zusätzliche Beschriftungen

Sichtbare zusätzliche erklärende Beschriftungen sollten über
`aria-describedby` mit betreffenden Formular-Element verknüpft sein.

=== 4Bewertung

==== Nicht erfüllt

* Beschriftungen sind nicht korrekt mit den dazugehörigen Eingabefeldern verknüpft und ein zugänglicher Name ist auch auf andere Weise (etwa über `aria-label` oder `title`) nicht programmatisch ermittelbar.

==== Nicht voll erfüllt

* Zur Unterscheidung notwendige Gruppenbeschriftungen sind vorhanden, aber nicht programmatisch ermittelbar (etwa über `fieldset`/`legend` oder `role="group"` mit Verknüpfung der Gruppenüberschrift über `aria-labelledby`).
* Zum Verständnis wichtige zusätzliche Beschriftungen sind nicht programmatisch ermittelbar (etwa durch Verknüpfung über `aria-describedby`).
* Hierarchische Auswahllisten sind mit Dummy-Einträgen oder Einrückung durch Leerzeichen oder Bindestriche gegliedert statt mit `optgroup`.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten

* Ob die Beschriftungen von Formular-Elementen (auch bei Nutzung von Gruppenüberschriften als Ergänzung der unmittelbaren Beschriftungen) hinreichend aussagekräftig sind, wird in Prüfschritt link:/index.php?a=di&iid=80&s=n[2.4.6a] "Aussagekräftige Überschriften und Beschriftungen" geprüftHier geht es um die programmatische Ermittelbarkeit.
* Ob die sichtbare Beschriftung überhaupt vorhanden ist, wird in Prüfschritt link:/index.php?a=di&iid=81&s=n[3.3.2a] "Beschriftungen von Formularelementen vorhanden" geprüft.
* Ob die sichtbare Beschriftung im zugänglichen Namen des Formularelements vorkommt, wird in Prüfschritt link:/index.php?a=di&iid=117&s=n[2.5.3a] "Sichtbare Beschriftung Teil des zugänglichen Namens" geprüft.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guidelines

* https://www.w3.org/TR/WCAG21/#adaptable[Guideline 1.3 Adaptable: Create content that can be presented in different ways (for example simpler layout) without losing information or structure.]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#info-and-relationships[1.3.1 Info and Relationships] (Level A)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G162.html[G162: Positioning labels to maximize predictability of relationships]

===== HTML Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/html/H44.html[H44: Using label elements to associate text labels with form controls]
* https://www.w3.org/WAI/WCAG21/Techniques/html/H65.html[H65: Using the title attribute to identify form controls when the label element cannot be used]
* https://www.w3.org/WAI/WCAG21/Techniques/html/H71.html[H71: Providing a description for groups of form controls using fieldset and legend elements]

===== ARIA Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA1.html[ARIA1: Using the aria-describedby property to provide a descriptive label for user interface controls]
* https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA2.html[ARIA2: Identifying a required field with the aria-required property]
* https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA16.html[ARIA16: Using aria-labelledby to provide a name for user interface controls]
* https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA17.html[ARIA17: Using grouping roles to identify related form controls]

===== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F87.html[F87: Failure of Success Criterion 1.3.1 due to inserting non-decorative content by using :before and :after pseudo-elements and the 'content' property in CSS]

== Quellen

=== W3C Web Accessibility Tutorials: Forms

* Labeling Controls +
https://www.w3.org/WAI/tutorials/forms/labels/
* Grouping Controls +
https://www.w3.org/WAI/tutorials/forms/grouping/
