= Prüfschritt 9.1.3.1g Kein Strukturmarkup für Layouttabellen
include::include/author.adoc[]
include::include/attributes.adoc[]

[[multileiste]]
link:/index.php?a=eb&iid=35[die bisherigen Bewertungen für dieses Prüfschritt]

[.stopFloat]

== Technische Angaben

Version

Aktuell

BITV-Bedingung

1.3.1 Informationen und Beziehungen

WCAG-Erfolgskriterium

1.3.1 Info und Beziehungen

Bewertungsalternativen

ja / nein / nicht anwendbar

Bezieht sich auf

einzelne Webseite

Prüfschritt erfüllt

Für Datentabellen vorgesehenes Mark-up wird nicht für Layouttabellen verwendet.

Prüfschritt nicht anwendbar

Tabellen werden nicht für Layoutfunktionen verwendet.

== Was wird geprüft?

Tabellenstruktur-Mark-up soll nicht für Layouttabellen verwendet werden.

== Wie wird geprüft?

=== 1Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Seite Tabellen für das Layout verwendet.

=== [#G115][#G140]2Prüfung

Seite im Firefox aufrufen.
Das https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste.html[Tables bookmarklet] aufrufenTabellen-Auszeichnungen werden jetzt angezeigt.
[#H39][#H43][#H73][#F46]Prüfen, ob strukturelle Auszeichnungen (`th`, `caption`, `summary`, `headers`, `id`) in Layouttabellen vermieden werden.

=== 3Hinweis

Auch wenn Tabellen mit #role="presentation"# bzw#role="none"# ausgezeichnet sind, sollten semantische Elemente nicht benutzt werden.

=== 4Bewertung

==== Nicht erfüllt:

* In Layouttabellen werden die Elemente `th` oder `caption` oder die Attribute `summary`, `headers` oder `id` verwendet.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131#adaptable[Guideline 1.3 Adaptable: Create content that can be presented in different ways (for example simpler layout) without losing information or structure]

==== Success criterion

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131#info-and-relationships[1.3.1 Info and Relationships] (Level A)

==== Techniques

===== General Techniques

* G115: Using semantic elements to mark up structure
* https://www.w3.org/WAI/WCAG21/Techniques/general/G140.html[G140: Separating information and structure from presentation to enable different presentations]

===== HTML Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/html/H39.html[H39 Using `caption` elements to associate data table captions with data tables]
* https://www.w3.org/WAI/WCAG21/Techniques/html/H73.html[H73 Using the `summary` attribute of the `table` element]

===== Failure

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F46.html[F46 Failure of Success Criterion 1.3.1 due to using `th` elements, `caption` elements, or non-empty `summary` attributes in layout tables]

== Quellen

=== F46: Failure of Success Criterion 1.3.1 due to using `th` elements, `caption` elements, or non-empty `summary` attributes in layout tables

____
Although WCAG 2.1 does not prohibit the use of layout tables, CSS-based layouts are recommended in order to retain the defined semantic meaning of the HTML table elements and to conform to the coding practice of separating presentation from contentWhen a table is used for layout purposes the th element should not be usedSince the table is not presenting data there is no need to mark any cells as column or row headersLikewise, there is no need for an additional description of a table which is only used to layout contentDo not include a summary attribute and do not use the `summary` attribute to describe the table as, for instance, "layout table"When spoken, this information does not provide value and will only distract users navigating the content via a screen readerEmpty summary attributes are acceptable on layout tables, but not recommended.
____

Quelle: https://www.w3.org/WAI/WCAG21/Techniques/failures/F46.html[https://www.w3.org/WAI/WCAG21/Techniques/failures/F46.html]
