= Prüfschritt 9.1.1.1a Alternativtexte für Bedienelemente9.1.1.1b Alternativtexte für Grafiken und Objekte9.1.1.1c Leere alt-Attribute für Layoutgrafiken9.1.1.1d Alternativen für CAPTCHAs9.1.2.1a Alternativen für Audiodateien und stumme Videos9.1.2.2a Aufgezeichnete Videos mit Untertiteln9.1.2.3a Audiodeskription oder Volltext-Alternative für Videos9.1.2.4a Videos (live) mit Untertiteln9.1.2.5a Audiodeskription für Videos9.1.3.1a HTML-Strukturelemente für Überschriften9.1.3.1b HTML-Strukturelemente für Listen9.1.3.1c HTML-Strukturelemente für Zitate9.1.3.1d Inhalt geglieder9.1.3.1e Datentabellen richtig aufgebaut9.1.3.1f Zuordnung von Tabellenzellen9.1.3.1g Kein Strukturmarkup für Layouttabellen9.1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar9.1.3.2a Sinnvolle Reihenfolge9.1.3.3a Ohne Bezug auf sensorische Merkmale nutzbar9.1.3.4a Keine Beschränkung der Bildschirmausrichtung9.1.3.5a Eingabefelder zu Nutzerdaten vermitteln den Zweck9.1.4.10a Inhalte brechen um9.1.4.11a Kontraste von Grafiken und grafischen Bedienelementen ausreichend9.1.4.12a Textabstände anpassbar9.1.4.13a Eingeblendete Inhalte bedienbar9.1.4.1a Ohne Farben nutzbar9.1.4.2a Ton abschaltbar
include::include/author.adoc[]
include::include/attributes.adoc[]

[[multileiste]]
link:/index.php?a=eb&iid=84[die bisherigen Bewertungen für dieses Prüfschritt]

[.stopFloat]

== Technische Angaben

Version

link:/index.php?a=di&iid=39[bis 10.07.2017] | Aktuell

BITV-Bedingung

1.4.2 Audio-Kontrolle

WCAG-Erfolgskriterium

1.4.2 Audio-Steuerelement

Bewertungsalternativen

ja / eher erfüllt / teilweise erfüllt / eher nicht erfüllt / nein / nicht anwendbar

Bezieht sich auf

einzelne Webseite

Prüfschritt erfüllt

Automatisch abgespielte Tonelemente dauern nicht länger als drei Sekunden, lassen sich abschalten, oder unabhängig von der Systemlautstärke herunter regeln.

Prüfschritt nicht anwendbar

Die Seite hat keine Tonelemente, die automatisch abgespielt werden.

== Was wird geprüft?

Automatisch abgespielte Töne, die nicht nach drei Sekunden enden, sollen abschaltbar sein.

== Warum wird das geprüft?

Automatisch abgespielte Töne stören Nutzer, die sich auf einer Seite mittels Sprachausgabe orientieren.

Falls ein Tonelement nach dem Laden einer Seite automatisch startet, ist es deshalb wichtig, dass es sich über einen am Seitenbeginn befindlichen barrierefreien Mechanismus abschalten, anhalten oder herunter regeln lässt.

== Wie wird geprüft?

=== 1Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn nach dem Laden einer Seite Tonelementen, die auf einer Webseite automatisch länger als drei Sekunden abgespielt werden.

=== [#G60]2Prüfung

Wenn nach Laden der Seite ein Tonelement automatisch abgespielt wird:

* [#G170][#F23]Prüfen, ob der Ton länger als 3 Sekunden dauert.
* Wenn das der Fall ist: Prüfen, ob sich am Seitenbeginn ein Mechanismus (Button, Link, oder Lautstärke-Regler) befindet, mit dem sich der Ton abschalten oder unabhängig von der Systemlautstärke herunter regeln lässt.
* Den Mechanismus bedienen und den Ton abschalten.

Wenn sich die Lautstärke regeln lässt:

* Das Kontrollelement "Sound" aufrufen: Windows-Menü _Start > Alle Apps > Windows System > Systemsteuerung (> Kategorie Hardware und Sound) > Sound_In der Registerkarte "Wiedergabe" die Eigenschaften des Lautsprechers aufrufen und den "Pegel" (in gleichnamiger Registerkarte) anzeigen.
* Ton wieder anschalten oder Seite neu laden, dann die Lautstärke ganz herunterregelnIst der Ton verschwunden?
* Prüfen, ob der Lautstärkeregelung durch den Mechanismus unabhängig von der Systemtonlautstärke ist (Die Lautstärkeeinstellung in "Sound" soll unverändert bleiben)Alternativ kann die Systemlautstärke auch über den das Lautsprechersymbol im einblendbaren Infobereich der Taskleiste geprüft werden.

=== 3Hinweise

* Töne, die nicht nach kurzer Zeit enden, können auch die Verständlichkeit der Sprachausgabe des Abschaltmechanismus störenDeshalb wird auch berücksichtigt, wie störend sich der Ton auswirktSprache oder laute Geräusche etwa stören mehr als eine gleichmäßige Hintergrundmusik.
* Der Mechanismus zum Herunterregeln des Tones darf nicht die Systemtonlautstärke ändern, da dies auch die Tonausgabe von Hilfsmitteln mit Sprachausgabe beeinträchtigen würde.
* Der Mechanismus zum Abschalten oder Herunterregeln des Tons muss sich am Seitenbeginn befinden und soll selbst alle Anforderungen an Barrierefreiheit erfüllen, also etwa ausreichende Kontraste haben und tastaturbedienbar sein.
* Wenn sich der Ton herunterregeln lässt, soll er auf der niedrigsten Stellung des Reglers nicht mehr hörbar sein.
* Es reicht zur Erfüllung dieses Prüfschritts nicht aus, wenn sich der Ton über Tastaturbefehle (etwa die _Escape_-Taste) abschalten lässtDiese Funktion kann sinnvoll sein, wird aber von vielen Nutzern nicht vermutet.

=== 4Bewertung

==== Erfüllt:

* Automatisch abgespielte Töne dauern nicht länger als drei Sekunden oder sind über einen barrierefreien Mechanismus am Seitenbeginn abschaltbar.

==== Nicht voll erfüllt:

* Automatisch abgespielter Ton enthält von Beginn an längere Sprachpassagen oder andere laute und störende Ton-EreignisseDie Sprachausgabe des Abschaltmechanismus kann deshalb nur schlecht wahrgenommen werden.
* Der Mechanismus zum Abschalten des Tons befindet sich nicht unmittelbar am Seitenbeginn.
* Es gibt am Seitenbeginn lediglich eine Erklärung, wie der Ton mittels Tastatur abschaltbar ist.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#audio-control[Guideline 1.4 Distinguishable: Make it easier for users to see and hear content including separating foreground from background.]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#audio-control[1.4.2 Audio Control] (Level A)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G60.html[G60: Playing a sound that turns off automatically within three seconds]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G170.html[G170: Providing a control near the beginning of the Web page that turns off sounds that play automatically]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G171.html[G171: Playing sounds only on user request]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F23.html[F23: Failure of 1.4.2 due to playing a sound longer than 3 seconds where there is no mechanism to turn it off]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F93.html[F93: Failure of Success Criterion 1.4.2 for absence of a way to pause or stop an HTML5 media element that autoplays]

== Quellen

=== Bedeutung der Tonabschaltung nach WCAG 2.1

____
Individuals who use screen reading software can find it hard to hear the speech output if there is other audio playing at the same timeThis difficulty is exacerbated when the screen reader's speech output is software based (as most are today) and is controlled via the same volume control as the soundTherefore, it is important that the user be able to turn off the background soundNote: Having control of the volume includes being able to reduce its volume to zero.

Note: Playing audio automatically when landing on a page may affect a screen reader user's ability to find the mechanism to stop it because they navigate by listening and automatically started sounds might interfere with that navigationTherefore, we discourage the practice of automatically starting sounds (especially if they last more than 3 seconds), and encourage that the sound be started by an action initiated by the user after they reach the page, rather than requiring that the sound be stopped by an action of the user after they land on the page.
____

Quelle: https://www.w3.org/WAI/WCAG21/Understanding/audio-control.html[Audio Control: Understanding SC 1.4.2]
