= Prüfschritt 9.1.3.2 Sinnvolle Reihenfolge
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Seiteninhalte sollen unabhängig von der Darstellung in einer sinnvollen und
brauchbaren Reihenfolge stehen.
Was inhaltlich zusammengehört (etwa eine
Überschrift und die dazugehörigen Inhalte darunter) soll nicht
auseinandergerissen werden.
Mittels CSS versteckte Seiteninhalte sollen deshalb
an sinnvoller Stelle im Seitenquelltext erscheinen.

Dynamische Inhalte, die im Ausgangszustand visuell versteckt sind, sollen auch
für Screenreader verborgen sein, damit sie nicht die Lesereihenfolge stören.

Ausschlaggebend bei der Prüfung ist nicht, ob die Seite in der Ansicht ohne
CSS visuell eine verständliche Lesereihenfolge hat.
Ausschlaggebend ist, ob *bei eingeschaltetem CSS* die Reihenfolge beim
linearen Lesen mit dem Screenreader sinnvoll ist.

== Warum wird das geprüft?

Screenreader lesen die Elemente, die auf dem Bildschirm in der Fläche
angeordnet sind, *nacheinander* vor - und zwar in der Reihenfolge, in der sie
im Quellcode stehen.
Die Reihenfolge der Elemente muss also gut verständlich und nutzbar sein.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn CSS verwendet wird, insbesondere für die
Positionierung von Inhalten, und wenn Inhalte dynamisch eingeblendet oder
eingefügt werden.

=== 2. Prüfung

==== 2.1 Lesereihenfolge für Screenreader-Nutzer

Seite im
http://www.bitvtest.de/bitvtest/das_testverfahren_im_detail/werkzeugliste.html#firefox[
Firefox] aufrufen und in der
http://www.bitvtest.de/bitvtest/das_testverfahren_im_detail/werkzeugliste.html#webdeveloper[
Web Developer Toolbar] _CSS > Disable All Styles_ wählen.
Bleibt die logische Reihenfolge von sichbaren Seiten-Inhalten nach dem
Abschalten von CSS erhalten?
CSS wieder einschalten.
Die Reihenfolge der Inhalte mit dem Screenreader NVDA im
Lesemodus (Pfeiltaste nach unten) überprüfen.
Gibt es Linearisierungsprobleme, die bei der Screenreader-Nutzung störend sind?
Werden visuell versteckte Inhalte
vorgelesen?

==== 2.2 Prüfung der Linearisierbarkeit von Layouttabellen

Wenn Tabellen für das Layout (die Anordnung von Elementen auf der Seite)
eingesetzt werden, müssen sie linearisierbar sein.

Seite im Firefox anzeigen.
Mittels _Web Developer Toolbar_ die Funktion _Miscellaneous > Linearize page_
die Struktur der Seite und damit die der Layouttabelle linearisieren.
Prüfen, ob die lineare Reihenfolge der angezeigten Inhalte sinnvoll ist.

=== 3. Hinweise

==== Reihenfolge von Inhalten

Die visuelle Anordnung der Seitenelemente kann von der Reihenfolge im
Quelltext abweichen.
Sichtbare Inhalte sollen in der Regel in der gleichen
Reihenfolge wie im Quelltext stehen.
Bei der Nutzung von CSS Layout-Technik
`grid` kommt es hier häufiger zu Problemen.

==== Dynamische Elemente

Häufig und deshalb auch zu akzeptieren sind durch CSS versteckte Inhalte etwa
Ausklappmenüs oder Popup-Elemente, die bei der Ansicht ohne CSS sichtbar
werden.
Problematisch sind sie für Screenreader-Nutzer vor allem dann, wenn sie
zwar visuell mittels CSS versteckt werden, aber vom Screenreader im Lesemodus
dennoch erreicht werden, z. B. weil sie nicht mit geeigneten Mitteln wie
`display:none` versteckt wurden.

*Zu WAI-ARIA:* Die Verwendung von WAI-ARIA spielt in diesem Prüfschritt keine
Rolle.

=== 4. Bewertung

==== Nicht voll erfüllt

* Versteckte Texte oder dynamische Einfügungen erscheinen an verwirrender
  Stelle beim Lesen mit dem Screenreader.

== Einordnung des Prüfschritts

=== Abgerenzung zu anderen Prüfschritten

* _Custom controls_, die etwa Benutzerschnittstellen aus positionierten `div`s
  mit Hintergrundbildern erzeugen, werden bereits in einer Reihe von
  bestehenden Prüfkriterien implizit geprüft, etwa
ifdef::env_embedded[9.2.4.7 "Aktuelle Position des Fokus deutlich",]
ifndef::env_embedded[]
  <<9.2.4.7 Aktuelle Position des Fokus deutlich.adoc#,9.2.4.7 Aktuelle
  Position des Fokus deutlich>>,
endif::env_embedded[]
  und
ifdef::env_embedded[9.4.1.2 "Name, Rolle, Wert verfügbar".]
ifndef::env_embedded[]
  <<9.4.1.2 Name-Rolle-Wert verfügbar.adoc#,9.4.1.2 Name, Rolle, Wert
  verfügbar>>.
endif::env_embedded[]
* Die korrekte *Reihenfolge im Quelltext* bei dynamisch generierten oder
  eingeblendeten Elementen ist Gegenstand von Prüfschritt
ifdef::env_embedded[9.2.4.3 "Schlüssige Reihenfolge bei der Tastaturbedienung".]
ifndef::env_embedded[]
  <<9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung.adoc#,9.2.4.3
  Schlüssige Reihenfolge bei der Tastaturbedienung>>.
endif::env_embedded[]

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131#adaptable[
  Guideline 1.3 Adaptable: Create content that can be presented in different
  ways (for example simpler layout) without losing information or structure.]

==== Success criterio

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131#meaningful-sequence[
  1.3.2 Meaningful Sequence] (Level A)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G57.html[
  G57 Ordering the content in a meaningful sequence]

==== CSS Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/css/C6.html[
  C6 Positioning content based on structural markup]
* https://www.w3.org/WAI/WCAG21/Techniques/css/C8.html[
  C8 Using CSS letter-spacing to control spacing within a word]
* https://www.w3.org/WAI/WCAG21/Techniques/css/C27.html[
  C27: Making the DOM order match the visual order]

==== Scripting Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR21.html[
  SCR21: Using functions of the Document Object Model (DOM) to add content to
  a page]
* https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR28.html[
  SCR28: Using an expandable and collapsible menu to bypass block of content]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F1.html[
  F1: Failure of Success Criterion 1.3.2 due to changing the meaning of
  content by positioning information with CSS]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F32.html[
  F32: Failure of Success Criterion 1.3.2 due to using white space characters
  to control spacing within a word]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F34.html[
  F34: Failure of Success Criterion 1.3.1 and 1.3.2 due to using white space
  characters to format tables in plain text content]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F49.html[
  F49 Failure of Success Criterion 1.3.2 due to using an HTML layout table
  that does not make sense when linearized]

== Quellen

* https://gridbyexample.com/[Grid by example] (Rachel Andrew)
