= Prüfschritt 9.1.1.1a Alternativtexte für Bedienelemente9.1.1.1b Alternativtexte für Grafiken und Objekte9.1.1.1c Leere alt-Attribute für Layoutgrafiken9.1.1.1d Alternativen für CAPTCHAs9.1.2.1a Alternativen für Audiodateien und stumme Videos9.1.2.2a Aufgezeichnete Videos mit Untertiteln9.1.2.3a Audiodeskription oder Volltext-Alternative für Videos9.1.2.4a Videos (live) mit Untertiteln9.1.2.5a Audiodeskription für Videos9.1.3.1a HTML-Strukturelemente für Überschriften9.1.3.1b HTML-Strukturelemente für Listen9.1.3.1c HTML-Strukturelemente für Zitate9.1.3.1d Inhalt geglieder9.1.3.1e Datentabellen richtig aufgebaut9.1.3.1f Zuordnung von Tabellenzellen9.1.3.1g Kein Strukturmarkup für Layouttabellen9.1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar9.1.3.2a Sinnvolle Reihenfolge9.1.3.3a Ohne Bezug auf sensorische Merkmale nutzbar9.1.3.4a Keine Beschränkung der Bildschirmausrichtung9.1.3.5a Eingabefelder zu Nutzerdaten vermitteln den Zweck9.1.4.10a Inhalte brechen um9.1.4.11a Kontraste von Grafiken und grafischen Bedienelementen ausreichend9.1.4.12a Textabstände anpassbar9.1.4.13a Eingeblendete Inhalte bedienbar9.1.4.1a Ohne Farben nutzbar9.1.4.2a Ton abschaltbar9.1.4.3a Kontraste von Texten ausreichend
include::include/author.adoc[]
include::include/attributes.adoc[]

[[multileiste]]
link:/index.php?a=eb&iid=86[die bisherigen Bewertungen für dieses Prüfschritt]

[.stopFloat]

== Technische Angaben

Version

link:/index.php?a=di&iid=40[bis 10.07.2017] | Aktuell

BITV-Bedingung

1.4.3 Kontrast

WCAG-Erfolgskriterium

1.4.3 Kontrast (Minimum)

Bewertungsalternativen

ja / eher erfüllt / teilweise erfüllt / eher nicht erfüllt / nein / nicht anwendbar

Bezieht sich auf

einzelne Webseite

Prüfschritt erfüllt

Texte haben ausreichende Helligkeitskontraste.

Prüfschritt nicht anwendbar

Texte sind nicht vorhanden.

== Was wird geprüft?

Alle Texte der Seite sollen ausreichende Helligkeitskontraste habenSie sollen auch für farbfehlsichtige Benutzer wahrnehmbar seinBei Seiten, die eine ausreichend kontrastreiche Version über einen Styleswitcher anbieten, wird auch geprüft, ob der Ausgangszustand Mindestanforderungen an Schriftkontraste erfüllt.

== Warum wird das geprüft?

Wenn Vordergrund- und Hintergrundfarbe sich in der Helligkeit ähneln, haben sie unter Umständen zu wenig Kontrast, wenn sie mit Schwarzweiß-Monitoren oder von Menschen mit verschiedenen Arten von Farbenschwäche betrachtet werden.

Die Ausgabe einer kontrastreicheren Seite durch einen Styleswitcher darf nicht dazu führen, dass die Standardseite sich nicht mehr um nutzbare Kontraste kümmertDenn viele Nutzer nehmen das Schaltelement Styleswitcher nicht wahr, verstehen die Funktion nicht, oder möchten die Seite lieber im Ausgangszustand nutzen.

== Wie wird geprüft?

=== 1Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Seite Text enthält.

Grafische Schriften sind ebenfalls Gegenstand des Prüfschritts.

=== 2Prüfung

==== 2.1Prüfung der Textkontraste der Standardversion

Prüfung nicht festgelegter FarbenÜber das Bookmarklet https://testen.bitv-test.de/bookmarklets.html["Vorder-und Hintergrundfarbe definiert"] oder ein User Stylesheet (`html {background-color:black;color:white})` prüfen, ob für jedes Element, für das eine Vordergrundfarbe festgelegt wurde, auch eine Hintergrundfarbe festgelegt ist und umgekehrt.
SichtpüfungSind die Schriftkontraste stark genug?
Im Zweifel den http://www.bitvtest.de/bitvtest/das_testverfahren_im_detail/werkzeugliste.html#analyser[Contrast Analyser] öffenSchriftfarbe und Hintergrundfarbe auswählen und Kontrastverhältnis prüfen.
In der http://www.bitvtest.de/bitvtest/das_testverfahren_im_detail/werkzeugliste.html#webdeveloper[Web Developer Toolbar] die Funktion _Informationen > Elementinformationen einblenden_ aktivieren.
Text, der überprüft werden soll, anklickenIm eingeblendeten Fenster "Elementinformationen" im Bereich "Text" wird die jeweilige Schriftgröße in Pixeln angegeben.
Mit Hilfe des Contrast Analysers im Bereich _Vordergrund_ mit der Pipette die Vordergrundfarbe auswählen, dann im Bereich _Hintergrund_ die HintergrundfarbeFür Schriftgrößen unter 24 px (beziehungsweise 18,7 px bei fetter Schrift) prüfen, ob das Kontrastverhältnis bei 4,5:1 oder größer liegtFür große Schriften prüfen, ob das Kontrastverhältnis bei 3:1 oder größer liegt.
Bei andersfarbigen Fließtextlinks ohne sonstige Unterschiede in der Auszeichung, wie etwa Unterstreichung, prüfen, ob das Kontrastverhältnis zum Standardfließtext mindestens 3:1 beträgt.

==== 2.2Styleswitcher-Prüfung, Prüfung der Textkontraste der alternativen Ansicht

Wenn die Kontraste der Standardversion nicht die Sollwerte erfüllen und die Seite eine kontrastreichere Ansicht über einen Styleswitcher anbietet:

Textkontrast des Styleswitcher-Schaltelements prüfenDas Kontrastverhältnis muss 4,5:1 oder besser sein, und auch die anderen Anforderungen (zum Beispiel tastaturbedienbar, ohne Stylesheets nutzbar) müssen erfüllt seinSonst abbrechen.
Alternative kontrastreichere Ansicht über den Styleswitcher aufrufen.
Textkontraste der alternativen Ansicht prüfen (wie in 2.1 _Prüfung der Textkontraste der Standardversion_).

=== 3Hinweise

==== 3.1Allgemeine Hinweise

* Elemente, die unterschiedliche Zustände haben können, sollten immer ausreichend kontrastierenAlso zum Beispiel: auch die farblich hervorgehobene, aktuell ausgewählte Menüoption; auch in einer anderen Farbe dargestellte, besuchte LinksFür die Bewertung entscheidend ist der jeweils *schlechtere* Helligkeitskontrast.
* Die einzige Ausnahme, weil hier der gezielte Wechsel zwischen den beiden Zuständen verhältnismäßig einfach ist: die Hervorhebung des Maus- und TastaturfokusHier soll zunächst geprüft werden, in welchem Zustand (im Fokus/nicht im Fokus) der Helligkeitskontrast besser istDieser in Hinblick auf den Helligkeitskontrast bessere Zustand muss den allgemeinen Grenzwert von 4,5:1 erfüllenDas Kontrastverhältnis des zweiten Zustandes muss über 3:1 liegen.
* Schwache Kontraste können zweckmäßig sein, sie können den Umgang mit einer Webseite erleichternEin Beispiel dafür: Funktionen, die prinzipiell vorgesehen, aktuell aber nicht verfügbar sind, werden schwach kontrastierend dargestelltDas ist akzeptabel, wenn das ausgeblendete Element für die Orientierung und Bedienung nicht erforderlich istDer Prüfschritt ist daher auf die Beschriftungen ausgeblendeter, deaktivierter Bedienelemente in der Regel nicht anwendbar
* Bei Bereichen, die mit Farbwechseln auf den Mauszeiger reagieren, kann ein Screenshot helfen, den Farbwert im "Ruhezustand" zu ermittelnAlternativ kann man den Fokuszustand über Tastaturbedienung erzeugen und dann den Kontrast mit der Pipette des Contrast Analyser messen.
* Wenn Kontraste dünner Schriften zu prüfen sind, gegebenenfalls Schrift vergrößern und die Schriftenglättung ausschalten.
* Sollen die Farbwerte sehr kleiner Bereiche (feine Schriften oder kleine Icons) ermittelt werden, ist es unter Umständen einfacher, ein Screenshot zu machen und die leistungsfähigeren Zoom- und Pipettenwerkzeuge eines Bildbearbeitungsprogramms zu nutzen.
* Der Farbkontrast von Textvorbelegungen von Formularfeldern oft nicht die Mindest-Anforderung von 4,5:1.

==== 3.2Hinweise zur Prüfung von Seiten mit Styleswitcher

Die Kontrastprüfung auf durch Styleswitcher aufgerufenen kontrastreicheren Ansicht erfolgt nur unter folgenden Bedingungen:

* Das Styleswitcher-Schaltelement (oder der direkte Link zu einer Styleswitcher-Seite) ist deutlich sichtbar am Seitenbeginn platziert.
* Das Schaltelement hat ein Kontrastverhältnis von mindestens 4.5:1 und erfüllt auch die anderen Anforderungen an Barrierefreiheit (es ist zum Beispiel tastaturbedienbar und ohne Stylesheets nutzbar)
* Die alternative kontrastreichere Ansicht muss dieselben Informationen und dieselbe Funktionalität aufweisen wie die Ausgangsansicht.

==== 3.3Hinweise zur Messung des Kontrastverhältnisses

* Für die Bewertung zählt das Kontrastverhältnis (_relative luminosity_) nach einer in den WCAG 2.1 definierten Formel.
* Die Prüfung der Kontraste für normalen Text und großen Text orientiert sich an den gemessenen Werten der Schriftgröße in Pixel (http://www.bitvtest.de/bitvtest/das_testverfahren_im_detail/werkzeugliste.html#webdeveloper[Web Developer Toolbar], _Funktion Elementinformationen einblenden_), denn eine Messung der tatsächlich dargestellten Punktgröße auf dem Bildschirm mit einem Typometer ist nicht praktikabelBei einer Bildschirmauflösung von 96 dpi entsprechen 18 Punkt etwa 24 Pixeln, 14 Punkt entsprechen etwa 18,7 Pixeln.
* Die Messung des Pixel-Äquivalents ist dadurch gerechtfertigt, dass die bisher getesteten _User Agents_ die Auszeichnung in Pixel und Punkt analog behandeln (im Verhältnis 4:3), also unabhängig von der Bildschirmauflösung, unter der der Text angezeigt wirdRichtiger wäre es, wenn _User Agents_ die Bildschirmauflösung auswerten würden, um die Ausgabegröße zu berechnen (also mehr Pixel pro Punkt bei höher auflösenden Bildschirmen)Für die Prüfung maßgeblich ist der Referenzwert von 96 dpi Bildschirmauflösung, für den die Entsprechung auf jeden Fall gilt.

=== 4Bewertung

==== Erfüllt:

* Das Kontrastverhältnis (_contrast ratio_) zwischen Vorder- und Hintergrundfarbe liegt für Texte unter 18 Punkt (beziehungsweise für fette Texte unter 14 Punkt) bei mindestens 4,5:1.
* Das Kontrastverhältnis (_contrast ratio_) zwischen Vorder- und Hintergrundfarbe liegt bei Texten in großer Schriftgröße (18 Punkt und größer, 14 Punkt und größer bei fetter Schrift) bei mindestens 3:1Das Kontrastverhältnis des schlechteren Zustands des Maus- und Tastaturfokus liegt über 3:1.
* Wenn die Anforderung nur über eine alternative Ansicht erfüllt wird, erfüllt der Styleswicher selbst die Kontrastforderung von 4,5:1 und andere Anforderungen an Barrierefreiheit.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten

Prüfschritt link:/index.php?a=di&iid=109&s=n[1.4.11a] "Kontraste von Grafiken und Bedienelementen ausreichend" behandelt den Kontrast von GrafikenSchriftgrafiken (zur Definition vergleiche auch Prüfschritt link:/index.php?a=di&iid=54&s=n[1.4.5a]) werden jedoch in diesem Prüfschritt bewertet.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#distinguishable[Guideline 1.4 Distinguishable: Make it easier for users to see and hear content including separating foreground from background]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#contrast-minimum[1.4.3 Contrast (Minimum)] (Level AA)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G18.html[G18: Ensuring that a contrast ratio of at least 4.5:1 exists between text (and images of text) and background behind the text]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G145.html[G145: Ensuring that a contrast ratio of at least 3:1 exists between text (and images of text) and background behind the text]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G148.html[G148: Not specifying background color, not specifying text color, and not using technology features that change those defaults]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G174.html[G174: Providing a control with a sufficient contrast ratio that allows users to switch to a presentation that uses sufficient contrast]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F83.html[F83: Failure of Success Criterion 1.4.3 and 1.4.6 due to using background images that do not provide sufficient contrast with foreground text (or images of text)]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F24.html[F24: Failure of Success Criterion 1.4.3, 1.4.6 and 1.4.8 due to specifying foreground colors without specifying background colors or vice versa]

== Quellen

=== W3C zum Zusammenhang zwischen `px` und `pt`:

https://www.w3.org/TR/css3-values/#absolute-lengths[CSS Values and Units Module Level 3: 5.2 Absolute Lengths]

== Fragen zu diesem Prüfschritt

=== Das Ergebnis der http://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html#visual-audio-contrast-contrast-69-head[WCAG 2.1 Formel zur Messung des Kontrastverhältnisses] entspricht oft nicht dem subjektiven EindruckWie zuverlässig ist es?

Zwei Punkte sind hier zu beachten:

Der Helligkeitskontrast ist nur einer von drei Einflussgrößen für den GesamtkontrastInsofern ist klar, dass das Ergebnis für den Helligkeitskontrast nicht dem subjektiven Eindruck entsprichtEs soll gar nicht dem subjektiven Gesamteindruck entsprechen, denn schließlich geht es darum, ob die Helligkeitsunterschiede der Farben für sich genommen ausreichend kontrastierenWenn man normalsichtig ist, entspricht der subjektive Eindruck der Graustufenansicht dagegen schon eher dem Formelergebnis.
Farben benachbarter Flächen beeinflussen die Wahrnehmung, kleine und dünne Schriften erscheinen kontrastärmer, es gibt Überstrahleffekte, möglicherweise werden die Kontraste durch Schriftenglättung abgeschwächtDie Formel berücksichtigt all diese Faktoren nichtZumindest wenn es um Texte geht, ist dies auch angemessenDenn die genannten Einflüsse stehen nicht fest, sie hängen zum Beispiel von der gewählten Schriftgröße ab.

Für die Prüfung bedeutet das: Wer mit der formelbasierten Bewertung von Helligkeitskontrasten noch keine Erfahrungen hat, kann sich nicht auf seinen subjektiven Eindruck verlassenEr muss die Formel fast auf alle Farbkombinationen anwenden.
