= Prüfschritt 9.1.3.3 Ohne Bezug auf sensorische Merkmale nutzbar
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Verweise auf Inhalte der Seite sollen *nicht ausschließlich* sensorische
Merkmale wie Farbe, Form oder Position nutzen, sondern auch ohne bestimmte
Sinneswahrnehmungen verständlich sein (etwa durch den Verweis
die Überschrift von Inhalten).

== Warum wird das geprüft?

Auch der Bezug auf die Form, Farbe oder Position von bestimmten Seiteninhalten
ist für blinde Nutzer und auch Nutzer, die die Seite ohne das mitgelieferte
Stylesheet oder auf anderen Ausgabegeräten sehen, nicht brauchbar.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

=== 2. Prüfung

==== 2.1 Textliche Bezüge auf Farben und andere sensorische Merkmale

Prüfen, ob textliche Verweise auf Seiteninhalte diese nur über die Angabe
sensorischer Merkmale wie Farbe, Form, Größe, Position, oder Orientierung
identifizieren und nicht auch sinnesunabhängig, etwa durch Nennung einer
Überschrift oder eines Labels.
Beispiele für Bezugnahmen, die nur sensorische Merkmale nennen:

* Klicken Sie auf den grünen Knopf, um ...
* Über die runde Taste können Sie...
* Der rot eingerahmte Kasten enthält Infos zu ...
* Klicken Sie im Menü rechts...
* In der breiten Spalte steht...
* Die rechtsbündigen Absätze zeigen..

Solche Bezugnahmen sind ohne die Wahrnehmung sensorischer Merkmale nicht
nachzuvollziehen.

Dies gilt auch für Alternativtexte von Informationsgrafiken: sie sollen alle
für das Verständnis relevanten Informationen nicht allein durch Bezug auf
sensorische Merkmale vermitteln (vergleiche Failure
http://www.w3.org/TR/WCAG20-TECHS/F13.html[F13]).

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten

Prüfschritt
ifdef::env_embedded[9.1.4.1 "Ohne Farben nutzbar"]
ifndef::env_embedded[]
  <<9.1.4.1 Ohne Farben nutzbar.adoc#,9.1.4.1 Ohne Farben nutzbar>>
endif::env_embedded[]
behandelt die Verwendung von Farbe zur Übermittlung von Information, hier
dagegen geht es um Form, Position, oder textliche Bezüge.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guidelines

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131%2C132#adaptable[
  Guideline 1.3 Adaptable: Create content that can be presented in different
  ways (for example simpler layout) without losing information or structure.]

==== Success criterion

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131%2C132#sensory-characteristics[
  1.3.3 Sensory Characteristics] (Level A)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G96.html[
  G96 Providing textual identification of items that otherwise rely only on
  sensory information to be understood]

===== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F14.html[
  F14: Failure of Success Criterion 1.3.3 due to identifying content only by
  its shape or location]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F26.html[
  F26: Failure of Success Criterion 1.3.3 due to using a graphical symbol
  alone to convey information]

== Quellen

[.BLOCK_LANG_EN]
=== Sensory Characteristics: Understanding SC 1.3.3

[.BLOCK_LANG_EN]
____
People who are blind and people who have low vision may not be able to
understand information if it is conveyed by shape and/or location.
Providing additional information other than shape and/or location will allow
them to understand the information conveyed by shape and/or alone.
____

(https://www.w3.org/WAI/WCAG21/Understanding/sensory-characteristics.html)
