= Prüfschritt 9.1.3.1d Inhalt gegliedert
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Absätze sind mit geeigneten Strukturelementen ausgezeichnet.

Hervorhebungen in Texten sind mit `strong` oder `em` ausgezeichnet.

Text-Inhalt wird nicht per CSS eingebunden.

== Warum wird das geprüft?

Die Unterteilung in kleinere Einheiten erleichtert die Handhabung und das
Verständnis.

Die Verwendung der vorgesehenen HTML-Strukturelemente stellt sicher, dass
diese Unterteilung unabhängig von der Präsentation, auf einer abstrakten Ebene
festgelegt und zugänglich ist.
Benutzer, die mit der vorgegebenen visuellen Präsentation der Elemente 
auf der Seite nichts anfangen können, finden sich dann trotzdem zurecht, 
oder sie können eine eigene, besser passende Präsentation anwenden.

Die Auszeichnungen `strong` und `em` sind allgemein und nicht
darstellungsbezogen (wie `b`, `i` oder eine nur mit CSS realisierte visuelle
Hervorhebung).

Werden Inhalte per CSS eingebunden, sind sie für Nutzer Assistiver
Technologien nicht verfügbar.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn es auf der Seite Absätze gibt.

=== 2. Prüfung

==== 2.1 Prüfung mit Bookmarklet

Seite in
https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste.html#c1078[
Firefox] aufrufen.
Das Bookmarklet
http://www.bitvtest.de/bitvtest/das_testverfahren_im_detail/werkzeugliste.html#gegliedert[
Inhalte gegliedert] aufrufen.
Prüfen, ob Absätze mit `p` ausgezeichnet sind.
Prüfen, ob Hervorhebungen in Texten mit `strong` oder `em` ausgezeichnet sind.

==== 2.2 Missbräuchliche Nutzung von typographischen Zeichen

Prüfen, ob Leerzeichen (``&nbsp;``) zur Formatierung von Text benutzt werden
(etwa zur Schaffung von Spalten).
Prüfen, ob typographische Zeichen, etwa Reihen von Bindestrichen, zur
Erzeugung von Trennlinien eingesetzt werden.

==== 2.3 Einbindung von Text-Inhalt mit Hilfe von CSS

Prüfen, ob über die Pseudo-Elemente `:after` bzw. `:before` und der
``"content"``-Eigenschaft Inhalt eingebunden wurde.

=== 3. Hinweise

* Es soll nicht bewertet werden, ob die vorhandene, sichtbare Gliederung der
  Seite sinnvoll ist, sondern nur, ob sie mit geeigneten
  HTML-Strukturelementen umgesetzt wurde.
* Die Verwendung von HTML-Strukturelementen für Tabellen, Überschriften,
  Listen und Zitate ist bereits durch andere Prüfkriterien abgedeckt.
* Die Inhalte von Iframes werden ebenso überprüft wie andere Seiteninhalte.
  Dazu muss unter Umständen der Iframe in einem neuen Fenster geladen werden.
* Wenn es sich bei dem über CSS eingebundenen Inhalt um Überschriften,
  Listen oder Tabellen handelt, wird dies in den entsprechenden Prüfschritten
  bewertet.

=== 4. Bewertung

==== Erfüllt

* Alle Absätze sind mit `p` ausgezeichnet, für Hervorhebungen im Text wird
  `strong` und `em` verwendet.

==== Nicht voll erfüllt

* Für Absätze werden anstelle von `p` doppelte Zeilenumbrüche (`br`) verwendet.
* Leerzeichen (``&nbsp;``) werden zur Schaffung von Spalten eingesetzt.
* Text-Inhalt wird mit Hilfe von CSS eingebunden.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten

Andere auf Strukturierung bezogenen Prüfkriterien sind:

* Prüfschritt
ifdef::env_embedded[9.1.3.1a "HTML-Strukturelemente für Überschriften"]
ifndef::env_embedded[]
  <<9.1.3.1a HTML-Strukturelemente für Überschriften.adoc#,9.1.3.1a
  HTML-Strukturelemente für Überschriften>>
endif::env_embedded[]
* Prüfschritt
ifdef::env_embedded[9.1.3.1b "HTML-Strukturelemente für Listen"]
ifndef::env_embedded[]
  <<9.1.3.1b HTML-Strukturelemente für Listen.adoc#,9.1.3.1b
  HTML-Strukturelemente für Listen>>
endif::env_embedded[]
* Prüfschritt
ifdef::env_embedded[9.1.3.1c "HTML-Strukturelemente für Zitate"]
ifndef::env_embedded[]
  <<9.1.3.1c HTML-Strukturelemente für Zitate.adoc#,9.1.3.1c
  HTML-Strukturelemente für Zitate>>
endif::env_embedded[]
* Prüfschritt
ifdef::env_embedded[9.1.3.1e "Datentabellen richtig aufgebaut"]
ifndef::env_embedded[]
  <<9.1.3.1e Datentabellen richtig aufgebaut.adoc#,9.1.3.1e Datentabellen
  richtig aufgebaut>>
endif::env_embedded[]

Die Textalternative für Font-Icons wird im Prüfschritt
ifdef::env_embedded[9.1.1.1a "Alternativtexte für Bedienelemente"]
ifndef::env_embedded[]
  <<9.1.1.1a Alternativtexte für Bedienelemente.adoc#,9.1.1.1a
  Alternativtexte für Bedienelemente>>
endif::env_embedded[]
und
ifdef::env_embedded[9.1.1.1b "Alternativtexte für Grafiken und Objekte"]
ifndef::env_embedded[]
  <<9.1.1.1b Alternativtexte für Grafiken und Objekte.adoc#,9.1.1.1b
  Alternativtexte für Grafiken und Objekte>>
endif::env_embedded[]
geprüft.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131#adaptable[
  Guideline 1.3 Adaptable: Create content that can be presented in different
  ways (for example simpler layout) without losing information or structure]

==== Success criterion

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131#info-and-relationships[
  1.3.1 Info and Relationships] (Level A)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G115.html[
  G115: Using semantic elements to mark up structure]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G140.html[
  G140: Separating information and structure from presentation to enable
  different presentations]

===== HTML Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/html/H49.html[
  H49: Using semantic markup to mark emphasized or special text]

===== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F2.html[
  F2: Failure of Success Criterion 1.3.1 due to using changes in text
  presentation to convey information without using the appropriate markup or
  text]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F33.html[
  F33: Failure of Success Criterion 1.3.1 and 1.3.2 due to using white space
  characters to create multiple columns in plain text content]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F43.html[
  F43: Failure of Success Criterion 1.3.1 due to using structural markup in a
  way that does not represent relationships in the content]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F48.html[
  F48: Failure of Success Criterion 1.3.1 due to using the pre element to
  markup tabular information]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F87.html[
  F87: Failure of Success Criterion 1.3.1 due to inserting non-decorative
  content by using :before and :after pseudo-elements and the 'content' property
  in CSS]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F92.html[
  F92: Failure of Success Criterion 1.3.1 due to the use of role presentation
  on content which conveys semantic information]
