= Prüfschritt 9.1.4.4 Text auf 200% vergrößerbar
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Text soll um bis zu 200 Prozent vergrößert werden können, ohne dass dabei Inhalt oder Funktionalität verloren geht. Mindestens eine der folgenden Voraussetzungen soll erfüllt
sein:

* Mit der Zoom-Funktion des Browsers kann die Schrift auf 200% vergrößert werden (dabei bricht die Seite häufig in ein neues Layout um)
* Über ein Bedienelement oben auf der Seite kann die Schriftgröße vergrößert werden

== Warum wird das geprüft?

Benutzer sollen die Schriftgröße nach ihren Bedürfnissen einstellen können. Die gängigen Desktop-Browser bieten heutezutage die Zoom-Vergrößerung des gesamte Layouts, bei der die Seite häufig in eine responsive Ansicht umbricht.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Seite Text enthält.

=== 2. Prüfung

==== 2.1 Prüfung der Zoomvergrößerung über Browser-Einstellungen

. Seite in https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste.html#firefox[Firefox] aufrufen.
. Falls nötig unter _Ansicht > Zoom_ die Option _Nur Text zoomen_ deaktivieren.
. Mithilfe der https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste.html#webdeveloper[Web Developer Toolbar] die Browserfenstergröße auf 1280x768 einstellen (_Größe ändern > ..._).
. Sechs Mal die Tastenkombination _Strg + +_ drücken, um das Layout auf 200% zu zoomen (alternativ sechs mal _Ansicht > Zoom > Vergrößern_ wählen).
. Prüfen, ob weiterhin alle Inhalte ohne Überlagerungen dargestellt werden und alle Funktionalitäten bedienbar bleiben.
. Seite im https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste.html#chrome[Chrome Browser] aufrufen.
. Die Browserfenstergröße auf 1280x768 einstellen (entsprechend Firefox-Browserfenster).
. Über des Einstellungs-Menü und die Option Zoomen _200%_ auswählen.
. Prüfen, ob weiterhin alle Inhalte ohne Überlagerungen dargestellt werden und alle Funktionalitäten bedienbar bleiben.

==== 2.2 Prüfung der Schriftvergrößerung durch Bedienelemente auf der Seite

Wenn die Seite eigene Bedienelemente bereithält, um die Schriftgröße zu vergrößern:

. Prüfen, ob die Bedienelemente für Schriftvergrößerung deutlich sichtbar im oberen Bereich der Seite angeboten werden.
. Prüfen, ob die Schrift mit Hilfe der auf der Seite angebotenen Bedienelemente schrittweise vergrößert werden kann. In der Regel wird durch diese Vergrößerungsoption keine Vergrößerung auf 200% erreicht. Eigene Bedienelemente erfüllen diesen Prüfschritt dann nicht, eine andere Vergrößerungsmöglichkeit muss 200% erreichen.
. Prüfen, ob sich über die angebotenen Bedienelemente die Ausgangsschriftgröße wiederherstellen lässt.

=== 3. Hinweise

==== 3.1 Hinweise zur Prüfung der Zoomvergrößerung über Browser-Einstellungen

* Wenn bei Nutzung der Zoom-Funktion am Desktop das Layout für mobile Geräte ausgeliefert wird, sollten auch in diesem Layout alle Anforderungen der Barrierefreiheit erfüllt sein Probleme in dieser Ansicht werden bei den jeweils relevanten Prüfschritten bewertet.

==== 3.2 Hinweise zur Prüfung der Schriftvergrößerung durch Bedienelemente auf der Seite

Die Prüfung der Schriftvergrößerung durch Bedienelemente erfolgt nur unter folgenden Bedingungen:

* Das Bedienelement erfüllt alle Anforderungen an Barrierefreiheit (es ist zum Beispiel tastaturbedienbar, erfüllt die Kontrastanforderungne etc.)

=== 4. Bewertung

==== Erfüllt

* Der Text lässt sich mit mindestens einer Technik auf 200 % vergrößern, ohne dass es zu Überlappungen oder abgeschnittenen Inhalten kommt und ohne dass Funktionalitäten beeinträchtigt werden.

==== Nicht voll erfüllt

* Bedienelemente für die Schriftvergrößerung werden auf der Seite angeboten und können den Text auf 200% vergrößern, aber sie sind nicht oben auf der Seite platziert, es kommt bei der Nutzung zu Überlappungen von Text, oder Inhalte werden abgeschnitten.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten

* Mangelnde Vergrößerbarkeit von Schriftgrafiken: siehe Prüfschritt
ifdef::env_embedded[9.1.4.5 "Verzicht auf Schriftgrafiken"]
ifndef::env_embedded[]
<<9.1.4.5 Verzicht auf Schriftgrafiken.adoc#,9.1.4.5 Verzicht auf
Schriftgrafiken>>
endif::env_embedded[]

=== Einordnung des Prüfschritts nach WCAG 2.2

==== Guideline

* https://www.w3.org/TR/WCAG21/#distinguishable[
  Guideline 1.4 Distinguishable: Make it easier for users to see and hear
  content including separating foreground from background]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#resize-text[
  1.4.4 Resize text] (Level AA)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G146.html[
  G146: Using liquid layout]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G178.html[
  G178: Providing controls on the Web page that allow users to incrementally
  change the size of all text on the page up to 200 percent]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G179.html[
  G179: Ensuring that there is no loss of content or functionality when the
  text resizes and text containers do not change their width]

===== CSS-Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/css/C12.html[
  C12: Using percent for font sizes]
* https://www.w3.org/WAI/WCAG21/Techniques/css/C13.html[
  C13: Using named font sizes]
* https://www.w3.org/WAI/WCAG21/Techniques/css/C14.html[
  C14: Using em units for font sizes]
* https://www.w3.org/WAI/WCAG21/Techniques/css/C20.html[
  C20: Using relative measurements to set column widths so that lines can
  average 80 characters or less when the browser is resized]
* https://www.w3.org/WAI/WCAG21/Techniques/css/C28.html[
  C28: Specifying the size of text containers using em units]
* https://www.w3.org/WAI/WCAG21/Techniques/css/C29.html[
  C29: Using a style switcher to provide a conforming alternate version]

===== Client-side Scripting Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR34.html[
  SCR34: Calculating size and position in a way that scales with text size]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F69.html[
  F69: Failure of Success Criterion 1.4.4 when resizing visually rendered tex
  up to 200 percent causes the text, image or controls to be clipped,
  truncated or obscured]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F80.html[
  F80: Failure of Success Criterion 1.4.4 when text-based form controls do not
  resize when visually rendered text is resized up to 200%]

== Quellen

=== WCAG 2.1 über die Skalierung von Text

[.BLOCK_LANG_EN]
____
The scaling of content is primarily a user agent responsibility.
User agents that satisfy UAAG 1.0 Checkpoint 4.1 allow users to configure text
scale.
The author's responsibility is to create Web content that does not prevent the
user agent from scaling the content effectively.
Authors may satisfy this Success Criterion by verifying that content does not
interfere with user agent support for resizing text, including text-based
controls, or by providing direct support for resizing text or changing the
layout.
An example of direct support might be via server-side script that can be used
to assign different style sheets.
____

(https://www.w3.org/WAI/WCAG21/Understanding/resize-text.html[
Resize text: Understanding SC 1.4.4])

=== Die WCAG 2.1 zur Nutzung absoluter und relativer Maßeinheiten für Text

[.BLOCK_LANG_EN]
____
(...) specify text font size in `em` units so that user agents can scale
content effectively.
Since the `em` is a property of the font, it scales as the
font changes size.
If a font-size is specified for the body element, all other
elements inherit that value, unless overridden by a more specific selector.

When font size is given in absolute units of measurement, such as points or
pixels, the Text Size menu commands in Internet Explorer 7 and earlier do not
resize the text.

Internet Explorer 7 only changes the text size when the CSS is defined in a
style element (...)When using inline style with the `style` attribute, the
text size change is not supported.
____

(WCAG 2.1 Technik https://www.w3.org/WAI/WCAG21/Techniques/css/C14.html[
C14: Using em units for font sizes])

== Fragen zu diesem Prüfschritt

=== Die Vergrößerung der Schrift ist weniger wichtig, wenn die Ausgangsschriftgrößen der Webseite bereits groß genug sind, sollte das nicht berücksichtigt werden?

Der BITV-Test berücksichtigt die tatsächlichen Schriftgrößen nicht, geprüft wird nur die Änderbarkeit.
Für Seiten mit großen Ausgangsschriften (oder für Seiten, die in großen Schritten vergrößern) ist die Prüfanforderung also nicht so leicht zu erfüllen.

Die Begründung:

Die BITV verlangt keine Mindestgröße für Schriften. Und was wichtiger ist: es gibt unterschiedliche Auffassungen zur der Frage, wie groß Ausgangsschriftgrößen sein sollen:

* Idealerweise wären die Ausgangsschriftgrößen aller Webangebote ähnlich. Denn dann könnte jeder Benutzer in seinem Browser die für ihn passende Schriftgröße einstellen.
Diese Einstellung müsste nicht geändert werden, sie wäre für alle Webangebote passend.
* Sehr große Ausgangsschriften sind unter Umständen nicht gut zu nutzen. Und zwar auch für Benutzer, die große Schriften brauchen. Denn diese Benutzer haben ihren Computer oder ihren Browser meist schon so eingerichtet, daß Schriften größer dargestellt werden. Die extrem große Ausgangsschrift ist dann zu viel des Guten.

Die Orientierung an im Web üblichen Schriftgrößen ist also sinnvoll. Aber auch große Ausgangsschriften sind vorteilhaft. Auch für Besucher, die nicht wissen, wie man die Schrift vergrößert, sind sie groß genug.

Am besten ist es also, wenn sich Webangebote an der Obergrenze der im Web üblichen Schriftgrößen orientieren.
