= Prüfschritt 9.2.5.2a Zeigergesten-Eingaben können abgebrochen oder widerrufen werden
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Funktionen von Bedienelementen sollen nicht bereits durch den Down-Event eines Zeigers (z.BMauszeiger, Trackpad-Zeiger, Finger oder Eingabestift) auf einem Bedienelement ausgeführt werden; falls doch, muss es eine Möglichkeit geben, die ausgelöste Funktion entweder abzubrechen oder rückgängig zu machen.

Eine Ausnahme für diese Anforderung besteht, wenn das Auslösen der Funktion
durch das Down-Ereignis essenziell ist (etwa beim Zeichnen mittels Maus,
Eingabestift oder Finger auf einem Touchscreen oder Grafiktablett, oder beim
Interagieren mit einer virtuellen Tastatur).

== Warum wird das geprüft?

Menschen mit motorischen Beeinträchtigungen haben häufig Schwierigkeiten,
Zeiger-Gesten auf Schnittstellen-Elementen zielgerichtet auszuführenDie
Ausführung beim Up-Event (etwa wenn die Maustaste losgelassen wird oder der
Finger vom Touchscreen abgehoben wird) gibt diesen Menschen die Möglichkeit,
Fehleingaben zu vermeiden, da es sie befähigt, vor Auslösen des Up-Events den
Zeiger vom Interface-Element wegzubewegenWenn Down-Events bereits Funktionen
auslösen, besteht diese Korrekturmöglichkeit nicht.

In Fällen, wo eine Zeiger-Eingabe mehrstufig ist, etwa bei Drag-and-Drop
Aktionen, ist es wichtig, dass es einen Weg gibt, versehentlich ausgeführte
Eingaben rückgängig zu machenDies kann auf verschiedene Weise geschehen, etwa
über eine Schaltfläche zum Rückgängig-Machen der Aktion, einen
Bestätigungsdialog, durch das Loslassen des Elements über dem Ausgangsort,
oder durch das Loslassen des Elements über einem Ort, der nicht als Drop
Target definiert ist und das Element zum Ausgangspunkt zurückspringen lässt.

== Wie wird geprüft?

=== 1Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn auf der Seite Bedienelemente vorhanden
sind.

=== 2Prüfung

Es wird auf einem Smartphone überprüft, ob es Bedienelemente gibt, deren
Funktionen durch Down-Events ausgelöst werdenDie Prüfung auf dem Desktop ist
nicht ausreichend, weil hier Touch-Events wie `touchstart` ggfnicht
ausgewertet werden.

Auf dem Smartphone Bedienelemente (Links, Schalter) berühren, den Finger kurz
liegen lassen.
Beobachten, ob nun schon eine Funktion ausgeführt wirdDies geschieht
wahrscheinlich aufgrund eines Down-Events.
Wenn keine Funktion ausgelöst wird, Finger vom Punkt der Berührung wegbewegen
und loslassenDadurch wird in der Regel der Aufruf des Links oder der Funktion
vermieden, selbst wenn der berührte Punkt dem Finger folgt (die Seite
gescrollt wird).
Wenn Funktionen beim Down-Event ausgelöst werden, prüfen, ob die Funktion
abgebrochen oder rückgängig gemacht werden kann oder beim Up-Event wieder
rückgängig gemacht wird.

=== 3Hinweise

Es ist in der Regel nicht notwendig, jedes einzelne Bedienelement aufzurufen,
wenn eine stichprobenartige Prüfung zeigt, das die Umsetzung gleichartig
istFür ein Menü etwa reicht es dann, bei jeder Art von Menüeintrag (etwa
Hauptmenü- und Untermenü-Einträge) ein Element zu testenDas Gleiche gilt für
Fließtextlinks.

Es kann bei der Prüfung zum Aufruf von Funktionen des Browsers kommen (etwa:
ein Kontextmenü wird angezeigt)Dies ist nicht Teil der Prüfung und sollte
ignoriert werrden.

Als Zeiger-Down-Events gelten `mousedown`, `touchstart` und `pointerdown`.

=== 4Bewertung

==== Prüfschritt erfüllt:

* Keine Funktionen werden beim Down-Event ausgelöst.
* Funktionen, die beim Down-Event ausgelöst werden, können abgebrochen, zurückgenommen oder beim Up-Event in den alten Zustand zurückversetzt werden.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#input-modalities[Guideline 2.5 Input Modalities: Make it easier for users to operate functionality through various inputs beyond keyboard]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#pointer-cancellation[2.5.2 Pointer Cancellation] (Level A)

==== Sufficient Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G210[G210: Ensuring that drag-and-drop actions can be cancelled]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G212[G212: Using native controls to ensure functionality is triggered on the up-event.]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F101[F101: Failure of Success Criterion 2.5.2 due to activating a control on the down-event]

== Quellen

* Das Bookmarklet https://testen.bitv-test.de/bookmarklets.html#downevent[Down-Events auslösen] von Prüfstelle T-Systems MMS kann ggfzusätzlich eingesetzt werden, um der Reihe nach auf allen Elementen down-events auszulösenDabei muss die Seite genau beobachtet werden, ob sich etwas ändert bzwgeändert hatDie Geschwindigkeit (Intervall in Millisekunden) kann am Beginn eingestellt werden.
* https://www.w3.org/WAI/WCAG21/Understanding/pointer-cancellation[Understanding Success Criterion 2.5.2: Pointer Cancellation] (zur Zeit nur auf Englisch verfügbar)
* Spezifikation PointerEvents (https://www.w3.org/TR/pointerevents/)
* Spezifikation TouchEvents (https://www.w3.org/TR/touch-events/)
* Spezifikation UIEvents (https://www.w3.org/TR/uievents/)
