= Prüfschritt 9.1.1.1a Alternativtexte für Bedienelemente9.1.1.1b Alternativtexte für Grafiken und Objekte9.1.1.1c Leere alt-Attribute für Layoutgrafiken9.1.1.1d Alternativen für CAPTCHAs9.1.2.1a Alternativen für Audiodateien und stumme Videos9.1.2.2a Aufgezeichnete Videos mit Untertiteln9.1.2.3a Audiodeskription oder Volltext-Alternative für Videos9.1.2.4a Videos (live) mit Untertiteln9.1.2.5a Audiodeskription für Videos9.1.3.1a HTML-Strukturelemente für Überschriften9.1.3.1b HTML-Strukturelemente für Listen9.1.3.1c HTML-Strukturelemente für Zitate9.1.3.1d Inhalt geglieder9.1.3.1e Datentabellen richtig aufgebaut9.1.3.1f Zuordnung von Tabellenzellen9.1.3.1g Kein Strukturmarkup für Layouttabellen9.1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar9.1.3.2a Sinnvolle Reihenfolge9.1.3.3a Ohne Bezug auf sensorische Merkmale nutzbar9.1.3.4a Keine Beschränkung der Bildschirmausrichtung9.1.3.5a Eingabefelder zu Nutzerdaten vermitteln den Zweck9.1.4.10a Inhalte brechen um9.1.4.11a Kontraste von Grafiken und grafischen Bedienelementen ausreichend9.1.4.12a Textabstände anpassbar9.1.4.13a Eingeblendete Inhalte bedienbar9.1.4.1a Ohne Farben nutzbar9.1.4.2a Ton abschaltbar9.1.4.3a Kontraste von Texten ausreichend9.1.4.4a Text auf 200% vergrößerbar9.1.4.5a Verzicht auf Schriftgrafiken9.2.1.1a Ohne Maus nutzbar9.2.1.2a Keine Tastaturfalle9.2.1.4a Tastatur-Kurzbefehle abschaltbar oder anpassbar9.2.2.1a Zeitbegrenzungen anpassbar9.2.2.2a Bewegte Inhalte abschaltbar9.2.3.1a Verzicht auf Flackern9.2.4.1a Bereiche überspringbar9.2.4.2a Sinnvolle Dokumenttitel9.2.4.3a Schlüssige Reihenfolge bei der Tastaturbedienung9.2.4.4a Aussagekräftige Linktexte9.2.4.5a Alternative Zugangswege9.2.4.6a Aussagekräftige Überschriften und Beschriftungen9.2.4.7a Aktuelle Position des Fokus deutlich9.2.5.1a Alternativen für komplexe Zeiger-Gesten9.2.5.2a Zeigergesten-Eingaben können abgebrochen oder widerrufen werden9.2.5.3a Sichtbare Beschriftung Teil des zugänglichen Namens9.2.5.4a Alternativen für Bewegungsaktivierung
include::include/author.adoc[]
include::include/attributes.adoc[]

[[multileiste]]
link:/index.php?a=eb&iid=119[die bisherigen Bewertungen für dieses Prüfschritt]

[.stopFloat]##

== [#technische-angaben]####Technische Angaben

Version

Aktuell

BITV-Bedingung

2.5.4 Bewegungsaktivierung

Bewertungsalternativen

ja / eher erfüllt / teilweise erfüllt / eher nicht erfüllt / nein / nicht anwendbar

Bezieht sich auf

einzelne Webseite

Prüfschritt erfüllt

Funktionen, die über Gerätebewegung oder Benutzerbewegung ausgelöst werden können, lassen sich alternativ auch über Bedienelemente auslösen. Die Aktivierung durch Bewegung kann abgeschaltet werden, außer wenn die Bewegung Teil einer Hilfsmitteleingabe oder für die Funktion unerlässlich ist.

== [#was-wird-geprueft]####Was wird geprüft?

Wenn Webinhalte auf die Bewegung eines mobilen Gerätes reagieren oder wenn Bewegungen des Benutzers von Gerätesensoren oder der Kamera erfasst werden, um Funktionen auszulösen, sollten hierfür alternative Eingabemöglichkeiten vorhanden sein, und die Bewegungseingabe soll vom Nutzer abgeschaltet werden können.

Der Prüfschritt gilt nicht für Bewegungseingaben, die für die Funktion wesentlich sind, z.B. wenn ein Bewegungssensor die Schritte einer Person aufzeichnet, oder wenn die Bewegung Teil einer zugänglichkeits-unterstützten Hilfsmitteleingabe ist.

Abschaltbarkeit der Bewegungseingabe: Gegebenenfalls können Webinhalte diese Anforderung erfüllen, indem sie Betriebssystemeinstellungen unterstützen, die es dem Benutzer ermöglichen, die Bewegungserkennung auf Systemebene zu deaktivieren.

== [#warum-wird-das-geprueft]####Warum wird das geprüft?

Menschen mit motorischen Einschränkungen können Bewegungseingaben oft nicht, oder nicht gezielt, ausführen. In manchen Fällen sind Geräte fest montiert, zum Beispiel an einem Rollstuhl, was Bewegungseingaben unmöglich macht. Deshalb ist es wichtig, dass es auch andere Möglichkeiten der Eingabe über Bedienelemente des Webinhaltes gibt.

Bei anderen motorischen Einschränkungen kann es durch unwillkürliche Bewegungen zu ungewollten Eingaben kommen. Deshalb ist es wichtig, dass sich von Webinhalten bereitgestelte motorische Eingaben deaktivieren lassen.

== [#wie-wird-geprueft]####Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn Webinhalte bestimmte Bewegungseingaben definieren, etwa die Bewegung durch eine 360-Grad-Rundumansicht durch ein Rotieren des Geräts, oder das Blättern durch eine Folge von Präsentationsfolien durch ruckartige Seitwärtsbewegungen.

=== 2. Prüfung

. Über Bewegungen, Quellcode-Prüfung oder geeignete Hilfsfunktionen, die in Scripten das Vorhandensein von Motion-Eventhandlern aufzeigen, prüfen, ob der Webinhalt in irgend einer Weise auf Bewegungseingaben reagiert.
. Für alle Funktionen, die über Bewegungseingabe ausgelöst werden, prüfen, ob alternative Eingabemöglichkeiten über Bedienelemente bestehen.
. Prüfen, ob sich vorhandene Bewegungseingaben abschalten lassen.

=== 3. Bewertung

==== Prüfschritt erfüllt:

* Von Webinhalten definierte Bewegungseingaben haben eine alternative Eingabemöglichkeit über zugängliche Bedienelemente oder lassen sich vom Nutzer wirkungsvoll deaktivieren (ggf. über Einstellungen des Betriebssystems).

== [#einordnung-des-pruefschritts]####Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#input-modalities[Guideline 2.5 Input Modalities: Make it easier for users to operate functionality through various inputs beyond keyboard]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#motion-actuation[2.5.4 Motion Actuation] (Level A)

==== Sufficient Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G213[G213: Provide conventional controls and an application setting for motion activated input]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F106[F106: Failure due to inability to deactivate motion actuation]

== [#quellen]####Quellen

https://www.w3.org/WAI/WCAG21/Understanding/motion-actuation.html[Understanding Success Criterion 2.5.4: Motion Actuation] (zur Zeit nur auf Englisch verfügbar)
