= Prüfschritt 9.1.1.1a Alternativtexte für Bedienelemente9.1.1.1b Alternativtexte für Grafiken und Objekte9.1.1.1c Leere alt-Attribute für Layoutgrafiken9.1.1.1d Alternativen für CAPTCHAs9.1.2.1a Alternativen für Audiodateien und stumme Videos9.1.2.2a Aufgezeichnete Videos mit Untertiteln9.1.2.3a Audiodeskription oder Volltext-Alternative für Videos9.1.2.4a Videos (live) mit Untertiteln9.1.2.5a Audiodeskription für Videos9.1.3.1a HTML-Strukturelemente für Überschriften9.1.3.1b HTML-Strukturelemente für Listen9.1.3.1c HTML-Strukturelemente für Zitate9.1.3.1d Inhalt geglieder9.1.3.1e Datentabellen richtig aufgebaut9.1.3.1f Zuordnung von Tabellenzellen9.1.3.1g Kein Strukturmarkup für Layouttabellen9.1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar9.1.3.2a Sinnvolle Reihenfolge9.1.3.3a Ohne Bezug auf sensorische Merkmale nutzbar9.1.3.4a Keine Beschränkung der Bildschirmausrichtung9.1.3.5a Eingabefelder zu Nutzerdaten vermitteln den Zweck9.1.4.10a Inhalte brechen um9.1.4.11a Kontraste von Grafiken und grafischen Bedienelementen ausreichend9.1.4.12a Textabstände anpassbar9.1.4.13a Eingeblendete Inhalte bedienbar9.1.4.1a Ohne Farben nutzbar9.1.4.2a Ton abschaltbar9.1.4.3a Kontraste von Texten ausreichend9.1.4.4a Text auf 200% vergrößerbar9.1.4.5a Verzicht auf Schriftgrafiken9.2.1.1a Ohne Maus nutzbar9.2.1.2a Keine Tastaturfalle9.2.1.4a Tastatur-Kurzbefehle abschaltbar oder anpassbar
include::include/author.adoc[]
include::include/attributes.adoc[]

[[multileiste]]
link:/index.php?a=eb&iid=112[die bisherigen Bewertungen für dieses Prüfschritt]

[.stopFloat]

== Technische Angaben

Version

Aktuell

BITV-Bedingung

2.1.4 Tastaturkurzbefehle

Bewertungsalternativen

ja / eher erfüllt / teilweise erfüllt / eher nicht erfüllt / nein

Bezieht sich auf

einzelne Webseite

Prüfschritt erfüllt

Durch Webinhalte implementierte Tastatur-Kurzbefehle über Einzeltasten sind abschaltbar oder auf Tastenkombinationen mit Modifikator-Tasten umstellbar.

== Was wird geprüft?

Wenn Webseiten Tastaturkurzbefehle über Einzeltasten (Buchstaben, Zahlen, Satzzeichen oder Symbole) implementieren, können diese entweder abgeschaltet oder auf eine Tastenkombination mit Modifikator-Tasten umgestellt werden, oder sie sind nur aktiv für bestimmte Schnittstellen-Elemente, wenn diese den Fokus haben.

== Warum wird das geprüft?

Tastaturkurzbefehle sind für Menschen, die am Computer oder einem mobilen Gerät die Spracheingabe benutzen, häufig problematischSpracheingaben können unerwartet Befehle für Funktionen auslösen, der Nutzungskontext geht dadurch verloren.

== Wie wird geprüft?

=== 1Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

=== 2Prüfung

Seite neu ladenWenn dies den Fokus auf ein Interface-Element setzt (z.Bauf ein Eingabefeld), auf einen leeren Bereich der Seite klicken, um sicherzustellen, dass keine Interface-Elemente fokussiert sind.
Mit Ausnahme der Modifikator- und Steuertasten wie STR, ALT, ENTER, Tab, Pfeiltasten und Funktionstasten F1-F12, nacheinander auf alle Tastaturtasten drücken, d.hauf alle Nummern- Buchstaben-, Symbol- und Zeichensetzungs-Tasten.
Die Umschalttaste halten und die gleichen Tasten erneut betätigen.
Falls einzelne Tasten Funktionen auslösen, prüfen, ob die Website oder App Einstellungen bereithält, um diese Tastaturkurzbefehle über Einzeltasten abzuschalten oder auf Tastaturkurzbefehle mit einer Modifikator-Taste zu mappen.

=== 3Hinweise

Die Anforderung gilt nicht, wenn die Tastaturkurzbefehle nur aktiv sind, sobald bestimmte Interface-Elemente den Fokus haben, etwa ein Auswahllisten-Element bzw`select`Hier dient z.Bdas Drücken einer Buchstabentaste zur schnellen Navigation innerhalb der Auswahllisten-Optionen.

Über das Anzeigen von Seitenskripten und das Suchen nach typischen Tastatur-Event-Handlern wie `document.addEventListener` oder das Vorhandensein des `.keycode` Attributs lässt sich ggfdas Vorhandensein von Skripten überprüfen, welche auf Tasteneingaben reagieren, bei denen nicht Modifikator-Tasten wie ALT oder STR gleichzeitig gedrückt werdenDa es mehrere Möglichkeiten gibt, Tastatur-Events zu implementieren, ist diese Methode aber nicht als zuverlässig zu betrachten.

Einige Browser verwenden Tastenkombinationen mit der UmschalttasteSo öffnet Firefox eine Seitensuche, wenn man Umschalttaste + / drückt, und eine Suche in Seitenlinks, wenn man Umschalttaste + ' drücktIn diesen Fällen ist es notwendig, die ESC-Taste zu drücken oder auf einen leeren Teil der Seite zu klicken, um den Fokus aus der Browser-Sucheingabe zu entfernen.

=== 4Bewertung

==== Prüfschritt erfüllt:

* Durch das Drücken der Tasten geschehen keinerlei Änderungen des Inhalts oder des Kontexts.
* Es gibt Tastatur-Kurzbefehle über Einzeltasten, aber diese sind über Einstellungen der Website oder App abschaltbar oder auf Tastenkombinationen mit Modifikator-Tasten umstellbar.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#keyboard-accessible[Guideline 2.1 Keyboard Accessible: Make all functionality available from a keyboard]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#character-key-shortcuts[2.1.4 Character Key Shortcuts] (Level A)

==== Sufficient Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G217[G217: Providing a mechanism to allow users to remap or turn off character key shortcuts]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F99[F99: Failure of Success Criterion 2.1.4 due to implementing character key shortcuts that cannot be turned off or remapped]

== Quellen

https://testen.bitv-test.de/bookmarklets.html#kurzbefehle[Bookmarklet "Tastatur-Kurzbefehle auslösen"] von Prüfstelle T-Systems MMS kann ggfzusätzlich eingesetzt werden, um der Reihe nach alle erforderlichen Tasten auszulösenDabei muss die Seite genau beobachtet werden, ob sich etwas ändert bzwgeändert hatDie Konsole der Entwickler-Tools zeigt die simulierten Eingaben.

https://www.w3.org/WAI/WCAG21/Understanding/character-key-shortcuts.html[Understanding Success Criterion 2.1.4: Character Key Shortcuts] (zur Zeit nur auf Englisch verfügbar)
