= Prüfschritt 9.1.1.1a Alternativtexte für Bedienelemente9.1.1.1b Alternativtexte für Grafiken und Objekte9.1.1.1c Leere alt-Attribute für Layoutgrafiken9.1.1.1d Alternativen für CAPTCHAs9.1.2.1a Alternativen für Audiodateien und stumme Videos9.1.2.2a Aufgezeichnete Videos mit Untertiteln9.1.2.3a Audiodeskription oder Volltext-Alternative für Videos9.1.2.4a Videos (live) mit Untertiteln9.1.2.5a Audiodeskription für Videos9.1.3.1a HTML-Strukturelemente für Überschriften9.1.3.1b HTML-Strukturelemente für Listen9.1.3.1c HTML-Strukturelemente für Zitate9.1.3.1d Inhalt geglieder9.1.3.1e Datentabellen richtig aufgebaut9.1.3.1f Zuordnung von Tabellenzellen9.1.3.1g Kein Strukturmarkup für Layouttabellen9.1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar9.1.3.2a Sinnvolle Reihenfolge9.1.3.3a Ohne Bezug auf sensorische Merkmale nutzbar9.1.3.4a Keine Beschränkung der Bildschirmausrichtung9.1.3.5a Eingabefelder zu Nutzerdaten vermitteln den Zweck9.1.4.10a Inhalte brechen um9.1.4.11a Kontraste von Grafiken und grafischen Bedienelementen ausreichend9.1.4.12a Textabstände anpassbar9.1.4.13a Eingeblendete Inhalte bedienbar9.1.4.1a Ohne Farben nutzbar9.1.4.2a Ton abschaltbar9.1.4.3a Kontraste von Texten ausreichend9.1.4.4a Text auf 200% vergrößerbar9.1.4.5a Verzicht auf Schriftgrafiken9.2.1.1a Ohne Maus nutzbar9.2.1.2a Keine Tastaturfalle9.2.1.4a Tastatur-Kurzbefehle abschaltbar oder anpassbar9.2.2.1a Zeitbegrenzungen anpassbar9.2.2.2a Bewegte Inhalte abschaltbar9.2.3.1a Verzicht auf Flackern9.2.4.1a Bereiche überspringbar
include::include/author.adoc[]
include::include/attributes.adoc[]

[[multileiste]]
link:/index.php?a=eb&iid=73[die bisherigen Bewertungen für dieses Prüfschritt]

[.stopFloat]##

== [#technische-angaben]####Technische Angaben

Version

link:/index.php?a=di&iid=22[bis 10.07.2017] | Aktuell

BITV-Bedingung

2.4.1 Umgehen von Elementgruppen

WCAG-Erfolgskriterium

2.4.1 Blöcke umgehen

Bewertungsalternativen

ja / eher erfüllt / teilweise erfüllt / eher nicht erfüllt / nein / nicht anwendbar

Bezieht sich auf

einzelne Webseite

Prüfschritt erfüllt

Seitenbereiche sind durch Überschriften, Sprunglinks oder WAI ARIA document landmarks erschlossen, Frames und Iframes haben sinnvolle Titel.

Prüfschritt nicht anwendbar

Überschriften oder Sprunglinks sind nicht erforderlich, denn die Seite hat keine unterschiedlichen Bereiche.

== [#was-wird-geprueft]####Was wird geprüft?

Verschiedenen Inhaltsbereiche wie Navigation, Suche oder Seiteninhalt können von Nutzern assistiver Technologien übersprungen werden. Der Seitenaufbau soll unabhängig von der Darstellung deutlich werden. Eine der folgenden Voraussetzungen soll erfüllt sein:

* Es werden sinnvolle Bereichsüberschriften (HTML-Strukturelemente `h1` bis `h6`) eingesetzt
* Es sind Sprunglinks vorhanden.
* HTML5 Elemente zur Auszeichnung von Bereichen (`header, nav, main, aside, footer`) erschließen den Seitenaufbau sinnvoll.
* WAI-ARIA _document landmarks_ strukturieren die Seitenbereiche sinnvoll.

Frames und Iframes brauchen ein sinnvolles `title`-Attribut.

== [#warum-wird-das-geprueft]####Warum wird das geprüft?

Visuell werden Webseiten mit Mitteln wie Überschriften, Spalten oder Kästen strukturiert. Dank dieser Strukturierung weiß der Benutzer, was zusammengehört, kann das Angebot der Webseite leicht überblicken und gezielt auf die Inhalte zugreifen, die ihn interessieren.

Benutzer, die diese visuelle Ordnung nicht nutzen können – zum Beispiel, weil sie blind sind oder nur einen kleinen Ausschnitt der Seite sehen können – sind darauf angewiesen, dass die Struktur unabhängig von der Darstellung auf dem Bildschirm zugänglich und nutzbar ist. Die Verwendung von (oft unsichtbaren) Bereichsüberschriften, Sprunglinks oder HTML5 Elementen zur Auszeichnung von Regionen ist dafür eine wesentliche Voraussetzung.

Bei Frames ist eine sinnvoller Titel wichtig für die Orientierung mit Screenreadern. Gängige Screenreader werten das `title`- und das in der Programmierung gebräuchliche `name`-Attribut aus. Dabei wird das `title`-Attribut vorrangig ausgegeben. Sie sprechen beim Umschalten zwischen den Frames mit den Tastenkürzeln den Titel des aktiven Frames aus.

Der Einsatz von HTML5 Elementen für Regionen wird inzwischen gut von assisitven Technologien unterstützt. Die zusätzliche Berücksichtigung eines role-Attributs (WAI ARIA document landmarks) kann die Unterstützung von Regionen jedoch verbessern.

So können Benutzer die Bereichsüberschriften, Sprunglinks, HTML5-Elmente für Regionen bzw. WAI-ARIA document landmarks anwenden:

* Konstante Bereiche am Seitenbeginn, etwa Navigation oder Seitenkopf, überspringen, um direkt zum Inhalt zu gelangen
* Zwischen Bereichen hin- und her wechseln

== [#wie-wird-geprueft]####Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn es auf der Seite deutlich voneinander abgegrenzte Bereiche gibt, etwa Navigation und Inhalt. Das ist bei informationsorientierten Seiten meist der Fall.

=== [#G140]####2. Prüfung

==== 2.1. Prüfung der Bereichsüberschriften

. Seite im Firefox aufrufen.
. Über die http://www.bitvtest.de/bitvtest/das_testverfahren_im_detail/werkzeugliste.html#webdeveloper[Web Developer Toolbar] die Seite ohne Stylesheets anzeigen (über _CSS > Styles deaktivieren > Alle Styles deaktivieren_ Stylesheets deaktivieren).
. Das http://www.bitvtest.de/bitvtest/das_testverfahren_im_detail/werkzeugliste.html#gegliedert[Bookmarklet "Inhalte gegliedert"] aufrufen.
. [#G115]####[#G130]####[#H42]####[#H69]####Die Bereichsüberschriften im Zusammenhang mit den durch sie strukturierten Inhalten ansehen und prüfen, ob sie aussagekräftig sind, die Strukturelemente für Überschriften nutzen, und die Inhaltsbereiche der Seite vollständig und korrekt gliedern.

==== 2.2. Sprunglink-Prüfung

Wenn Sprunglinks vorhanden sind, prüfen, ob die folgenden Anforderungen erfüllt sind:

* Sprunglinks verschieben beim Auslösen den Tastaturfokus zum angegebenen Bereich (bzw. beim Überspringen von Inhaltsblöcken auf den Inhalt direkt nach dem zu überspringenden Bereich)
* Sprunglinks sind entweder permanent sichtbar oder werden bei Fokuserhalt eingeblendet
* Sprunglinks am Seitenbeginn sind die ersten fokussierbaren Elemente der Tabreihenfolge
* Sprunglinks zum Überspringen von Inhaltsblöcken sind das letzte fokussierbare Element vor dem zu überspringenden Inhaltsblock oder dessen erster Link

==== 2.3. Prüfung der HTML5 Elemente für Regionen und WAI-ARIA document landmarks

. Seite im Firefox aufrufen.
. Quelltextanalyse: Prüfen, ob die verschiedenen Seitenbereiche durch die Auszeichnung mit `header, nav, main, aside, footer` sinnvoll erschlossen werden.
. Das http://www.bitvtest.de/bitvtest/das_testverfahren_im_detail/werkzeugliste.html[Landmarks bookmarklet] aufrufen. Die document landmarks werden nun, wenn vorhanden, hervorgehoben.
. Wenn document landmarks eingesetzt werden, prüfen, ob die Zuordnung der Rollen (z.B. `navigation, main`) korrekt ist und dem Aufbau der Seite entspricht.
. Sind mehrere Navigationsbereiche nur mit `nav` oder `role="navigation"` ausgezeichnet, dann prüfen, ob sie mit `aria-label` oder `aria-labelledby` sinnvoll bezeichnet sind.

==== [#H64]####2.4. Prüfung von Frame-Titeln

. Seite im Firefox aufrufen.
. In derWeb Developer Toolbar die Funktion _Outline > Outline Frames_ aufrufen.
. Dann ebenfalls in derWeb Developer Toolbar die Funktion _Information > Display Element Information_ aufrufen. Der Cursor wird nun als Fadenkreuz angezeigt.
. Mit dem Fadenkreuz die Kante der hervorgehobenen Frames anklicken und prüfen, ob für alle Frames ein aussagekräftiger `title`-Text vorhanden ist.

=== 3. Hinweise

==== Eigenständige Bereiche

Eigenständige Bereiche sind zum Beispiel:

* Navigation und Inhalt
* Spalten mit unterschiedlichen Inhalten
* Bereiche, die durch Umrahmung als zusammengehörig gekennzeichnet sind
* Frames oder Iframes

Der Fußbereich wird nicht als eigenständiger Bereich gewertet, wenn dort lediglich redundante Links, Copyright-Hinweise oder Angaben zum Erstellungs- oder Änderungsdatum stehen.

==== Hinweis zu Sprunglinks und Document Landmarks

Das Fehlen von Sprunglinks und die Nichtverwendung von WAI-ARIA Document Landmarks werden nicht negativ bewertet.

==== Hinweis zu mehrfach verwendeten Landmarks bzw. HTML5-Elemente für Bereiche

Wird eine WAI-ARIA document landmark bzw. ein HTML5-Element für Bereiche mehrfach verwendet (z.B. role="navigation" oder `nav`), sollte sie mit Hilfe von `aria-label` oder `aria-labelledby` aussagekräftig benannt werden.

==== Hinweis zu Sie-sind-hier"-Navigationen

Die "Sie-sind-hier"-Navigation am Seitenanfang (auch breadcrumb trail oder Krümelpfad) Wenn Breadcrumbs als Listen ausgezeichnet sind, brauchen sie einen (eventuell versteckte) vorangestellten Hinweis wie "Seitenpfad", "Sie sind hier", oder "Navigationspfad" um so für Screenreader-Nutzer von anderen Menüs unterscheidbar zu sein.

==== Hinweis zu Frames und Iframes

Im `title`-Attribut soll der Zweck oder Inhalt, nicht aber die Lage des Frames auf dem Bildschirm angeben werden (siehe https://testen.bitv-test.de/index.php?a=di&iid=55&s=n[2.4.2a]). Angemessene `title`-Attribute sind zum Beispiel "Navigation" und "Inhalt", nicht jedoch "top" oder "rechts". Oft werden in Framesets auch leere Frames eingebunden, die ausschließlich zu Layoutzwecken verwendet werden. Bei solchen Frames sollte als Bezeichnung "Leer" gewählt werden.

=== 4. Bewertung

==== Erfüllt:

* Alle Bereiche der Seite können über Überschriften, Sprunglinks, HTML5 Elemente für Regionen und/oder WAI ARIA document landmarks erreicht und übersprungen werden. Frames und Iframes haben sinnvolle Titel.

==== Nicht voll erfüllt:

* Bereichsüberschriften sind nicht aussagekräftig oder irreführend.
* Der Einsatz von HTML5 Elementen für Regionen erschließt die Seitenbereiche nicht vollständig.
* Die Zuordnung von WAI-ARIA document landmarks ist falsch oder irreführend.
* Bereichsüberschriften oder Sprunglinks sind mittels `display:none` versteckt
* Der Seitenpfad (Breadcrumb) ist als Liste ausgezeichet, hat aber keinen vorangestellten Hinweis (z.B. Überschrift)
* Mehre wichtige Navigationsbereiche sind mit WAI-ARIA document landmarks oder HTML5-Elementen für Bereiche ausgezeichnet und sind nicht mit aria-label oder aria-labelledby unterschieden.

==== Nicht erfüllt:

* Es gibt auf der Seite verschiedene Bereiche mit für sich nutzbaren Inhalten, diese werden jedoch weder mit Überschriften, noch mit Sprunglinks oder HTML5 Elementen erschlossen.
* Auf der Seite werden mehrere klar abgrenzbare Themen behandelt, es wurde aber nur pro forma eine Hauptüberschrift ausgezeichnet.

== [#einordnung-des-pruefschritts]####Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten

* In diesem Prüfschritt geht es um die Auszeichnung der Seitenbereiche mit Überschriften, Sprunglinks und WAI-ARIA-Attributen (landmarks). Die inhlatliche Strukturierung von Seiteninhalten wird in Prüfschritt link:/index.php?a=di&iid=72&s=n[1.3.1a] "HTML-Strukturelemente für Überschriften" geprüft.
* In diesem Prüfschritt wird geprüft, ob Frames und Iframes (wenn vorhanden) vernünftige Titel haben. Die *Inhalte* von Iframes werden ebenso geprüft wie andere Seiteninhalte, etwa in Prüfschritt link:/index.php?a=di&iid=76&s=n[1.3.1d] "Inhalte gegliedert".

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guidelines

* https://www.w3.org/WAI/WCAG21/quickref/#navigable[Guideline 2.4 Navigable: Provide ways to help users navigate, find content, and determine where they are]

==== Success criteria

* https://www.w3.org/WAI/WCAG21/quickref/#bypass-blocks[2.4.1 Bypass Blocks (Level A)]

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G1.html[G1: Adding a link at the top of each page that goes directly to the main content area]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G115.html[G115: Using semantic elements to mark up structure]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G123.html[G123: Adding a link at the beginning of a block of repeated content to go to the end of the block]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G124.html[G124: Adding links at the top of the page to each area of the content]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G130.html[G130: Providing descriptive headings]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G140.html[G140: Separating information and structure from presentation to enable different presentations]

===== HTML Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/html/H42.html[H42: Using h1-h6 to identify headings]
* https://www.w3.org/WAI/WCAG21/Techniques/html/H64.html[H64: Using the title attribute of the frame and iframe elements]
* https://www.w3.org/WAI/WCAG21/Techniques/html/H69.html[H69: Providing heading elements at the beginning of each section of content]
* https://www.w3.org/WAI/WCAG21/Techniques/html/H97.html[H97: Grouping related links using the nav element]

===== ARIA Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA11.html[ARIA11: Using ARIA landmarks to identify regions of a page]
* https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA13.html[ARIA13: Using aria-labelledby to name regions and landmarks]

== [#quellen]####Quellen

=== WCAG 2.1 Hinweis zum Unterschied von `name` und `title`

____
The `title` attribute is not interchangeable with the `name` attribute. The title labels the frame for users; the name labels it for scripting and window targeting. The name is not presented to the user, only the title is.
____

Quelle: https://www.w3.org/WAI/WCAG21/Techniques/html/H64.html[H64: Using the title attribute of the frame and iframe elements]

=== WCAG 2.1 Verknüpfung von WAI ARIA document landmarks und Text

____
The purpose of this technique is to provide names for regions of a page that can be read by assistive technology. The aria-labelledby attribute provides a way to associate an section of the page marked up as a region or landmarks with text that is on the page that labels it.
____

Quelle: https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA13.html[ARIA13: Using aria-labelledby to name regions and landmarks]

=== Ergänzung von HTML5 Elementen mit WAI ARIA

Script, das bei HTML5 Elementen automatisch ARIA-Rollen ergänzt: https://github.com/yatil/accessifyhtml5.js[Polyfill accessifyhtml5.js von Yatil]

== [#faq]####Fragen zu diesem Prüfschritt

=== Müssen die Bereiche der Webseite durch `h1`-Überschriften ausgezeichnet werden?

Bei den meisten Webangeboten sind bestimmte Bereiche durchgängig für die Navigation reserviert. Andere wiederkehrende Bereich können etwa die Suche oder der Seitenkopf sein. Diese Bereiche sind auf allen Seiten des Angebots gleich aufgebaut und gestaltet. Sie haben keinen engen Bezug zum besonderen Seiteninhalt, sind eigentlich nicht den einzelnen Seiten, sondern eher dem Webauftritt als ganzen zuzurechnen. Es liegt daher nahe, die Navigation, den Inhaltsbereich und weitere klar abgegrenzte Bereiche der Seite jeweils mit einer `h1`-Hauptüberschrift zu versehen.

Es gibt jedoch auch andere Möglichkeiten, Seitenbereiche auszuzeichnen, etwa durch `h5`- oder `h6`-Überschriften, falls diese in der Gliederung der Seiteninhalte nicht verwendet werden (vergleiche den Artikel auf einfach-für-alle: http://www.einfach-fuer-alle.de/artikel/ueberschriften-strukturen-in-html/["Passende Überschrift hier einsetzen"])

Vom BITV-Test werden unterschiedliche Herangehensweisen akzeptiert. Es muss in jedem Fall geprüft werden, ob Überschriften konsistent eingesetzt werden, um die Seiten-Bereiche und deren Inhalte zu erschließen.
