= Prüfschritt 9.1.1.1a Alternativtexte für Bedienelemente9.1.1.1b Alternativtexte für Grafiken und Objekte9.1.1.1c Leere alt-Attribute für Layoutgrafiken9.1.1.1d Alternativen für CAPTCHAs9.1.2.1a Alternativen für Audiodateien und stumme Videos9.1.2.2a Aufgezeichnete Videos mit Untertiteln9.1.2.3a Audiodeskription oder Volltext-Alternative für Videos9.1.2.4a Videos (live) mit Untertiteln9.1.2.5a Audiodeskription für Videos9.1.3.1a HTML-Strukturelemente für Überschriften9.1.3.1b HTML-Strukturelemente für Listen9.1.3.1c HTML-Strukturelemente für Zitate9.1.3.1d Inhalt geglieder9.1.3.1e Datentabellen richtig aufgebaut9.1.3.1f Zuordnung von Tabellenzellen9.1.3.1g Kein Strukturmarkup für Layouttabellen9.1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar9.1.3.2a Sinnvolle Reihenfolge9.1.3.3a Ohne Bezug auf sensorische Merkmale nutzbar9.1.3.4a Keine Beschränkung der Bildschirmausrichtung9.1.3.5a Eingabefelder zu Nutzerdaten vermitteln den Zweck9.1.4.10a Inhalte brechen um9.1.4.11a Kontraste von Grafiken und grafischen Bedienelementen ausreichend9.1.4.12a Textabstände anpassbar9.1.4.13a Eingeblendete Inhalte bedienbar9.1.4.1a Ohne Farben nutzbar9.1.4.2a Ton abschaltbar9.1.4.3a Kontraste von Texten ausreichend9.1.4.4a Text auf 200% vergrößerbar9.1.4.5a Verzicht auf Schriftgrafiken9.2.1.1a Ohne Maus nutzbar9.2.1.2a Keine Tastaturfalle9.2.1.4a Tastatur-Kurzbefehle abschaltbar oder anpassbar9.2.2.1a Zeitbegrenzungen anpassbar9.2.2.2a Bewegte Inhalte abschaltbar9.2.3.1a Verzicht auf Flackern9.2.4.1a Bereiche überspringbar9.2.4.2a Sinnvolle Dokumenttitel9.2.4.3a Schlüssige Reihenfolge bei der Tastaturbedienung9.2.4.4a Aussagekräftige Linktexte9.2.4.5a Alternative Zugangswege
include::include/author.adoc[]
include::include/attributes.adoc[]

[[multileiste]]
link:/index.php?a=eb&iid=58[die bisherigen Bewertungen für dieses Prüfschritt]

[.stopFloat]

== Technische Angaben

Version

Aktuell

BITV-Bedingung

2.4.5 Alternative Zugangswege

WCAG-Erfolgskriterium

2.4.5 Verschiedene Methoden

Bewertungsalternativen

ja / eher erfüllt / teilweise erfüllt / eher nicht erfüllt / nein / nicht anwendbar

Bezieht sich auf

gesamten Webauftritt

Prüfschritt erfüllt

Zwei unterschiedliche Zugangswege zu den Inhalten des Angebots sind vorhanden.

Prüfschritt nicht anwendbar

Das Webangebot ist nicht informationsorientiert oder es besteht nur aus einer Seite.

== Was wird geprüft?

Es gibt mindestens zwei unterschiedliche Zugangswege, um zu den Inhalten des Angebotes zu gelangen.

== Warum wird das geprüft?

Benutzer bevorzugen verschiedene Zugangswege, um zu Inhalten zu gelangenManche orientieren sich an hierarchischen Navigationsmenüs, andere nutzen ein Inhaltsverzeichnis (Sitemap), noch andere ziehen eine Suchfunktion vorGerade sehbehinderte Benutzer kommen oft schneller über eine Suche zu den gewünschten Inhalten.

Deshalb sollte das Angebot verschiedene Zugangswege zu den Inhalten bereitstellen.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn das Webangebot informationsorientiert ist und aus mehr als einer Seite besteht.

=== Prüfung

Das Angebot auf vorhandene Zugangswege hin betrachtenÜbliche Zugangswege sind:
* Durchgängig verfügbare Navigationsmenüs
* Inhaltsverzeichnis (Sitemap)
* [#G161]Suchfunktion (direkt über ein Sucheingabefeld oder über Verlinkung auf eine zentrale Suchseite)
* [#G185]Alle Seiten des Angebots sind von der Startseite her verlinkt [#G126] oder auf jeder Seite des Angebots verlinkt (nur für kleine Sites geeignet)
* Sequenzielle Verlinkung aller Seiten (höchstens für kleine Sites geeignet, oder für Sites, in denen die Wahrnehmung der Seiten in einer bestimmten Reihenfolge sinnvoll ist)
* als Teil eines Prozesses erzeugte Seiten (etwa als Ergebnis einer Transaktion)
Gibt es mindestens zwei Zugangswege, etwa eine hierarchisches Navigationsmenü und eine Suchfunktion, oder ein Navigationsmenü und ein Inhaltsverzeichnis (Sitemap)?
[#G63][#G64][#G125]Zugangswege stichprobenartig ausprobieren, um deren Funktionsfähigkeit zu überprüfen

=== Hinweise

* Es wird nicht gefordert, dass hierarchische Navigationsmenüs die tieferen Ebenen des Angebots vollständig abbilden.
* Es spielt für diesen Prüfschritt keine Rolle, ob Navigationsmenüs vertikal oder horizontal orientiert sindSie sollen aber als eigenständige Bereiche kenntlich sein.
* Die Kombination aus hierarchischem Hauptmenü und untergeordneten Bereichsmenüs git als *ein* Zugangsweg.
* Ein hierarchischer Navigationspfad (Breadcrumb) ist sinnvollEr gilt jedoch nicht als eigenständiger Zugangsweg, da er nur die Navigation zu höheren Ebenen der Seitenhierarchie erlaubt, nicht den Zugang zu weiter unten liegenden Ebenen.
* Bei kleinen Angeboten mit nur wenigen Seiten, die *alle* von der Startseite verlinkt sind, gilt diese gleichzeitig als Sitemap, sofern auf allen Unterseiten des Angebotes deutlich ein Link auf die Startseite angeboten wird.
* Bei sequenziellen Prozessen kann es sinnvoll sein, dass außer der Navigation zu folgenden und vorhergehenden Prozessschritten keine weitere Navigation angeboten wirdDenn die Seiten (oder Instanzen) des Prozesses machen nur innerhalb des Gesamtprozesses Sinn und sollen nicht einzeln erreichbar seinHier sollte das Fehlen weiterer Navigationsoptionen nicht negativ bewertet werden.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#navigable[Guideline 2.4 Navigable: Provide ways to help users navigate, find content, and determine where they are.]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#multiple-ways[2.4.5 Multiple Ways] (Level AA)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G63.html[G63: Providing a site map]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G64.html[G64: Providing a Table of Contents]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G125.html[G125: Providing links to navigate to related Web pages]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G126.html[G126: Providing a list of links to all other Web pages]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G161.html[G161: Providing a search function to help users find content]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G185.html[G185: Linking to all of the pages on the site from the home page]

== Quellen

=== Multiple Ways - Specific Benefits of Success Criterion 2.4.5:

____
* Providing an opportunity to navigate sites in more than one manner can help people find information fasterUsers with visual impairments may find it easier to navigate to the correct part of the site by using a search, rather than scrolling through a large navigation bar using a screen magnifier or screen readerA person with cognitive disabilities may prefer a table of contents or site map that provides an overview of the site rather than reading and traversing through several Web pagesSome users may prefer to explore the site in a sequential manner, moving from Web page to Web page in order to best understand the concepts and layout.
* Individuals with cognitive limitations may find it easier to use search features than to use a hierarchical navigation scheme that be difficult to understand.
____

Quelle: https://www.w3.org/WAI/WCAG21/Understanding/multiple-ways.html[Multiple Ways: Understanding SC 2.4.5]
