= Prüfschritt 9.2.2.2 Bewegte Inhalte abschaltbar
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Ablenkung durch blinkende oder sich bewegende Elemente soll vermieden werden,
auf 5 Sekunden begrenzt sein oder abschaltbar sein.

Bewegte oder automatisch aktualisierte Inhalte, z.Bperiodisch wechselnde
Nachrichten-Aufmacher (Teaser) sollen zum Lesen anhaltbar sein.

== Warum wird das geprüft?

Viele Benutzer haben Schwierigkeiten, Seiten zu nutzen, die mit blinkenden
oder sich bewegenden Elementen (zum Beispiel Werbung) ausgestattet sindSolche
Elemente lenken abDer Benutzer kann sich möglicherweise nicht auf andere
Elemente des Webauftritts konzentrieren.

Viele Benutzer haben außerdem Schwierigkeiten, blinkende oder bewegte Inhalte
zu lesen, etwa bei Newstickern.

Interaktive bewegte Inhalte können für Benutzer mit motorischen
Einschränkungen problematisch sein.

Automatisch aktualisierte Nachrichten-Aufmacher (Teaser) ändern unangekündigt
die angezeigten Inhalte und stören dadurch die Wahrnehmung und OrientierungDas
beeinträchtigt besonders Nutzer von Bildschirmvergrößerungssoftware und
solche, die mehr Zeit zum Lesen brauchenBei Screenreader-Nutzern kann es zu
unvermittelten Fokus-Verschiebungen kommen.

Einige Bewegungen (etwa von animated gifs) lassen sich über die esc-Taste
beenden, aber die meisten Nutzer kennen diese Funktion nichtAuch das
Deaktivieren von JavaScript führt in manchen Fällen zum Beenden der Bewegung,
etwa von skriptgesteuerten Tickern oder wechselnden TeasernDieses Deaktivieren
ist aber zunehmend problematisch, da sich immer mehr Websites auf aktiviertes
JavaScript verlassenSelbst wenn die Website dann noch funktioniert, wissen
Nutzer nicht, was ihnen ohne JavaScript entgeht.

Schaltflächen zum Beenden der Bewegung sind problematischSie müssen erst
einmal gefunden werden, bevor Benutzer mit ihnen die Bewegung stoppen könnenDa
sie zur Zeit sehr selten eingesetzt werden, erwarten und erkennen Benutzer sie
häufig nicht.

== Wie wird geprüft?

=== 1Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar, wenn bewegte Inhalte gleichzeitig mit
anderen nicht bewegten Inhalten dargestellt werden (etwa die Navigation oder
statische Inhalte).

=== 2Prüfung

Falls die Seite blinkende, bewegte oder automatisch aktualisierte Inhalte
enthält, zum Beispiel Nachrichten-Aufmacher (Teaser), laufende Texte, oder
animierte Werbung:

[#G11][#G152][#SCR22][#SCR33][#F4][#F7][#F47][#F50]Prüfen, ob die Bewegung innerhalb von 5 Sekunden nach Anzeige der Seite von selbst aufhört.
[#G4][#G186][#F16]Falls das nicht der Fall ist: Feststellen, ob sich auf der Seite eine Schaltfläche befindet, mit der man die Bewegung stoppen kann, [#G191]eine gleichwertige nicht-animierte Version der Seite laden kann, [#G187]oder ob es eine klare Anweisung gibt, wie die Bewegung mit der Tastatur angehalten werden kann.
Prüfen, ob das Aktivieren der Schaltfläche oder des Tastatur-Shortcuts die
Bewegung tatsächlich anhält und sie auch nicht wieder von allein erneut
beginnt.
Prüfen, ob das erneute Aktivieren der Schaltfläche die Bewegung wieder in Gang
setzt, und zwar von dem Punkt aus, der beim letztem Anhalten erreicht war.

=== 3Hinweise

Die Schaltfläche oder die Anweisung, mit der man die Bewegung anhalten kann,
muss eindeutig sein und deutlich sichtbar am Seitenbeginn oder im direkten
Kontext des bewegten Inhalts platziert sein.

Alle Inhalte müssen nach dem Anhalten der Bewegung verfügbar bleiben.

Es spielt keine Rolle, ob es sich bei den blinkenden oder sich bewegenden
Inhalten um Werbung oder um redaktionelle Inhalte handelt.

=== 4Bewertung

==== Nicht voll erfüllt:

* Bewegung endet nicht von allein, bewegte und automatisch aktualisierte Inhalte können nicht angehalten, ausgeblendet oder in ihrer Aktualisierungsfrequenz angepasst werden.

== Einordnung des Prüfschritts

=== Abgrenzung der Prüfschritte 2.2.1a und 2.2.2a

Dieser Prüfschritt 2.2.2a betrifft bewegte Inhalte, die Benutzer ablenken oder
durch ihren vorgegebenen zeitlichen Ablauf für bestimmte Benutzer schwierig
wahrnehmbar sindHier wird geprüft, ob Benutzer die Möglichkeit haben, bewegte
Inhalte anzuhalten oder auszublenden.

Der Prüfschritt link:/index.php?a=di&iid=90&s=n[2.2.1a] "Zeitbegrenzungen anpassbar" betrifft Zeitbegrenzungen, welche die ganze Seite betreffen, unabhängig davon, ob die zeitbegrenzten Inhalte bewegt sind (also ablenken) oder nichtGeprüft wird, ob solche Zeitbegrenzungen abschaltbar oder verlängerbar sind.

Zur Abgrenzung von Blinken und Flackern siehe Abschnitt "Quellen" bei Prüfschritt link:/index.php?a=di&iid=21&s=n[2.3.1a] "Verzicht auf Flackern".

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#enough-time[Guideline 2.2 Enough Time: Provide users enough time to read and use content.]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#pause-stop-hide[2.2.2 Pause, Stop, Hide] (Level A)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G4[G4: Allowing the content to be paused and restarted from where it was paused]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G11.html[G11: Creating content that blinks for less than 5 seconds]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G152.html[G152: Setting animated gif images to stop blinking after n cycles (within 5 seconds)]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G186.html[G186: Using a control in the Web page that stops moving, blinking, or auto-updating content]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G191.html[G191: Providing a link, button, or other mechanism that reloads the page without any blinking content]

===== Scripting Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR22.html[SCR22: Using scripts to control blinking and stop it in five seconds or less]
* https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR33.html[SCR33: Using script to scroll content, and providing a mechanism to pause it]

===== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F4.html[F4: Failure of Success Criterion 2.2.2 due to using text-decoration:blink without a mechanism to stop it in less than five seconds]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F7.html[F7: Failure of Success Criterion 2.2.2 due to an `object` or `applet`, such as Java or Flash, that has blinking content without a mechanism to pause the content that blinks for more than five seconds]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F16.html[F16: Failure of Success Criterion 2.2.2 due to including scrolling content where movement is not essential to the activity without also including a mechanism to pause and restart the content]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F47.html[F47: Failure of Success Criterion 2.2.2 due to using the blink element]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F50.html[F50: Failure of Success Criterion 2.2.2 due to a script that causes a blink effect without a mechanism to stop the blinking at 5 seconds or less]

== Quellen

=== Die WCAG 2.1 zum Anhalten und Fortsetzen bei aufgezeichneten Inhalten und Echtzeit-Inhalten

____
Content that is paused can either resume in real-time or continue playing from
the point in the presentation where the user left off.

Pausing and resuming where the user left off is best for users who want to
pause to read content and works best when the content is not associated with a
real-time event or status.
+
_Note_: See https://www.w3.org/WAI/WCAG21/Understanding/timing-adjustable.html[Understanding Success Criterion 2.2.1 Timing Adjustable] for additional requirements related to time-limits for reading.
Pausing and jumping to current display (when pause is released) is better for information that is real-time or "status" in natureFor example, weather radar, a stock ticker, a traffic camera, or an auction timer, would present misleading information if a pause caused it to display old information when the content was restarted.
+
_Note_: Hiding content would have the same result as pausing and jumping to
current display (when pause is released).
____

Quelle: https://www.w3.org/WAI/WCAG21/Understanding/pause-stop-hide.html[Pause, Stop, Hide: Understanding SC 2.2.2]
