= Prüfschritt 9.1.1.1a Alternativtexte für Bedienelemente9.1.1.1b Alternativtexte für Grafiken und Objekte9.1.1.1c Leere alt-Attribute für Layoutgrafiken9.1.1.1d Alternativen für CAPTCHAs9.1.2.1a Alternativen für Audiodateien und stumme Videos9.1.2.2a Aufgezeichnete Videos mit Untertiteln9.1.2.3a Audiodeskription oder Volltext-Alternative für Videos9.1.2.4a Videos (live) mit Untertiteln9.1.2.5a Audiodeskription für Videos9.1.3.1a HTML-Strukturelemente für Überschriften9.1.3.1b HTML-Strukturelemente für Listen9.1.3.1c HTML-Strukturelemente für Zitate9.1.3.1d Inhalt geglieder9.1.3.1e Datentabellen richtig aufgebaut9.1.3.1f Zuordnung von Tabellenzellen9.1.3.1g Kein Strukturmarkup für Layouttabellen9.1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar9.1.3.2a Sinnvolle Reihenfolge9.1.3.3a Ohne Bezug auf sensorische Merkmale nutzbar9.1.3.4a Keine Beschränkung der Bildschirmausrichtung9.1.3.5a Eingabefelder zu Nutzerdaten vermitteln den Zweck9.1.4.10a Inhalte brechen um9.1.4.11a Kontraste von Grafiken und grafischen Bedienelementen ausreichend9.1.4.12a Textabstände anpassbar9.1.4.13a Eingeblendete Inhalte bedienbar9.1.4.1a Ohne Farben nutzbar9.1.4.2a Ton abschaltbar9.1.4.3a Kontraste von Texten ausreichend9.1.4.4a Text auf 200% vergrößerbar9.1.4.5a Verzicht auf Schriftgrafiken9.2.1.1a Ohne Maus nutzbar9.2.1.2a Keine Tastaturfalle9.2.1.4a Tastatur-Kurzbefehle abschaltbar oder anpassbar9.2.2.1a Zeitbegrenzungen anpassbar9.2.2.2a Bewegte Inhalte abschaltbar9.2.3.1a Verzicht auf Flackern
include::include/author.adoc[]
include::include/attributes.adoc[]

[[multileiste]]
link:/index.php?a=eb&iid=21[die bisherigen Bewertungen für dieses Prüfschritt]

[.stopFloat]##

== [#technische-angaben]####Technische Angaben

Version

Aktuell

BITV-Bedingung

2.3.1 Dreimaliges Aufblitzen – Unterschreiten der Schwellenwerte

WCAG-Erfolgskriterium

2.3.1 Grenzwert von dreimaligem Blitzen oder weniger

Bewertungsalternativen

ja / nein

Bezieht sich auf

einzelne Webseite

Prüfschritt erfüllt

Webseiten enthalten kein Flackern.

== [#was-wird-geprueft]####Was wird geprüft?

Die Seite enthält keine Elemente, die in einem Zeitraum von einer Sekunde häufiger als dreimal aufblitzen.

== [#warum-wird-das-geprueft]####Warum wird das geprüft?

Bei Menschen mit Epilepsie kann längeres Flackern in bestimmten Frequenzen einen Anfall auslösen.

== [#wie-wird-geprueft]####Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

=== 2. Prüfung

[#G15]####Gibt es auf der Webseite flackernde Inhalte, die nicht spätestens nach dreimaligem Flackern in einem Zeitraum von Sekunde aufhören?

[#G176]####Zur Einschätzung der Größe des flackernden Bereichs kann, wenn nötig, die WCAG 2.1 http://www.w3.org/TR/2008/NOTE-WCAG20-TECHS-20081211/G176#smallsafe1[Formel 1] herangezogen werden.

=== 3. Hinweis zur Abwertung

Wenn die Seite größere flackernde Elemente enthält, wird das Gesamtergebnis der Prüfung abgewertet. Flackern wird dadurch hervorgerufen, dass die Farbe oder das Muster einer Fläche pro Sekunde mindestens 4 mal wechselt.

== [#einordnung-des-pruefschritts]####Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guidelines

* https://www.w3.org/WAI/WCAG21/quickref/#no-timing[Guideline 2.3 Do not design content in a way that is known to cause seizures]

==== Success criteria

* https://www.w3.org/WAI/WCAG21/quickref/#three-flashes-or-below-threshold[2.3.1 Three Flashes or Below Threshold]

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G15.html[G15: Using a tool to ensure that content does not violate the general flash threshold or red flash threshold]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G176.html[G176: Keeping the flashing area small enough]

== [#quellen]####Quellen

=== Die WCAG 2.1 zu General flash and red flash thresholds

____
A flash or rapidly changing image sequence is below the threshold (i.e., content passes) if any of the following are true:

. there are no more than three general flashes and / or no more than three red flashes within any one-second period; or
. the combined area of flashes occurring concurrently occupies no more than a total of .006 steradians within any 10 degree visual field on the screen (25% of any 10 degree visual field on the screen) at typical viewing distance

where:

* A general flash is defined as a pair of opposing changes in relative luminance of 10% or more of the maximum relative luminance where the relative luminance of the darker image is below 0.80; and where "a pair of opposing changes" is an increase followed by a decrease, or a decrease followed by an increase, and
* A red flash is defined as any pair of opposing transitions involving a saturated red.
____

Quelle: https://www.w3.org/WAI/WCAG21/Understanding/three-flashes-or-below-threshold.html[Three Flashes or Below Threshold: Understanding SC 2.3.1]

=== Die WCAG 2.1 zur Abgrenzung von Blinken und Flackern

____
Note: The terms "blinking" and "flashing" can sometimes refer to the same content.

* "Blinking" refers to content that causes a distraction problem. Blinking can be allowed for a short time as long as it stops (or can be stopped)
* "Flashing" refers to content that can trigger a seizure (if it is more than 3 per second and large and bright enough). This cannot be allowed even for a second or it could cause a seizure. And turning the flash off is also not an option since the seizure could occur faster than most users could turn it off.
* Blinking usually does not occur at speeds of 3 per second or more, but it can. If blinking occurs faster than 3 per second, it would also be considered a flash.
____

Quelle: https://www.w3.org/WAI/WCAG21/Understanding/pause-stop-hide.html[Pause, Stop, Hide: Understanding SC 2.2.2]
