= Prüfschritt 9.2.4.6 Aussagekräftige Überschriften und Beschriftungen
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Überschriften beschreiben den folgenden Inhalt, Beschriftungen sind sinngebend.

== Warum wird das geprüft?

Visuell werden Webseiten-Inhalte durch Überschriften strukturiert. Dank dieser Strukturierung wissen Nutzende, was zusammengehört, können die
Inhalte der Webseite leicht überblicken und gezielt auf Inhalte zugreifen, die sie interessieren.

Wenn Formularelemente sinngebend beschriftet sind, können Sie von Nutzenden als solche erkannt und bedient werden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn es auf der Seite Inhalte gibt, die durch Überschriften strukturiert werden können und wenn die Seite Formularelemente
enthält.

=== 2. Prüfung

. Seite im
  https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste.html#c1078[
  Firefox] laden.
. Prüfen, ob die Überschriften im Zusammenhang mit den durch sie strukturierten Inhalten aussagekräftig sind.
. Prüfen, ob Beschriftungen von Formularelementen aussagekräftig sind.
. Wenn zur Gruppen-Beschriftung `fieldset` mit `legend` eingesetzt wird: Ist die Ausgabe von `legend` und ``label`` im Zusammenhang aussagekräftig?

=== 3. Hinweise

Besonders in Fachanwendungen gibt es Labels und Überschriften, die in dem betreffenden Nutzerkreis bestimmten, etablierten Vokabularen entsprechen (einschließlich viel genutzter Abkürzungen).
Die Verwendung in Interfaces bringt Vorteile mit (Wiedererkennbarkeit, Präzision, Kürze), kann aber auch dazu führen, dass sie nicht unbedingt für jeden aussagekräftig oder anschaulich sind, was aber nicht zu einer negativen Bewertung führen soll.

== Einordnung des Prüfschritts

=== Abgrenzung von anderen Prüfschritten

In diesem Prüfschritt geht es um die Aussagekraft von Überschriften und
Beschriftungen.
Die programmatische Ermittelbarkeit durch Assistive Technologien ist den Prüfkriterien
ifdef::env_embedded[9.1.3.1a "HTML-Strukturelemente für Überschriften"]
ifndef::env_embedded[]
  <<9.1.3.1a HTML-Strukturelemente für Überschriften.adoc#,9.1.3.1a
  HTML-Strukturelemente für Überschriften>>
endif::env_embedded[]
und
ifdef::env_embedded[9.1.3.1h "Beschriftung von Formularelementen programmatisch ermittelbar"]
ifndef::env_embedded[]
  <<9.1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar.adoc#,9.1.3.1h Beschriftung von
  Formularelementen programmatisch ermittelbar>>
endif::env_embedded[]
zugeordnet.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#navigable[
  Guideline 2.4 Navigable: Provide ways to help users navigate, find content,
  and determine where they are.]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#headings-and-labels[
  2.4.6 Headings and Labels] (Level A)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G130.html[
  G130: Providing descriptive headings]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G131.html[
  G131: Providing descriptive labels]
