= Prüfschritt 9.2.4.2 Sinnvolle Dokumenttitel
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Dokumenttitel bezeichnen die Site und den Inhalt der jeweiligen Seite, sie
können für die Unterscheidung und Auswahl von Seiten genutzt werden.

== Warum wird das geprüft?

Dokumenttitel vertreten die Seiten, zum Beispiel in Listen mit Bookmarks.
Sie
sind wichtig für die Navigation und Orientierung in Webangeboten.
Wenn das
Angebot oder der Inhalt der Seite nicht bezeichnet sind, ist die Orientierung
beeinträchtigt.

Typographische Schmuckelemente werden Screenreader-Nutzern unter Umständen
vorgelesen und stören dadurch.

== Wie wird geprüft?

=== 1Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

=== [#G88][#G127][#H25][#F25]2Prüfung

Dokumenttitel in der Browserleiste ansehen.
Bezeichnet der Titel die Website und
den Inhalt der jeweiligen Seite, ist er für die Unterscheidung und Auswahl von
Seiten geeignet?

Falls Seiten Frames haben:

* Einzelne Frames in neuem Tab oder Fenster öffnen.
* Dokumenttitel in der Browserleiste ansehen.
Haben die Frame-Seiten sinnvolle Titel, die Zweck oder Inhalt des Frames kennzeichnen?

=== 3Hinweis

Der Dokumenttitel muss nicht den Pfad von der Startseite zur aktuellen Seite wiedergeben.
Ein guter Dokumenttitel "vertritt" die Seite zum Beispiel in einer Bookmarks-Liste.

=== 4Bewertung

==== Erfüllt:

* Der Dokumenttitel enthält zwei Bestandteile: eine immer gleiche, allgemeine Bezeichnung des Webauftritts und eine unterscheidende, individuelle Bezeichnung der jeweiligen Seite.

==== Nicht voll erfüllt:

* Die allgemeine Bezeichnung des Webauftritts fehlt.
* Frame-Seiten haben keine sinnvollen Dokumenttitel.
* [#H86]Dokumenttitel enthalten typographischen Schmuck (etwa ++++, ~~~~, ====)

==== Eher nicht erfüllt:

* Die individuelle Bezeichnung der jeweiligen Seite fehlt.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=241#navigable[Guideline 2.4 Navigable: Provide ways to help users navigate, find content, and determine where they are]

==== Success criteria

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=241#page-titled[2.4.2 Page Titled: Web pages have titles that describe topic or purpose.] (Level A)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G88.html[G88: Providing descriptive titles for Web pages]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G127.html[G127: Identifying a Web page's relationship to a larger collection of Web pages]

===== HTML Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/html/H25.html[H25: Providing a title using the title element]
* https://www.w3.org/WAI/WCAG21/Techniques/html/H86.html[H86: Providing text alternatives for ASCII art, emoticons, and leetspeak]

==== Failure

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F25.html[F25: Failure of Success Criterion 2.4.2 due to the title of a Web page not identifying the contents]

== Quellen

=== Bedeutung von Dokumenttiteln nach WCAG 2.1

____
*Specific Benefits of Success Criterion 2.4.2:*

* This criterion benefits all users in allowing users to quickly and easily identify whether the information contained in the Web page is relevant to their needs.
* People with visual disabilities will benefit from being able to differentiate content when multiple Web pages are open.
* People with cognitive disabilities, limited short-term memory and reading disabilities also benefit from the ability to identify content by its title.
* This criterion also benefits people with severe mobility impairments whose mode of operation relies on audio when navigating between Web pages.
____

Quelle: https://www.w3.org/WAI/WCAG21/Understanding/page-titled.html[Page Titled: Understanding SC 2.4.2]
