= Prüfschritt 9.3.3.3a Hilfe bei Fehlern
include::include/author.adoc[]
include::include/attributes.adoc[]

[[multileiste]]
link:/index.php?a=eb&iid=104[die bisherigen Bewertungen für dieses Prüfschritt]

[.stopFloat]

== Technische Angaben

Version

Aktuell

BITV-Bedingung

3.3.3 Korrekturvorschläge

WCAG-Erfolgskriterium

3.3.3 Fehlerempfehlung

Bewertungsalternativen

ja / eher erfüllt / teilweise erfüllt / eher nicht erfüllt / nein / nicht anwendbar

Bezieht sich auf

einzelne Webseite

Prüfschritt erfüllt

Wird ein Eingabefehler automatisch festgestellt, wird der Fehler in Textform
beschriebenWo sinnvoll, werden Korrekturvorschläge gemacht.

Prüfschritt nicht anwendbar

Die Seite hat keine Formulare oder es gibt keine Fehlerbehandlung.

== Was wird geprüft?

Wenn ein Formular Fehlermeldungen erzeugt, müssen diese verständlich sein und
Hinweise geben, wie der Fehler zu korrigieren ist.

== Warum wird das geprüft?

Bei Formulareingaben kommt es öfters zu Fehlern: Nutzer verschreiben sich oder
überspringen benötigte Eingaben.

Wenn das Angebot Nutzereingaben überprüft, sollen die ausgegebenen
Fehlermeldungen hilfreich sein und es den Nutzern erleichtern, Eingaben zu
korrigieren.

== Wie wird geprüft?

=== 1Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Seite Formulare enthält, welche bei
inkorrektem Ausfüllen Fehlermeldungen erzeugenDies kann schon während der
Eingabe oder erst nach dem Abschicken des Formulars geschehen.

=== [#G83]2Prüfung

Formular unvollständig oder fehlerhaft ausfüllen, etwa durch das Leerlassen
von Pflichtfeldern oder das Eingeben syntaktisch nicht korrekter
Email-Adressen.
[#G84][#G85][#SCR18]Falls das Abschicken des Formulars eine Fehlermeldung erzeugt: Prüfen, ob Fehlermeldungen oder Korrekturvorschläge verständlich und sinnvoll sind.
+
Fehlermeldungen oder Korrekturvorschläge können auf verschiedene Weise zur
Verfügung gestellt werden, z.B.:
* Bei Neuanzeige des Formulars werden am Seitenbeginn Fehler beschrieben.
* [#G177]Korrekturvorschläge werden nahe der betroffenen Eingabefelder angezeigt und mit einer geeigenten ARIA-Technik verknüpft.

=== 3Hinweise

* Wenn serverseitig eine Fehlermeldung auf neuer Seite ausgegeben wird, wir diese wie ein Seitenzustand unter der Ausgangsseite mitgeprüftGeprüft wird auch die Erfüllung anderer relevanter Prüfkriterien.
* Bei komplizierten Formaten, z.BDatum, hilft eine Angabe, in welcher Weise das Datum eingegeben werden soll (z.Btt.mm.jjjj), Fehler zu vermeiden.
* Wenn Formulare keine Fehlermeldungen erzeugen, ist dies nicht negativ zu bewerten.

=== 4Bewertung

==== Nicht erfüllt:

* [#SCR32]Fehlermeldungen sind unklar oder irreführend

== Einordnung des Prüfschritts

=== Abgrenzung von anderen Prüfschritten

Die Identifizierung und Benennung des Fehlers, ist Gegenstand des Prüfschritts link:/index.php?a=di&iid=103&s=n[3.3.1a] "Fehlererkennung".

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=334#input-assistance[Guideline 3.3 Input Assistance: Help users avoid and correct mistakes.]

==== Success criteria

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=334#error-suggestion[3.3.3 Error Suggestion] (Level AA)

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G83.html[G83: Providing text descriptions to identify required fields that were not completed]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G84.html[G84: Providing a text description when the user provides information that is not in the list of allowed values]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G85.html[G85: Providing a text description when user input falls outside the required format or values]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G177.html[G177: Providing suggested correction text]

===== Scripting Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR18.html[SCR18: Providing client-side validation and alert]
* https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR32.html[SCR32: Providing client-side validation and adding error text via the DOM]

===== ARIATechniques

* https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA2.html[ARIA2: Identifying a required field with the aria-required property]
* https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA18.html[ARIA18: Using aria-alertdialog to Identify Errors]
