= Prüfschritt 9.1.1.1a Alternativtexte für Bedienelemente9.1.1.1b Alternativtexte für Grafiken und Objekte9.1.1.1c Leere alt-Attribute für Layoutgrafiken9.1.1.1d Alternativen für CAPTCHAs9.1.2.1a Alternativen für Audiodateien und stumme Videos9.1.2.2a Aufgezeichnete Videos mit Untertiteln9.1.2.3a Audiodeskription oder Volltext-Alternative für Videos9.1.2.4a Videos (live) mit Untertiteln9.1.2.5a Audiodeskription für Videos9.1.3.1a HTML-Strukturelemente für Überschriften9.1.3.1b HTML-Strukturelemente für Listen9.1.3.1c HTML-Strukturelemente für Zitate9.1.3.1d Inhalt geglieder9.1.3.1e Datentabellen richtig aufgebaut9.1.3.1f Zuordnung von Tabellenzellen9.1.3.1g Kein Strukturmarkup für Layouttabellen9.1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar9.1.3.2a Sinnvolle Reihenfolge9.1.3.3a Ohne Bezug auf sensorische Merkmale nutzbar9.1.3.4a Keine Beschränkung der Bildschirmausrichtung9.1.3.5a Eingabefelder zu Nutzerdaten vermitteln den Zweck9.1.4.10a Inhalte brechen um9.1.4.11a Kontraste von Grafiken und grafischen Bedienelementen ausreichend9.1.4.12a Textabstände anpassbar9.1.4.13a Eingeblendete Inhalte bedienbar9.1.4.1a Ohne Farben nutzbar9.1.4.2a Ton abschaltbar9.1.4.3a Kontraste von Texten ausreichend9.1.4.4a Text auf 200% vergrößerbar9.1.4.5a Verzicht auf Schriftgrafiken9.2.1.1a Ohne Maus nutzbar9.2.1.2a Keine Tastaturfalle9.2.1.4a Tastatur-Kurzbefehle abschaltbar oder anpassbar9.2.2.1a Zeitbegrenzungen anpassbar9.2.2.2a Bewegte Inhalte abschaltbar9.2.3.1a Verzicht auf Flackern9.2.4.1a Bereiche überspringbar9.2.4.2a Sinnvolle Dokumenttitel9.2.4.3a Schlüssige Reihenfolge bei der Tastaturbedienung9.2.4.4a Aussagekräftige Linktexte9.2.4.5a Alternative Zugangswege9.2.4.6a Aussagekräftige Überschriften und Beschriftungen9.2.4.7a Aktuelle Position des Fokus deutlich9.2.5.1a Alternativen für komplexe Zeiger-Gesten9.2.5.2a Zeigergesten-Eingaben können abgebrochen oder widerrufen werden9.2.5.3a Sichtbare Beschriftung Teil des zugänglichen Namens9.2.5.4a Alternativen für Bewegungsaktivierung9.3.1.1a Hauptsprache angegeben9.3.1.2a Anderssprachige Wörter und Abschnitte ausgezeichnet9.3.2.1a Keine unerwartete Kontextänderung bei Fokus
include::include/author.adoc[]
include::include/attributes.adoc[]

[[multileiste]]
link:/index.php?a=eb&iid=95[die bisherigen Bewertungen für dieses Prüfschritt]

[.stopFloat]##

== [#technische-angaben]####Technische Angaben

Version

link:/index.php?a=di&iid=26[bis 10.07.2017] | Aktuell

BITV-Bedingung

3.2.1 Bei Fokussierung

WCAG-Erfolgskriterium

3.2.1 Bei Fokus

Bewertungsalternativen

ja / eher erfüllt / teilweise erfüllt / eher nicht erfüllt / nein

Bezieht sich auf

einzelne Webseite

Prüfschritt erfüllt

Fokus führt nicht zu einer unerwarteten Kontextänderung.

== [#was-wird-geprueft]####Was wird geprüft?

Wenn irgendeine Komponente der Seite den Fokus erhält, soll dies nicht zu einer unerwarteten Kontextänderung führen.

== [#warum-wird-das-geprueft]####Warum wird das geprüft?

Unerwartete und unangekündigte Kontextänderungen bei von Fokussierung einer Komponente (z.B. das automatisches Abschicken von Formularen), können die Orientierung von Nutzern beeinträchtigen. Kontextänderungen auf der Seite selbst können Nutzer ablenken und verwirren oder auch unbemerkt bleiben und dadurch für Verwirrung sorgen. Sie sollten deshalb erwartet und klar nachvollziehbar sein.

Das Öffnen neuer Fenster bei Fokussierung einer Komponente oder beim Laden einer Seite kann die Orientierung des Benutzers ebenfalls beeinträchtigen. Das gilt ganz besonders für blinde und sehbehinderte Benutzer. Sie bemerken möglicherweise nicht, dass sich der Kontext geändert hat. Wenn das neue Fenster den Fokus erhält, funktioniert der Zurück-Button des Browsers nicht mehr. Der Überblick kann verloren gehen, möglicherweise wird dann versehentlich das falsche Fenster (mit der History der bislang besuchten Seiten) geschlossen.

== [#wie-wird-geprueft]####Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

=== 2. Prüfung

. Seite im http://www.bitvtest.de/bitvtest/das_testverfahren_im_detail/werkzeugliste.html#firefox[Firefox] aufrufen.
. [#F52]####Das Laden der Seite sollte kein neues Fenster öffnen.
. Mit der Tabulatortaste die Links und Formularelemente durchgehen. Der Fokuserhalt soll keine automatischen Kontextänderungen (etwa Pop-up-Fenster oder automatisches Abschicken von Formularen) auslösen.

=== Hinweise

Der Prüfschritt bezieht sich nur auf neue Browserfenster, nicht auf skriptgesteuerte Seiten-Elemente, die den Inhalt überlagern (Stichwort Lightbox).

Das Öffnen von Custom Tooltips, also nicht modalen Fenstern, die sich beim Weitertabben oder Mausklick selbständig schließen, gilt dabei nicht als Kontextänderung.

== [#einordnung-des-pruefschritts]####Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#predictable[Guideline 3.2 Predictable: Make Web pages appear and operate in predictable ways.]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#on-focus[3.2.1 On Focus] (Level A)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G107.html[G107: Using "activate" rather than "focus" as a trigger for changes of context]

===== Advisory Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G200.html[G200: Opening new windows and tabs from a link only when necessary]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G201.html[G201: Giving users advanced warning when opening a new window]

===== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F52.html[F52: Failure of Success Criterion 3.2.1 due to opening a new window as soon as a new page is loaded]

== [#faq]####Fragen zu diesem Prüfschritt

=== Der Prüfschritt bezieht sich nur auf das Öffnen neuer Fenster beim Laden der Seite. Erlaubt die BITV 2.0 jetzt das unangekündigte Öffnen von neuen Fenstern über Links?

Die WCAG empfehlen in den _Advisory Techniques_ https://www.w3.org/WAI/WCAG21/Techniques/general/G200.html[G200] und https://www.w3.org/WAI/WCAG21/Techniques/general/G201.html[G201], das Öffnen neuer Fenster auf Fälle zu beschränken, in denen das aus einer Zugänglichkeitsperspektive sinnvoll ist und Benutzer zuvor über das Öffnen eines neuen Fensters zu informieren (etwa als Teil des Links, der das Fenster öffnet).

Das unangekündigte Öffnen neuer Fenster bei der Aktivierung von Links wird jedoch grundsätzlich akzeptiert. Dies ist dadurch gerechtfertigt, das moderne Benutzeragenten Einstellungsmöglichkeiten für den Umgang mit automatisch öffnenden Fenstern bieten. In den meisten aktuellen Browser-Versionen lässt sich inzwischen festlegen, ob neue Fenster also zusätzliches Browser-Fenster oder in einem Tab (Registrierkarte) geöffnet werden sollen oder ob unangekündigte Fenster grundsätzlich unterdrückt werden sollen (Stichwort Popup-Blocker). Einige Browser (Firefox) erlauben auch die Festlegung, ob neue Tabs im Vordergrund geöffnet werden sollen (also den Fokus erhalten sollen) oder nicht.
