= Prüfschritt 9.3.3.4a Fehlervermeidung wird unterstützt
include::include/author.adoc[]
include::include/attributes.adoc[]

[[multileiste]]
link:/index.php?a=eb&iid=51[die bisherigen Bewertungen für dieses Prüfschritt]

[.stopFloat]

== Technische Angaben

Version

Aktuell

BITV-Bedingung

3.3.4 Fehlervermeidung

WCAG-Erfolgskriterium

3.3.4 Fehlervermeidung (rechtliche, finanzielle, Daten)

Bewertungsalternativen

ja / eher erfüllt / teilweise erfüllt / eher nicht erfüllt / nein / nicht anwendbar

Bezieht sich auf

einzelne Webseite

Prüfschritt erfüllt

Verpflichtende Dateneingaben können rückgängig gemacht oder vor dem Abschicken überprüft und korrigiert werden.

== Was wird geprüft?

Bei wichtigen Dateneingaben (etwa bei finanziellen Transaktionen) gibt es die Möglichkeit, die Dateneingabe rückgängig zu machen oder sie vor dem Abschicken zu überprüfen und zu korrigierenErfolgreiche Eingaben werden bestätigt.

== Warum wird das geprüft?

Bei jeder Dateneingabe können Fehler passierenGerade wenn sich der Prozess nicht rückgängig machen lässt, ist es wichtig, Benutzer dazu anzuhalten, die eingegebenen Daten vor dem Abschicken noch einmal zu überprüfen.

Dies ist für alle Benutzer wichtigFür Benutzer mit Behinderungen ist jedoch in vielen Fällen das Risiko von Fehleingaben größerBenutzer mit Legastenie vertauschen häufiger Zahlen, Benutzer mit motorischen Einschränkungen drücken häufiger versehentlich falsche TastaturtastenDeshalb ist das Rückgängig-Machen oder Anzeigen, Überprüfen und gegebenenfalls Korrigieren eingegebener Daten für diese Benutzer besonders wichtig.

== Wie wird geprüft?

=== 1Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Seite Formulare für Transaktionen enthält, durch die Nutzer rechtlich bindende Verpflichtungen eingehenDazu gehören Online-Bestellvorgänge und andere finanzielle Transaktionen.

=== 2Prüfung

Formular mit Beispieldaten ausfüllen und Prozess fortsetzenEine der folgenden drei Optionen soll erfüllt sein:

[#G98]**Datenanzeige mit Korrekturmöglichkeit.** Die eingegebenen Daten werden dem Benutzer vor dem Abschicken noch einmal angezeigt, es gibt an dieser Stelle die Möglichkeit, die Daten zu korrigieren.
[#G168]**Bestätigung.** Das Abschicken erfolgt erst nach Bestätigung eines Dialogs, der die Konsequenzen der Transaktion beschreibt.
[#G99][#G164]*Unmittelbare Rückabwicklung.* Die Transaktion (etwa das Löschen von angelegten Datensätzen) kann unmittelbar rückgängig gemacht werden.

=== 3Hinweise

Eine Checkbox oberhalb des "Abschicken"-Buttons zur Bestätigung der Richtigkeit von Benutzereingaben ist ein wesentlich schwächeres Instrument als die Anzeige der kompletten Eingabe auf einer neuen Seite vor dem endgültigen Abschicken des FormularsSolche Checkboxen werden häufig für formalrechtlich relevante Funktionen genutzt, wie etwa die Bestätigung der Geschäftsbedingungen eines AnbietersSie werden deshalb von vielen Benutzern nicht richtig wahrgenommen und routinemäßig gesetztFür die Bestätigung wichtiger Eingaben sind sie deshalb weniger geeignet.

[#G199]Erfolgreiche Eingaben sollten nach dem Abschicken bestätigt werden.

=== 4Bewertung

==== Nicht voll erfüllt:

* Daten werden vor dem Abschicken zum Überprüfen angezeigt, es gibt aber keinen expliziten Link zurück zum Formular, um Daten zu korrigieren oder zu ergänzen.
* [#G155]Es gibt weder eine Datenanzeige mit Korrekturmöglichkeit noch die Möglichkeit der unmittelbaren RückabwicklungZum Bestätigen der Eingabe gibt es keinen Dialog, sondern lediglich eine Checkbox über dem "Abschicken"-Button.
* Nach dem erfolgreichen Abschicken gibt es keine Bestätigung.

==== Nicht erfüllt:

* Wichtige Daten werden ohne vorherige Datenanzeige, Dialog zur Bestätigung, oder Möglichkeit der sofortigen Rückabwicklung abgeschickt.
* Bei Neuanzeige des Formulars sind bereits gemachte Eingaben gelöscht, die Felder sind wieder leer und müssen erneut ausgefüllt werden.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#input-assistance[Guideline 3.3 Input Assistance: Help users avoid and correct mistakes.]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#error-prevention-legal-financial-data[3.3.4 Error prevention (Legal, Financial, Data)] (Level AA)

==== Techniques

===== General techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G98.html[G98: Providing the ability for the user to review and correct answers before submitting]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G99[G99: Providing the ability to recover deleted information]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G155[G155: Providing a checkbox in addition to a submit button]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G164[G164: Providing a stated time within which an online request (or transaction) may be amended or canceled by the user after making the request]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G168[G168: Requesting confirmation to continue with selected action]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G199[G199: Providing success feedback when data is submitted successfully]
