= Prüfschritt 9.1.1.1a Alternativtexte für Bedienelemente9.1.1.1b Alternativtexte für Grafiken und Objekte9.1.1.1c Leere alt-Attribute für Layoutgrafiken9.1.1.1d Alternativen für CAPTCHAs9.1.2.1a Alternativen für Audiodateien und stumme Videos9.1.2.2a Aufgezeichnete Videos mit Untertiteln9.1.2.3a Audiodeskription oder Volltext-Alternative für Videos9.1.2.4a Videos (live) mit Untertiteln9.1.2.5a Audiodeskription für Videos9.1.3.1a HTML-Strukturelemente für Überschriften9.1.3.1b HTML-Strukturelemente für Listen9.1.3.1c HTML-Strukturelemente für Zitate9.1.3.1d Inhalt geglieder9.1.3.1e Datentabellen richtig aufgebaut9.1.3.1f Zuordnung von Tabellenzellen9.1.3.1g Kein Strukturmarkup für Layouttabellen9.1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar9.1.3.2a Sinnvolle Reihenfolge9.1.3.3a Ohne Bezug auf sensorische Merkmale nutzbar9.1.3.4a Keine Beschränkung der Bildschirmausrichtung9.1.3.5a Eingabefelder zu Nutzerdaten vermitteln den Zweck9.1.4.10a Inhalte brechen um9.1.4.11a Kontraste von Grafiken und grafischen Bedienelementen ausreichend9.1.4.12a Textabstände anpassbar9.1.4.13a Eingeblendete Inhalte bedienbar9.1.4.1a Ohne Farben nutzbar9.1.4.2a Ton abschaltbar9.1.4.3a Kontraste von Texten ausreichend9.1.4.4a Text auf 200% vergrößerbar9.1.4.5a Verzicht auf Schriftgrafiken9.2.1.1a Ohne Maus nutzbar9.2.1.2a Keine Tastaturfalle9.2.1.4a Tastatur-Kurzbefehle abschaltbar oder anpassbar9.2.2.1a Zeitbegrenzungen anpassbar9.2.2.2a Bewegte Inhalte abschaltbar9.2.3.1a Verzicht auf Flackern9.2.4.1a Bereiche überspringbar9.2.4.2a Sinnvolle Dokumenttitel9.2.4.3a Schlüssige Reihenfolge bei der Tastaturbedienung9.2.4.4a Aussagekräftige Linktexte9.2.4.5a Alternative Zugangswege9.2.4.6a Aussagekräftige Überschriften und Beschriftungen9.2.4.7a Aktuelle Position des Fokus deutlich9.2.5.1a Alternativen für komplexe Zeiger-Gesten9.2.5.2a Zeigergesten-Eingaben können abgebrochen oder widerrufen werden9.2.5.3a Sichtbare Beschriftung Teil des zugänglichen Namens9.2.5.4a Alternativen für Bewegungsaktivierung9.3.1.1a Hauptsprache angegeben9.3.1.2a Anderssprachige Wörter und Abschnitte ausgezeichnet9.3.2.1a Keine unerwartete Kontextänderung bei Fokus9.3.2.2a Keine unerwartete Kontextänderung bei Eingabe
include::include/author.adoc[]
include::include/attributes.adoc[]

[[multileiste]]
link:/index.php?a=eb&iid=96[die bisherigen Bewertungen für dieses Prüfschritt]

[.stopFloat]##

== [#technische-angaben]####Technische Angaben

Version

link:/index.php?a=di&iid=47[bis 10.07.2017] | Aktuell

BITV-Bedingung

3.2.2 Bei Eingabe

WCAG-Erfolgskriterium

3.2.2 Bei Eingabe

Bewertungsalternativen

ja / eher erfüllt / teilweise erfüllt / eher nicht erfüllt / nein / nicht anwendbar

Bezieht sich auf

einzelne Webseite

Prüfschritt erfüllt

Formulareingaben führen nicht zu unerwarteten Kontextänderungen.

== [#was-wird-geprueft]####Was wird geprüft?

Nutzereingaben auf Formularen sollen nicht zu unerwarteten Kontext-Änderungen führen. Alle Kontextänderungen müssen unterhalb des auslösenden Elements geschehen und sollen klar nachvollziehbar sein, der Fokus soll nicht versetzt werden.

== [#warum-wird-das-geprueft]####Warum wird das geprüft?

Unerwartete und unangekündigte Kontextänderungen bei einer Auswahl in Formularen (etwa eine Checkbox oder ein Radio-Button, deren Auswahl eine neue Seite aufruft, oder eine Auswahlliste ohne Submit-Button, die auf `onchange` reagiert) können die Orientierung von Nutzern beeinträchtigen. Kontextänderungen auf der Seite selbst können Nutzer ablenken und verwirren oder auch unbemerkt bleiben und dadurch für Verwirrung sorgen (plötzlich sind Inhalte verändert). Sie sollten deshalb erwartet und klar nachvollziehbar sein.

Wenn Kontextänderungen auf der selben Seite nicht *unterhalb* des Elements stattfinden, das sie auslöst, werden sie von blinden Nutzer häufig nicht wahrgenommen.

== [#wie-wird-geprueft]####Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Seite Formularelemente enthält.

=== 2. Prüfung

. Seite im Browser (Chrome oder Firefox) aufrufen.
. [#F36]####[#F37]####Formularelemente (Checkboxes, Radio Buttons, Auswahllisten) ausprobieren. Werden unerwartete und nicht angekündigte Kontextänderungen erzeugt?
. [#G80]####[#H32]####[#H84]####[#F9]####[#F60]####Überprüfen, ob Inhaltsänderungen hervorgerufen werden (etwa Einblendungen zusätzlicher Formularfelder). Sind die Inhaltsänderungen begrenzt und gut nachvollziehbar [#G13]####[#F76]####oder werden *vor* dem auslösenden Element angekündigt bzw. erklärt?
. Prüfen, ob Inhaltsänderungen *unterhalb* des Elements, das sie auslöst, hervorgerufen werden.
. Prüfen, ob durch Formulareingaben hervorgerufene Kontextänderungen (etwa dynamisch eingeblendete Elemente) den aktuellen Fokus versetzen.

=== 3. Hinweise

Fehlermeldungen, die über die Javascript-Funktion `alert()` ausgegeben werden, gelten nicht als Pop-Ups im Sinne des Prüfschritts. Denn sie öffnen sich als Antwort auf Benutzereingaben und sie sind modal, in Hinblick auf die Orientierung daher unproblematisch.

Änderungen, die über Skripte und _ARIA Live Regions_ vorgenommen werden, etwa die automatische Einblendung von Vorschlägen unterhalb des Texteingabefelds einer Such-Funktion, sollen nicht den aktuellen Fokus versetzen.

Zur Abgrenzung von Kontextänderungen und Inhaltsänderungen:

* Klare Kontextänderungen (_changes of context_) sind laut WCAG 2.1 etwa Sprünge zu anderen Seiten und das Öffnen neuer Fenster, aber auch das dynamische Laden von neuen Inhalten auf der selben Seite, wenn diese Inhalte wie eine neue Seite _wirken_ oder Inhalte in stark veränderter Anordnung erscheinen. Auch das Auslösen von Sprunglinks zu Ankern auf derselben Seite ist als Kontextänderung zu betrachten.
* Davon abgrenzen muss man bloße Inhaltsänderungen (in den WCAG 2.1: _changes of content_). Diese liegen vor, wenn etwa die Auswahl in einer Auswahlliste (`select`) die Inhalte einer darunter befindlichen Auswahlliste dynamisch aktualisiert (etwa: die Wahl eines Kontinents aktualisiert eine Auswahlliste mit Ländern). Auch das Ausklappen zusätzlicher Formularbereiche _unterhalb_ des auslösenden Elements kann als Inhaltsänderung gelten, wenn Fokus und Scrollstatus der Seite unverändert bleiben.

Ob Änderungen _unerwartet_ sind oder nicht, lässt sich nur aus dem Gesamtkontext heraus bestimmen.

Vergleiche: WCAG 2.1, Appendix A: Glossary: http://www.w3.org/TR/WCAG20/#context-changedef[changes of context]

=== 4. Bewertung

==== Nicht voll erfüllt:

* Die Interaktion mit Formularelementen führt zu unerwarteten und nicht angekündigten Kontextänderungen.

==== Nicht erfüllt:

* Formulare werden automatisch abgeschickt, wenn der Fokus das Formular verlässt.
* Das Ändern des Status einer Checkbox oder eines Radio-Buttons löst automatisch eine unerwartete Kontextänderung aus (öffnet etwa ein neues Fenster).

== [#einordnung-des-pruefschritts]####Einordnung des Prüfschritts

=== Abgrenzung von anderen Prüfschritten

Die Verwendung von Submit-Buttons, die in den Techniken https://www.w3.org/WAI/WCAG21/Techniques/general/G80.html[G80] und https://www.w3.org/WAI/WCAG21/Techniques/html/H32.html[H32] dem Success Criterion https://www.w3.org/TR/WCAG21/#on-input[3.2.2 On Input [no automatic change of context]] zugeordnet ist, wird nur indirekt im Prüfschritt 2.1.1a "Ohne Maus nutzbar" geprüft.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#predictable[Guideline 3.2 Predictable: Make Web pages appear and operate in predictable ways]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#on-input[3.2.2 On Input] (Level A)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G80.html[G80: Providing a submit button to initiate a change of context using a technology-specific technique listed below] +
_Hinweis:_ Die Technik G80 ist SC 3.2.2 zugeordnet, wird aber nur indirekt geprüft.
* https://www.w3.org/WAI/WCAG21/Techniques/general/G13.html[G13: Describing what will happen before a change to a form control that causes a change of context to occur is made]

===== HTML Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/html/H32.html[H32: Providing submit buttons]. +
_Hinweis:_ Die Technik H32 ist SC 3.2.2 zugeordnet, wird aber nur indirekt geprüft.
* https://www.w3.org/WAI/WCAG21/Techniques/html/H84.html[H84: Using a button with a select element to perform an action]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F36.html[F36: Failure of Success Criterion 3.2.2 due to automatically submitting a form and presenting new content without prior warning when the last field in the form is given a value]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F37.html[F37: Failure of Success Criterion 3.2.2 due to launching a new window without prior warning when the status of a radio button, check box or select list is changed]
