= Prüfschritt 9.4.1.1 Korrekte Syntax
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Die verwendete Markup-Sprache HTML muss korrekt eingesetzt werden.
Dabei muss für jedes Element folgendes gewährleistet sein:

* Sie besitzen vollständige Start- und Endtags
* sie sind gemäß Spezifikation korrekt verschachtelt
* sie enthalten keine doppelten Attribute
* alle ihre IDs sind eindeutig, außer dort wo die Spezifikationen etwas
  anderes erlauben

== Warum wird das geprüft?

Eine saubere HTML-Syntax vereinfacht Browsern oder Screenreadern den Umgang
mit der Seite.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

=== 2. Prüfung mit dem W3C-Validator

. Seite im Chrome-Browser aufrufen.
. Bookmarklet
  https://validator.w3.org/nu/about.html#extras[
  Check serialized DOM of current page] nutzen, um die Validität des
  geparsten Quelltextes im
  https://validator.w3.org/[
  W3C-Validator] zu prüfen.
  Falls das Bookmarklet nicht funktioniert, im Validator also nichts angezeigt
  wird, den DOM-Code kopieren und direkt im W3C Validator im Tab 'Validate by
  direct Input' eingeben (hier muss ggf. eine nicht mitkopierte DOCTYPE
  Erklärung der Seite zu Beginn eingefügt werden, z. B. bei HTML5 die Zeile
  ``<!DOCTYPE html>``).
. Falls Fehler angezeigt werden (Error), also die Seite nicht validiert, mit dem https://bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste.html#parsingerror[Syntax Only Bookmarklet] die Fehler filtern.
. Prüfen, ob nach der Anwendung des Bookmarklets noch Fehler vorhanden sind.

=== 3. Hinweise

* Die in HTML5 vorgesehenen validen Custom-Attribute nutzen das Format
  `data-$$*$$`, zum Beispiel `data-platznummer="44"`.
  Manche Scripting Frameworks nutzen eigene Formate.
  Angular.js etwa nutzt das Format `ng-$$*$$`.
  Trotz fehlender Validität sind solche Custom-Attribute grundsätzlich kein
  Barrierefreiheits-Problem, solange sie semantisch korrekt (also z. B. mit
  korrekt öffnenden und schließenden Anführungszeichen) eingesetzt sind.
  Browser ignorieren Attribute, die nicht zugeordnet werden können.
* In diesem Prüfschritt wird das vom Browser nach Auswertung von Scripten
  generierte DOM geprüft, nicht der Seitenquelltext vor Interpretation im
  Browser.

=== 4. Bewertung

==== Erfüllt

* Das Prüfergebnis des W3C-HTML-Validators ist nach Anwendung des WCAG
  parsing only Bookmarklet positiv.
  Falls noch Fehler (Errors) auftauchen, sind diese auf den semantisch
  korrekten Einsatz von Custom-Attributen zurückzuführen.

==== Eher erfüllt

* Das Prüfergebnis des W3C-HTML-Validators zeigt auch nach Anwendung des Syntax only Bookmarklets Fehler.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.2

==== Guideline

* https://www.w3.org/TR/WCAG21/#compatible[
  Guideline 4.1 Compatible: Maximize compatibility with current and future
  user agents, including assistive technologies.]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#parsing[
  4.1.1 Parsing] (Level A)

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G134.html[
  G134: Validating Web pages]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G192.html[
  G192: Fully conforming to specifications]

===== HTML Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/html/H74.html[
  H74: Ensuring that opening and closing tags are used according to
  specification]
* https://www.w3.org/WAI/WCAG21/Techniques/html/H75.html[
  H75: Ensuring that Web pages are well-formed]
* https://www.w3.org/WAI/WCAG21/Techniques/html/H88.html[
  H88: Using HTML according to spec]
* https://www.w3.org/WAI/WCAG21/Techniques/html/H93.html[
  H93: Ensuring that `id` attributes are unique on a Web page]

===== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F70.html[
  F70: Failure of Success Criterion 4.1.1 due to incorrect use of start and
  end tags or attribute markup]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F77.html[
  F77: Failure of Success Criterion 4.1.1 due to duplicate values of type ID]

== Quellen

=== WCAG Note zum Umgang mit dem Erfolgskriterium 4.1.1 Parsing (entfernt in WCAG 2.2, immer erfüllt in WCAG 2.0 und 2.1)

https://www.w3.org/WAI/WCAG21/Understanding/parsing.html[Understanding SC 4.1.1:Parsing (Level A)]

